Replace all Module's and Block's with ModuleScope and Scope
maxitg/SetReplace pull request #461
Opened 2020-10-14 03:08 UTC by daneelsan

## Changes
* Closes #460.
* Replaces (almost) all `Module`'s with `ModuleScope`'s.
* Adds ```PackageImport["GeneralUtilities`"]``` where `ModuleScope` was used.

## Comments
* _Work in progress_

## Examples
* Add explicit inputs and outputs (as screenshots in case of graphics) showcasing new functionality.

2020-10-14 03:20 UTC, maxitg reviewed
By the way, we still want to use `Module` in pattern rules (e.g., `{{a_, b_}} :> Module[{c}, {{a, c}, {c, b}}]`). `ModuleScope` is undocumented so we cannot expose it to users.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461#-:-MJ_6YIV6Lx7FdNoNWuq:byl0ze6)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)

___
*[Kernel/RulePlot.m, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/461#-MJ_5uihEcBaIwuqoBgx:-MJ_5uihEcBaIwuqoBgy:bz521k5) ([raw file](https://github.com/maxitg/setreplace/blob/57fc955e5f66a00058a17298c38a887299dd6eff/Kernel/RulePlot.m#L3)):*
> ```objc
> Package["SetReplace`"]
> 
> PackageImport["GeneralUtilities`"]
> ```

We should import it once in `Kernel/init.m`.


<!-- Sent from Reviewable.io -->

2020-10-14 03:30 UTC, daneelsan reviewed
Yes, was thinking the same.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461#-:-MJ_97576mSeZUBXCV7g:b-yru7e)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[Kernel/RulePlot.m, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/461#-MJ_5uihEcBaIwuqoBgx:-MJ_91CI7QjLMjOiWF00:b4o1gej) ([raw file](https://github.com/maxitg/setreplace/blob/57fc955e5f66a00058a17298c38a887299dd6eff/Kernel/RulePlot.m#L3)):*
Haven't tried it yet, but according to https://mathematica.stackexchange.com/questions/176434/declaring-package-with-dependencies-in-multiples-files/176489#176489:
> Regarding PackageImport, one non-obvious thing is that a package, imported in one fragment, is not considered imported in others. This means that, if you use some package in several fragments of your new-style package, you need to PackageImport it in all of them, even though they are parts of the same big package you are developing. This behavior has both pros and cons, although it may often seem an inconvenience.


<!-- Sent from Reviewable.io -->

2020-10-14 03:45 UTC, maxitg reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)

___
*[Kernel/RulePlot.m, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/461#-MJ_5uihEcBaIwuqoBgx:-MJ_CE4DB7Hr3bpClmeg:b8ynqmp) ([raw file](https://github.com/maxitg/setreplace/blob/57fc955e5f66a00058a17298c38a887299dd6eff/Kernel/RulePlot.m#L3)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Haven't tried it yet, but according to https://mathematica.stackexchange.com/questions/176434/declaring-package-with-dependencies-in-multiples-files/176489#176489:
> Regarding PackageImport, one non-obvious thing is that a package, imported in one fragment, is not considered imported in others. This means that, if you use some package in several fragments of your new-style package, you need to PackageImport it in all of them, even though they are parts of the same big package you are developing. This behavior has both pros and cons, although it may often seem an inconvenience.
</blockquote></details>

`init.m` could be an exception since it does not have an ordinary "package fragment" header. Not sure about that.


<!-- Sent from Reviewable.io -->

2020-10-14 04:18 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[Kernel/RulePlot.m, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/461#-MJ_5uihEcBaIwuqoBgx:-MJ_Juzt9LHu__K0WfMt:b-9q5hzz) ([raw file](https://github.com/maxitg/setreplace/blob/57fc955e5f66a00058a17298c38a887299dd6eff/Kernel/RulePlot.m#L3)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`init.m` could be an exception since it does not have an ordinary "package fragment" header. Not sure about that.
</blockquote></details>

I tried adding:
```wl
ClearAll @@ ...

Needs["GeneralUtilities`"];

Get["SetReplace`Kernel`usageString"];
...
```
but apparently it did not work.


<!-- Sent from Reviewable.io -->

2020-10-14 04:24 UTC, maxitg reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Kernel/RulePlot.m, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/461#-MJ_5uihEcBaIwuqoBgx:-MJ_LRZACRNOyziF66FF:b-aml8du) ([raw file](https://github.com/maxitg/setreplace/blob/57fc955e5f66a00058a17298c38a887299dd6eff/Kernel/RulePlot.m#L3)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

I tried adding:
```wl
ClearAll @@ ...

Needs["GeneralUtilities`"];

Get["SetReplace`Kernel`usageString"];
...
```
but apparently it did not work.
</blockquote></details>

Ok, thanks for checking!


<!-- Sent from Reviewable.io -->

2020-10-15 02:15 UTC, maxitg commented
As far as I understand, `ModuleScope` has to be directly after `SetDelayed` because of how it's defined:
```wl
In[] := UpValues[ModuleScope][[2]]
Out[] = HoldPattern[
  HoldPattern[
   GeneralUtilities`Control`PackagePrivate`sd : (_ := _ModuleScope)]] \
:> MacroEvaluate[GeneralUtilities`Control`PackagePrivate`sd]
```

However, there is `MacroEvaluate` that can find `ModuleScope` anywhere inside a function:
```wl
In[] := MacroEvaluate[f[x_] := Sqrt[ModuleScope[e = z; 2 z]]]
In[] := DownValues[f]
Out[] = {HoldPattern[f[x_]] :> Sqrt[Module[{e}, e = z; 2 z]]}
```

2020-10-15 02:30 UTC, daneelsan commented
Ah, I saw that too, but `RuleDelayed` and `ModuleScope` being inside a function also works...
```wl
MacroExpand[f[] :> Function[x,
   ModuleScope[y = 0; y/x]]
 ]
```
![image](https://user-images.githubusercontent.com/40190339/96069782-87098a80-0e64-11eb-8f91-3eb2171f16f6.png)

2020-10-15 02:55 UTC, taliesinb commented
`MacroExpand` is misleading: it *always* finds macros no matter how deep, so this doesn't tell you whether this macro will be evaluated during package loading.

In fact, Max is right, macros have to appear as the outermost head inside the `:=` (`SetDelayed`) for them to trigger during package loading. 

If you want to 'bury' a macro deeper into a function definition, you can use the 'no-op' `UseMacros` function to force the body to be macro-evaluated at load time:

```
foo[...] := UseMacros[
	...
	...
]
```

> On Oct 15, 2020, at 4:31 AM, Daniel Sanchez <notifications@github.com> wrote:
> 
> 
> Ah, I saw that too, but RuleDelayed and ModuleScope being inside a function also works...
> 
> MacroExpand[f[] :> Function[x,
>    ModuleScope[y = 0; y/x]]
>  ]
>  <https://user-images.githubusercontent.com/40190339/96069782-87098a80-0e64-11eb-8f91-3eb2171f16f6.png>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/maxitg/SetReplace/pull/461#issuecomment-708855520>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AACZEZPWVZYUDOUGYEC6CXLSKZNG3ANCNFSM4SQAZA6Q>.
>

2020-10-15 02:57 UTC, taliesinb commented
Just to clarify: `MacroExpand` *always* finds macros no matter how deep, so this doesn't tell you whether this macro will be evaluated during package loading if you do *not* use `MacroExpand`.

In other words, Max is right, macros have to appear as the outermost head inside the `:=` (`SetDelayed`) for them to trigger during package loading. 

If you want to 'bury' a macro deeper into a function definition, you can use the 'no-op' `UseMacros` function to force the body to be macro-evaluated at load time:

```
foo[...] := UseMacros[
	...
	...
]
```

2020-10-15 03:03 UTC, taliesinb reviewed
This looks good to me, but I just wanted to highlight one potential issue (I did not spot it occurring however): if there is a global variable that is changed from within a ModuleScope function, it will *become* localized by the ModuleScope, and so the change will no longer have an effect. I imagine there aren't any such global variables that are mutated within functions in SetReplace, since this is a weird thing to do -- @maxitg do you know if there are any in particular we should look out for?

2020-10-15 03:06 UTC, daneelsan commented
Is it worth replacing `ModuleScope` with `Module` in those cases? 
Are the benefits of using these macros greater than "always" using `UseMacros` at the beginning?
I'm thinking about how the guidelines should be updated, which should not confuse the developer/reviewer.

2020-10-15 03:15 UTC, taliesinb commented
@daneelsan I'm not sure I understand what you're proposing with respect to `UseMacros`. Which "beginning" are you referring to? Just to recap: `UseMacros` does not localize variables. It just forces macro evaluation to happen to any *other* macros when they are deeper than the RHS of the SetDelayed. 

But to go back to the original point: you shouldn't be assigning global variables unless it is for a very good reason (the only reasons I've ever seen are caching or debugging), and it'll be obvious that you "need to do something special" (namely `^=` instead of `=`) for them to not be localized -- `?ModuleScope` explains this carefully.

2020-10-15 18:07 UTC, taliesinb approved these changes

2020-10-15 18:49 UTC, maxitg requested changes
I assume, this is still a work in progress, but I left some comments below for what's currently here.

> Reviewed 17 of 18 files at r2, 2 of 3 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461#-:-MJh_tA3EG3dYBEj8k23:b-561hlj)* status: all files reviewed, 8 unresolved discussions (waiting on @daneelsan)

___
*[Kernel/RulePlot.m, line 223 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhUqFQ0gHpLeYDbV5_:-MJhUqFQ0gHpLeYDbV5a:bezk3qq) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/RulePlot.m#L223)):*
> ```objc
>     graphicsOpts_] := ModuleScope[
>   explicitSpacings = toListSpacings[Replace[spacings, Automatic -> style[$lightTheme][$ruleSidesSpacing]]];
>   hypergraphPlots =
> ```

That's a fixed weed. Nice!
___
*[Kernel/setSubstitutionSystem.m, line 273 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhVQXF1BnavAhU2kPm:-MJhVQXF1BnavAhU2kPn:b-pfn6wk) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/setSubstitutionSystem.m#L273)):*
> ```objc
>     caller, "EventDeduplication", OptionValue["EventDeduplication"], $eventDeduplications];
>   symbolicEvaluationSupportedQ = OptionValue["EventOrderingFunction"] === Automatic &&
>                                    OptionValue["EventSelectionFunction"] === "GlobalSpacelike" &&
> ```

Nit: move the indentation two spaces to the left. Same on the next line.
___
*[Kernel/testUtilities.m, line 26 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhWo61EDbM9T8WkoR3:-MJhWo61EDbM9T8WkoR4:b-m29irk) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/testUtilities.m#L26)):*
> ```objc
> testSymbolLeak[testHead_, expr_, opts___] :=
>   testHead[
>     ModuleScope[
> ```

This one does not work correctly because there is `testHead` after `:=`.
___
*[Kernel/WolframModelEvolutionObject.m, line 558 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhXHsW58ZiKUQ2s6Om:-MJhXHsW58ZiKUQ2s6On:b-y1drkj) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelEvolutionObject.m#L558)):*
> ```objc
>   events = propertyEvaluate[True, boundary][obj, caller, "AllEventsList"][[All, 2]];
>   stateIndices = FoldList[
>     Function[{currentState, newEvent}, ModuleScope[
> ```

This one won't work as well.
___
*[Kernel/WolframModelEvolutionObject.m, line 706 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhXZye0vQWEJomHz9Q:-MJhXZye0vQWEJomHz9R:bqyqjse) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelEvolutionObject.m#L706)):*
> ```objc
>   automaticVertexLabelsPattern = Automatic | Placed[Automatic, ___];
>   If[MatchQ[vertexLabelsOptionValue, automaticVertexLabelsPattern],
>     rules = rulesList[propertyEvaluate[True, None][obj, caller, "Rules"]];
> ```

`rules` here will probably not be captured by `ModuleScope` because they are not at the top level. The same for other variables below.
___
*[Kernel/WolframModelPlot.m, line 142 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhY9Ww1BA36O0sBEQU:-MJhY9Ww1BA36O0sBEQV:b-lmjen8) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelPlot.m#L142)):*
> ```objc
>       edges : $hypergraphPattern, edgeType : Alternatives @@ $edgeTypes : $defaultEdgeType, o : OptionsPattern[]] /;
>         correctWolframModelPlotOptionsQ[WolframModelPlot, Defer[WolframModelPlot[edges, o]], edges, {o}] := ModuleScope[
>   optionValue[opt_] := OptionValue[WolframModelPlot, {o}, opt];
> ```

@taliesinb, will this work?
___
*[Kernel/WolframModelPlot.m, line 505 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhYj6aAsKTiRgQb_Jf:-MJhYj6aAsKTiRgQb_Jg:bwkzpft) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelPlot.m#L505)):*
> ```objc
>       embedding_] := ModuleScope[
>   singleVertexEdgeCounts = <||>;
>   getSingleVertexEdgeRadius[coords_] := (
> ```

Similarly, will this work (a `DownValues` definition inside a module)?
___
*[Tests/SetReplace.wlt, line 171 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhZSOd6cFNxHOuqAy-:-MJhZSOd6cFNxHOuqAy0:b-9qr7ka) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Tests/SetReplace.wlt#L171)):*
> ```Mathematica
> 
>       VerificationTest[
>         ModuleScope[
> ```

I think we should keep using the ordinary `Module` in the test cases given that they are only supposed to use public functions (and the `Module`s here will never be very large). I only mean it for `Module`s inside `VerificationTest` (plus, it won't work in this case anyway). We can still replace `Module`s used for constructing tests with `ModuleScope`.


<!-- Sent from Reviewable.io -->

2020-10-15 21:40 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: all files reviewed, 7 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Kernel/RulePlot.m, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/461#-MJ_5uihEcBaIwuqoBgx:-MJiAjlEAoxfkvH7mK0u:blyphgc) ([raw file](https://github.com/maxitg/setreplace/blob/57fc955e5f66a00058a17298c38a887299dd6eff/Kernel/RulePlot.m#L3)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Ok, thanks for checking!
</blockquote></details>

No problem!
___
*[Kernel/RulePlot.m, line 223 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhUqFQ0gHpLeYDbV5_:-MJiA_hy3sm222PBEwWT:bnlp9vc) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/RulePlot.m#L223)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

That's a fixed weed. Nice!
</blockquote></details>

:weed:
___
*[Kernel/setSubstitutionSystem.m, line 273 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhVQXF1BnavAhU2kPm:-MJiAZaKC3D74wR4ty5I:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/setSubstitutionSystem.m#L273)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Nit: move the indentation two spaces to the left. Same on the next line.
</blockquote></details>

Done.
___
*[Kernel/testUtilities.m, line 26 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhWo61EDbM9T8WkoR3:-MJiAYPk56NipWwK0ZLf:bt2vr1b) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/testUtilities.m#L26)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This one does not work correctly because there is `testHead` after `:=`.
</blockquote></details>

Fixed.
___
*[Kernel/WolframModelEvolutionObject.m, line 558 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhXHsW58ZiKUQ2s6Om:-MJiAXQz0qu3X8yoLr-f:bt2vr1b) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelEvolutionObject.m#L558)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This one won't work as well.
</blockquote></details>

Fixed.
___
*[Kernel/WolframModelEvolutionObject.m, line 706 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhXZye0vQWEJomHz9Q:-MJiATyWASO0i8wZjAgS:bj35qyp) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelEvolutionObject.m#L706)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`rules` here will probably not be captured by `ModuleScope` because they are not at the top level. The same for other variables below.
</blockquote></details>

It seems they got captured.

![image.png](https://files.reviewableusercontent.io/images/reviewable/40190339/WK1snnab-RXZjR_DHMKniXmM/image.png)
___
*[Kernel/WolframModelPlot.m, line 142 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhY9Ww1BA36O0sBEQU:-MJiB0rR1OFGJaGoWVv6:bioj6t0) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelPlot.m#L142)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

@taliesinb, will this work?
</blockquote></details>

It didn't.

![image.png](https://files.reviewableusercontent.io/images/reviewable/40190339/54vnvt7sWs_YcOCE__Gijrfd/image.png)

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/40190339/vGSAJAhhFbgLeU1WEl16NYKO/image.png)

I'll fix this with `ScopeVariable`.
___
*[Kernel/WolframModelPlot.m, line 505 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhYj6aAsKTiRgQb_Jf:-MJiBZgg30oOUD4FMADE:bt2vr1b) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelPlot.m#L505)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Similarly, will this work (a `DownValues` definition inside a module)?
</blockquote></details>

Fixed.
___
*[Tests/SetReplace.wlt, line 171 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhZSOd6cFNxHOuqAy-:-MJiBnJQ4KvA1piEVem4:b-pbdqzg) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Tests/SetReplace.wlt#L171)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think we should keep using the ordinary `Module` in the test cases given that they are only supposed to use public functions (and the `Module`s here will never be very large). I only mean it for `Module`s inside `VerificationTest` (plus, it won't work in this case anyway). We can still replace `Module`s used for constructing tests with `ModuleScope`.
</blockquote></details>

Agreed!


<!-- Sent from Reviewable.io -->

2020-10-17 00:16 UTC, maxitg requested changes
There are some replaceable `Module`s left in `buildInit.wl`, `performanceTest.wls` and `test.wls`.

We should also change `Module` to `ModuleScope` in the `MakeUniverse` example from contributing, and add a comment to the Wolfram Language code style section that we are using `ModuleScope` from `GeneralUtilities`.

> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461#-:-MJnqrWl6I10axPHVnwe:bnqmvew)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)

___
*[Kernel/setSubstitutionSystem.m, line 264 at r7](https://reviewable.io/reviews/maxitg/setreplace/461#-MJnrN4k8LtlILUEQYUZ:-MJnrN4k8LtlILUEQYU_:b-oekupi) ([raw file](https://github.com/maxitg/setreplace/blob/1a38f27f0f020bc697c0ed4fd1ccd54db60b531b/Kernel/setSubstitutionSystem.m#L264)):*
> ```objc
>       returnOnAbortQ_,
>       o : OptionsPattern[]] /;
>         stepSpecQ[caller, set, stepSpec, OptionValue[setSubstitutionSystem, {o}, "EventSelectionFunction"]] := ModuleScope[
> ```

This line goes over the character limit.
___
*[Kernel/WolframModelEvolutionObject.m, line 706 at r5](https://reviewable.io/reviews/maxitg/setreplace/461#-MJhXZye0vQWEJomHz9Q:-MJnqJtc0gdCHEwct7tw:bhn3ge0) ([raw file](https://github.com/maxitg/setreplace/blob/72e7e7a50a1a49b746ee003232f4a2707decba75/Kernel/WolframModelEvolutionObject.m#L706)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

It seems they got captured.

![image.png](https://files.reviewableusercontent.io/images/reviewable/40190339/WK1snnab-RXZjR_DHMKniXmM/image.png)

</blockquote></details>

Indeed! It's smarted than I expected.


<!-- Sent from Reviewable.io -->

2020-10-17 03:28 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: 22 of 27 files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[Kernel/setSubstitutionSystem.m, line 264 at r7](https://reviewable.io/reviews/maxitg/setreplace/461#-MJnrN4k8LtlILUEQYUZ:-MJoaPFcCbAVwa5iSxQY:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1a38f27f0f020bc697c0ed4fd1ccd54db60b531b/Kernel/setSubstitutionSystem.m#L264)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This line goes over the character limit.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-17 05:51 UTC, maxitg requested changes
> Reviewed 1 of 1 files at r8, 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: all files reviewed, 3 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 398 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJouvMRC8vUVyM2b4bU:-MJouvMRC8vUVyM2b4bV:b-qohc1j) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L398)):*
> ```Markdown
>       graphicsOptions_] := Catch[
>         ...
>       ]
> ```

The closing bracket should not be indented.
___
*[.github/CONTRIBUTING.md, line 412 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJovBJ495y1nH-sPzAO:-MJovBJ495y1nH-sPzAP:b-ybwvul) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L412)):*
> ```Markdown
> 
> * Start global constants with `$`, whether internal or public, and tags (such as used in [`Throw`](https://reference.wolfram.com/language/ref/Throw.html) or [`Sow`](https://reference.wolfram.com/language/ref/Sow.html), or as generic enum labels) with `$$`. Global pure functions (defined as [`OwnValues`](https://reference.wolfram.com/language/ref/OwnValues.html)) should still be treated as ordinary (e.g., [`DownValues`](https://reference.wolfram.com/language/ref/DownValues.html)) functions and not start with `$`, unless they are public, in which case they should start with `$` and end with the word `Function`.
> * Use the macros `ModuleScope` and `Scope` (defined in "GeneralUtilities\`") instead of `Module` and `Block` (respectively) when defining functions of the form `f[x__] := (Module|Block)[...]`. The main benefit of using them is that there is no need to specify a list of local variables (i.e. `{localVar1, localVar2, ...}`) at the begining, as these will be localized whenever the macro detects the presence of `=` and `:=` in its body (See `?Scope` and [#460](https://github.com/maxitg/SetReplace/pull/460) for more information). For example:
> ```

I think it would be clearer if we say, "... the presence of `=` and `:=` anywhere in its body ...".
___
*[.github/CONTRIBUTING.md, line 417 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJovOWYCIXG5Jbf8b4T:-MJovOWYCIXG5Jbf8b4U:bud82x7) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L417)):*
> ```Markdown
>   decodeAtomLists[list_List] := ModuleScope[
>     count = list[[1]];
>     atomPointers = list[[2 ;; (count + 1) + 1]];
> ```

I think it would be useful to have two things in the example:
1. A definition with a list on the left-hand side: `{a, b} = ...`.
2. A definition nested inside of something (e.g., `If[..., c = ..., ...]`).

It was not obvious to me that it works in these cases.


<!-- Sent from Reviewable.io -->

2020-10-17 06:05 UTC, maxitg requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: all files reviewed, 4 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 412 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJp92t30QqnErIWwhaR:-MJp92t30QqnErIWwhaS:b-ofxr5) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L412)):*
> ```Markdown
> 
> * Start global constants with `$`, whether internal or public, and tags (such as used in [`Throw`](https://reference.wolfram.com/language/ref/Throw.html) or [`Sow`](https://reference.wolfram.com/language/ref/Sow.html), or as generic enum labels) with `$$`. Global pure functions (defined as [`OwnValues`](https://reference.wolfram.com/language/ref/OwnValues.html)) should still be treated as ordinary (e.g., [`DownValues`](https://reference.wolfram.com/language/ref/DownValues.html)) functions and not start with `$`, unless they are public, in which case they should start with `$` and end with the word `Function`.
> * Use the macros `ModuleScope` and `Scope` (defined in "GeneralUtilities\`") instead of `Module` and `Block` (respectively) when defining functions of the form `f[x__] := (Module|Block)[...]`. The main benefit of using them is that there is no need to specify a list of local variables (i.e. `{localVar1, localVar2, ...}`) at the begining, as these will be localized whenever the macro detects the presence of `=` and `:=` in its body (See `?Scope` and [#460](https://github.com/maxitg/SetReplace/pull/460) for more information). For example:
> ```

Also, ``"GeneralUtilities`"`` should be formatted as code (use two backticks on each side), i.e., ``` ``"GeneralUtilities`"`` ```.


<!-- Sent from Reviewable.io -->

2020-10-17 13:09 UTC, taliesinb requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: all files reviewed, 4 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[.github/CONTRIBUTING.md, line 412 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJovBJ495y1nH-sPzAO:-MJqeagO5tuRSLtg23Am:b17lddl) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L412)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think it would be clearer if we say, "... the presence of `=` and `:=` anywhere in its body ...".
</blockquote></details>

I think we should be more explicit and say "as a list of local variables will be automatically generated by lookin for expressions of the form `Set` (`=`) or `SetDelayed` (`:=`) in the body of the function"? .
___
*[.github/CONTRIBUTING.md, line 417 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJovOWYCIXG5Jbf8b4T:-MJqf0_B4DO-54e6XttY:b-8ayu6x) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L417)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think it would be useful to have two things in the example:
1. A definition with a list on the left-hand side: `{a, b} = ...`.
2. A definition nested inside of something (e.g., `If[..., c = ..., ...]`).

It was not obvious to me that it works in these cases.
</blockquote></details>

Agree


<!-- Sent from Reviewable.io -->

2020-10-17 17:05 UTC, maxitg requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: all files reviewed, 4 unresolved discussions (waiting on @daneelsan, @maxitg, and @taliesinb)

___
*[.github/CONTRIBUTING.md, line 412 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJovBJ495y1nH-sPzAO:-MJrVz_NDeGTHnf86ZUm:bizy9kg) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L412)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

I think we should be more explicit and say "as a list of local variables will be automatically generated by lookin for expressions of the form `Set` (`=`) or `SetDelayed` (`:=`) in the body of the function"? .
</blockquote></details>

I agree, but add, "... *anywhere* in the body of the function." We should make it clear it works inside `If`s, `Nest`s and such.


<!-- Sent from Reviewable.io -->

2020-10-18 03:07 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: 26 of 27 files reviewed, 4 unresolved discussions (waiting on @maxitg)

___
*[.github/CONTRIBUTING.md, line 398 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJouvMRC8vUVyM2b4bU:-MJtf2q51riJrEYZzwb3:br21pzf) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L398)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The closing bracket should not be indented.
</blockquote></details>

Nice catch, fixed.
___
*[.github/CONTRIBUTING.md, line 412 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJovBJ495y1nH-sPzAO:-MJtf4z2B8mpDj2loPEY:baox8aj) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L412)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I agree, but add, "... *anywhere* in the body of the function." We should make it clear it works inside `If`s, `Nest`s and such.
</blockquote></details>

I used both of your suggestions.
___
*[.github/CONTRIBUTING.md, line 412 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJp92t30QqnErIWwhaR:-MJtfAwRCOCp178DutFB:b-t2i4he) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L412)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Also, ``"GeneralUtilities`"`` should be formatted as code (use two backticks on each side), i.e., ``` ``"GeneralUtilities`"`` ```.
</blockquote></details>

Didn't know how to format back tick. Done.
___
*[.github/CONTRIBUTING.md, line 417 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJovOWYCIXG5Jbf8b4T:-MJtfEy0EYOlctbH8Pcv:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L417)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-18 03:22 UTC, maxitg approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[.github/CONTRIBUTING.md, line 412 at r9](https://reviewable.io/reviews/maxitg/setreplace/461#-MJp92t30QqnErIWwhaR:-MJthsv00i0z291MliOF:btrlp0b) ([raw file](https://github.com/maxitg/setreplace/blob/74b792cce81380a543944323f2b00d3522d81ee7/.github/CONTRIBUTING.md#L412)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Didn't know how to format back tick. Done.
</blockquote></details>

Basically, if some backticks "escape", just keep adding more backticks to the sides, e.g., ```` ```test``backticks`here` ``` ```` produces ```test``backticks`here` ```.


<!-- Sent from Reviewable.io -->

2020-10-18 03:25 UTC, daneelsan commented
@maxitg ````L`G`T`M````

2020-10-19 17:49 UTC, taliesinb approved these changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/461)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-19 19:09 UTC, merged