Extracted readme sections into `Documentation` directory
maxitg/SetReplace pull request #466
Opened 2020-10-14 07:04 UTC by wawo9193

## Changes
* Changes for #464 
* Moved most of readme besides introduction and physics/acknowledgements into `Documentation` directory.
* Two different Image Folders - `READMEImages` and `DocsImages` in their respective places for direct path access.
* Fixed links using relative linking in markdown, and header link references preserved.
* Corrected image file paths as well.

## Comments
* No code changes done, so no testing necessary

## Examples
* Refer to `Documentation` directory, let me know of any changes I can make

2020-10-14 18:30 UTC, maxitg requested changes
Thanks a lot for contributing! See the comments on the individual files below. Also:
* I think we can hide the READMEImages directory in Documentation, i.e., `READMEImages -> Documentation/Images`.
* Also, I think we should rename "DocsImages" -> "Images". It's already in the docs directory, so "Docs" is redundant.
* "Rule Specification", "Automatic Initial State", and "Options" sections are nowhere to be found.
* Related to that, many links lead to "Properties" instead of "Options" and are broken because of that.
* Some of the links in /.github/CONTRIBUTING.md and /Research/LocalMultiwaySystem/LocalMultiwaySystem.md are now broken.
* There are many links with anchors leading to the top of the page (e.g., `WolframModelPlot.md#wolframmodelplot`). We don't need anchors in these cases.
* Add empty lines at the ends of files to be consistent with the rest of the repo.
* We should keep a hierarchy in the "Documentation" directory. For example, `Documentation/Properties.md` should be `Documentation/WolframModelAndWolframModelEvolutionObject/Properties.md`.

> Reviewed 10 of 121 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466#-:-MJc6kIT-2N3kIyZ5wn-:bmk9879)* status: 10 of 121 files reviewed, 15 unresolved discussions (waiting on @wawo9193)

___
*[README.md, line 3 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc5tWM5IAJrmyrEY3u:-MJc5tWN7VpQm-sTSrxB:b-xtupdy) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/README.md#L3)):*
> ```Markdown
> [![Discord](https://img.shields.io/discord/761616685173309481?logo=Discord)](https://discord.setreplace.org)
> 
> [Wolfram Models as Set Substitution Systems](#wolfram-models-as-set-substitution-systems) | [Getting Started](#getting-started) | [Symbols and Functions](#symbols-and-functions) | [Physics](#physics) | [Acknowledgements](#acknowledgements)
> ```

Symbols and Functions should lead to the new page.
___
*[README.md, line 95 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc5y6W1JTu4BZabx1T:-MJc5y6W1JTu4BZabx1U:b-1f4oa9) ([raw file](https://github.com/maxitg/setreplace/blob/cdf2644a67f414110d12046e31c434604bfbfec4/README.md#L95)):*
> ```Markdown
> Exploring the hypergraph models of this variety is the primary purpose of this package.
> 
> # Getting Started
> ```

I think it will be better to keep "Getting Started" here on the main page. It's short, and everybody will need to read it to use the package.
___
*[README.md, line 105 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc7eHf4MKyicHnOb66:-MJc7eHf4MKyicHnOb67:b1hf2m0) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/README.md#L105)):*
> ```Markdown
> # Acknowledgements
> 
> In additional to commit authors and reviewers, *Stephen Wolfram* has contributed to the API design of most functions, and *Jeremy Davis* has contributed to the visual style of [`WolframModelPlot`](#wolframmodelplot), [`RulePlot`](#ruleplot-of-wolframmodel) and [`"CausalGraph"`](#causal-graphs).
> ```

The links here are broken.
___
*[README.md, line 132 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc6CoT5ebnrRBkn9ve:-MJc6CoT5ebnrRBkn9vf:b-ey0csr) ([raw file](https://github.com/maxitg/setreplace/blob/cdf2644a67f414110d12046e31c434604bfbfec4/README.md#L132)):*
> ```Markdown
> We have a [Discord server](https://discord.setreplace.org). If you would like to contribute but have questions or don't know where to start, this is the perfect place! In addition to helping new contributors, we discuss feature and research ideas. So, if you are interested, please join!
> 
> # Symbols and Functions
> ```

We should keep a table of contents here. One link per each new page (including on levels further down in the hierarchy).
___
*[Documentation/Contributions.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc7tRh-At4NNwMFrOD:-MJc7tRh-At4NNwMFrOE:bwvm279) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/Contributions.md#L1)):*
> ```Markdown
> # Getting Started
> ```

We should call this file `GettingStarted.md`. It's about how to install the paclet rather than how to contribute. We have a separate file for that (see Contributing section below).
___
*[Documentation/Contributions.md, line 32 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc8cQMDwX3V2GL8IPh:-MJc8cQMDwX3V2GL8IPi:b68jk7g) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/Contributions.md#L32)):*
> ```Markdown
> ## Contributing
> 
> Keep in mind that this is an active research project. While we try to keep the main functionality backward compatible, it might change in the future as we adjust our models and find better ways of analysis. Keep that in mind when building on top of *SetReplace*, and keep track of [git SHAs](UtilityFunctions.md#build-data) as you go.
> ```

This link is broken.
___
*[Documentation/SymbolsAndFunctions/Properties.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcDpKY-G75ZGG1BH97:-MJcDpKY-G75ZGG1BH98:bhfek4v) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/Properties.md#L1)):*
> ```Markdown
> ### Properties
> ```

It would be best to split each of the properties into a separate file (this section is still quite long). Same with options.
___
*[Documentation/SymbolsAndFunctions/Properties.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcJWWYErhVf68Mbrqq:-MJcJWWYErhVf68Mbrqr:biaeg7x) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/Properties.md#L1)):*
> ```Markdown
> ### Properties
> ```

I suggest changing the title to "WolframModelEvolutionObject Properties" to make it more clear what kind of property this refers to.
___
*[Documentation/SymbolsAndFunctions/StepLimiters.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcK5tpBMGmnBsWF-iI:-MJcK5tpBMGmnBsWF-iJ:b1mndxa) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/StepLimiters.md#L1)):*
> ```Markdown
> ### Step Limiters
> ```

The title should be "WolframModel Step Limiters".
___
*[Documentation/SymbolsAndFunctions/StepLimiters.md, line 28 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcD9npEGDbYbqhD_OE:-MJcD9npEGDbYbqhD_OF:bkzcpp0) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/StepLimiters.md#L28)):*
> ```Markdown
> <img src="DocsImages/MaxVerticesFinalStatePlot.png" width="478">
> 
> Note that the final state here is "less symmetric" because its last generation is incomplete (more on that [later](#hypergraphautomorphismgroup)). Such incomplete generations can be automatically trimmed by setting [`"IncludePartialGenerations" -> False`](Properties.md#includepartialgenerations).
> ```

The link in "later" is broken.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcLEnMEnDZTnuHFiCZ:-MJcLEnMEnDZTnuHFiC_:bi0xmhn) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/UtilityFunctions.md#L1)):*
> ```Markdown
> ## Utility Functions
> ```

I think each utility function should go on a separate page as well. We should also have links to each of these functions from the table of contents in the main README.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions.md, line 239 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcLxTA4Zj_1YaUVChR:-MJcLxTA4Zj_1YaUVChS:b68jk7g) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/S [...]

2020-10-15 04:39 UTC, wawo9193 commented
- Broke down properties, options, and utility functions into their own directories of files.
- Changed Step Limiter header to `WolframModel Step Limiters'
- Added the Rule Specification and Automatic Initial State files in /WolframModelAndWolframModelEvolutionObject/...
- Fixed links (really tried to go page by page, line by line, so hoping I didn't miss any)
- Moved images all into /Documentation/Images/...
     - Fixed all corresponding image paths
- Fixed links/images in LocalMultiwaySystem.md
- README.md had the getting started part added to it
- Added a table of contents at the end of WolframModelAndWolframModelEvolutionObject.md with links to "Rule Specification", "Automatic Initial State", "Step Limiters", and all individual properties and options.

TODO: Add full table of contents inside of README.md for all new files added with maybes some direction as to the hierarchy.

@maxitg

2020-10-15 20:08 UTC, maxitg requested changes
I think we are getting closer! I did not look at everything yet but left some comments in the files below. Also, the links and pictures in the contributing guidelines are still broken.

Also, please reply to individual review comments on Reviewable (there is a link in the PR message).

> Reviewed 2 of 164 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466#-:-MJhmom63O9UnJ6IhCTg:bc8k1jl)* status: 2 of 162 files reviewed, 16 unresolved discussions (waiting on @aokellermann, @daneelsan, @maxitg, @taliesinb, and @wawo9193)

___
*[README.md, line 105 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc7eHf4MKyicHnOb66:-MJhoDnL-RGv7rk_GSLx:b-pw6wbv) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/README.md#L105)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The links here are broken.
</blockquote></details>

The links to `WolframModelPlot` and `RulePlot` are still broken.
___
*[README.md, line 132 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc6CoT5ebnrRBkn9ve:-MJhnXED0Ro9h8-EBYF2:b-e34h7l) ([raw file](https://github.com/maxitg/setreplace/blob/cdf2644a67f414110d12046e31c434604bfbfec4/README.md#L132)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

We should keep a table of contents here. One link per each new page (including on levels further down in the hierarchy).
</blockquote></details>

We don't need the `## Table of Contents` title (it's obvious already that it is). Also, it should be vertical (i.e., one link per line), and, as you mentioned, should include *all* pages including the pages for individual properties and options.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md, line 1 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhmLQO0KxznDI0rcov:-MJhmLQO0KxznDI0rcow:b8074xt) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md#L1)):*
> ```Markdown
> ### Build Data
> ```

Do you think we should make this a top-level title, i.e., `# Build Data`? And bump up all the other subsections the corresponding number of levels? @aokellermann?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqh0zBZF4YmGjn6Qi:-MJhqh0zBZF4YmGjn6Qj:bec5iuz) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md#L15)):*
> ```Markdown
> ```
> 
> <img src="../../../Images/ArithmeticModelExpressionsEventsGraph.png" width="478">
> ```

Do you think it would be better to put the images "locally", i.e., to `Images/...` instead of `/Documentation/Images`? Thoughts, @aokellermann?
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 5 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqNLcBFzxQqahRsyn:-MJhqNLcBFzxQqahRsyo:bnmoyjm) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L5)):*
> ```Markdown
> ## Introduction
> 
> This note introduces [local multiway systems](../../Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventSelectionFunction) and examines them in the context of the
> ```

The path to this note has nothing to do with the documentation, so use absolute instead of relative links here, i.e., `/Documentation/...` instead of `../../Documentation/...`.
___
*[Documentation/SymbolsAndFunctions/WolframModel.md, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhp6Da5DJYmFOD-bik:-MJhp6Da5DJYmFOD-bil:b-q3uysq) ([raw file](https://github.com/maxitg/setreplace/blob/1931588ff0b004a37bd6f0e8f15bf77a80a8a315/Documentation/SymbolsAndFunctions/WolframModel.md#L3)):*
> ```Markdown
> ## WolframModel and WolframModelEvolutionObject
> 
> [Rule Specification](#rule-specification) | [Automatic Initial State](#automatic-initial-state) | [Step Limiters](StepLimiters.md) | [Properties](Properties.md) | [Options](#options)
> ```

I think we should keep the navigation bar so that it's easy to jump to other sections.
___
*[Documentation/SymbolsAndFunctions/WolframModel.md, line 185 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcB_vF6bU3T1RpheJh:-MJhpMaiB750IBEJMEcZ:bfskbq) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/WolframModel.md#L185)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Add a table of contents at the end with links to "Rule Specification", "Automatic Initial State", "Step Limiters", and all individual properties and options.
</blockquote></details>

Again, we don't need `## Table of Contents` title. It should be vertical (probably as a bullet list), and we should keep subheadings for individual sections (options, properties, and the first two). Otherwise, it's impossible to tell which one is an option or a property.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 186 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhq3iE69YEKItHPZME:-MJhq3iE69YEKItHPZMF:b-p37fkt) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L186)):*
> ```Markdown
> 
> ## Table of Contents
> ["Rule Specification"](Options/VertexNamingFunction) | ["Automatic Initial State"](Options/IncludePartialGenerations.md) | ["Step Limiters"](Options/IncludeBoundaryEvents.md) | ["EventOrderingFunction"](Options/EventOrderingFunction.md) | ["EventSelectionFunction"](Options/EventSelectionFunction.md) | ["EventDeduplication"](Options/EventDeduplication.md) | ["IncludeBoundaryEvents"](Options/IncludeBoundaryEvents.md) | ["IncludePartialGenerations"](Options/IncludePartialGenerations.md) | [Method](Options/Method.md) | [TimeConstraint](Options/TimeConstraint.md) | ["VertexNamingFunction"](Options/VertexNamingFunction.md) | ["AllEdgesThroughoutEvolution"](Properties/AllEdgesThroughoutEvolution.md) | [Causal Graphs](Properties/CausalGraphs.md) | [Creator And Destroyer Events](Properties/CreatorAndDestroyerEvents.md) | [Edge And Event Generations](Properties/EdgeAndEventGenerations.md) | [ElementCountLists](Properties/ElementCountLists.md) | [Event Counts](Properties/EventCounts.md) | [Events](Properties/Events.md) | [Events And States](Properties/EventsAndStates.md) | [Expression Separations](Properties/ExpressionSeparations.md) | [Final Element Counts](Properties/FinalElementCounts.md) | [Generation Counts](Properties/GenerationCounts.md) | [Plots Of Events](Properties/PlotsOfEvents.md) | [Plots Of States](Properties/PlotsOfStates.md) | [RuleIndices For Events](Properties/RuleIndicesForEvents.md) | [Rules](Properties/Rules.md) | [States](Properties/States.md) | [States As Edge Indices](Properties/StatesAsEdgeIndices.md) | [Termination Reason](Properties/TerminationReason.md) | [Total Element Counts](Properties/TotalElementCounts.md) | [Version](Properties/Version.md) 
> ```

Some links here also go to incorrect places.


<!-- Sent from Reviewable.io -->

2020-10-16 03:29 UTC, wawo9193 reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: 0 of 162 files reviewed, 16 unresolved discussions (waiting on @aokellermann, @daneelsan, @maxitg, @taliesinb, and @wawo9193)

___
*[README.md, line 3 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc5tWM5IAJrmyrEY3u:-MJjKlwlBt6290swdkYS:bajj5yw) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/README.md#L3)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Symbols and Functions should lead to the new page.
</blockquote></details>

Symbols and Functions is now broken up into multiple files, on uncommitted version, I have the vertical table of contents for all symbols and functions - could it go there or is there a certain page it should land on?
___
*[README.md, line 95 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc5y6W1JTu4BZabx1T:-MJjMpa37Os-as_p43Zl:b8e7kq8) ([raw file](https://github.com/maxitg/setreplace/blob/cdf2644a67f414110d12046e31c434604bfbfec4/README.md#L95)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think it will be better to keep "Getting Started" here on the main page. It's short, and everybody will need to read it to use the package.
</blockquote></details>

Done, also on Documentation/GettingStarted.md
___
*[README.md, line 105 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc7eHf4MKyicHnOb66:-MJjNAg39VT5fYZdlsrZ:bb6un1j) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/README.md#L105)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The links to `WolframModelPlot` and `RulePlot` are still broken.
</blockquote></details>

Done
___
*[README.md, line 132 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc6CoT5ebnrRBkn9ve:-MJjMwJv9WLSueUPhQae:bb6un1j) ([raw file](https://github.com/maxitg/setreplace/blob/cdf2644a67f414110d12046e31c434604bfbfec4/README.md#L132)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

We don't need the `## Table of Contents` title (it's obvious already that it is). Also, it should be vertical (i.e., one link per line), and, as you mentioned, should include *all* pages including the pages for individual properties and options.
</blockquote></details>

Done
___
*[Documentation/SymbolsAndFunctions/Properties.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcDpKY-G75ZGG1BH97:-MJjNiCA6uIOFZgbccSg:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/Properties.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It would be best to split each of the properties into a separate file (this section is still quite long). Same with options.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/Properties.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcJWWYErhVf68Mbrqq:-MJjNj8W5D3TFCuXtR11:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/Properties.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I suggest changing the title to "WolframModelEvolutionObject Properties" to make it more clear what kind of property this refers to.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcLEnMEnDZTnuHFiCZ:-MJjNlmb07JzFddmYV_R:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/UtilityFunctions.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think each utility function should go on a separate page as well. We should also have links to each of these functions from the table of contents in the main README.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md, line 1 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhmLQO0KxznDI0rcov:-MJjPpMIC_u_A_852B4m:b2u32zs) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Do you think we should make this a top-level title, i.e., `# Build Data`? And bump up all the other subsections the corresponding number of levels? @aokellermann?
</blockquote></details>

Let me know on this
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqh0zBZF4YmGjn6Qi:-MJjS5Qk1qEJaXkeFy_i:b1ecj72) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Do you think it would be better to put the images "locally", i.e., to `Images/...` instead of `/Documentation/Images`? Thoughts, @aokellermann?
</blockquote></details>

Let me know on this one
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 5 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqNLcBFzxQqahRsyn:-MJjRhQw2pv_7a8tXkOT:bp8ziwa) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L5)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The path to this note has nothing to do with the documentation, so use absolute instead of relative links here, i.e., `/Documentation/...` instead of `../../Documentation/...`.
</blockquote></details>

Not sure on this one, absolute paths seem to work on the README.md since that is in the root, but I tried your example and it broke the link. I agree that it would look a lot better, I will try and look into why it didn't work for me.
___
*[Documentation/Contributions.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc7tRh-At4NNwMFrOD:-MJjNF2K1cS0cLWhAMaF:bb6un1j) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/Contributions.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

We should call this file `GettingStarted.md`. It's about how to install the paclet rather than how to contribute. We have a separate file for that (see Contributing section below).
</blockquote></details>

Done
___
*[Documentation/Contributions.md, line 32 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc8cQMDwX3V2GL8IPh:-MJjNeJv-r-nvf1vu0yY:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/Contributions.md#L32)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This link is broken.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/StepLimiters.md, line 1 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcK5tpBMGmnBsWF-iI:-MJjPv2h-og563zX-vXs:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/StepLimiters.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The title should be "WolframModel Step Limiters".
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/StepLimiters.md, l [...]

2020-10-16 03:42 UTC, wawo9193 commented
Overview:

- Added Symbols and Function TOC in README.md (vertical)
- Adding absolute path on files broke links for me, will need to investigate or advice is appreciated here
- Lots of broken links fixed (Including CONTRIBUTING.md and LocalMultiwaySystem.md)

- Let me know about putting Images in the root for Readme and also about putting vertical TOC in WolframModelAndWolframModelEvolutionObject.md, and if at the top is preferred as well

2020-10-17 07:24 UTC, maxitg requested changes
> Reviewed 2 of 164 files at r3, 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: 3 of 162 files reviewed, 12 unresolved discussions (waiting on @aokellermann, @daneelsan, @maxitg, @taliesinb, and @wawo9193)

___
*[README.md, line 3 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc5tWM5IAJrmyrEY3u:-MJpCzDE5IMtggvWFUpQ:b-upruej) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/README.md#L3)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Symbols and Functions is now broken up into multiple files, on uncommitted version, I have the vertical table of contents for all symbols and functions - could it go there or is there a certain page it should land on?
</blockquote></details>

Yes, it should go to the table of contents, nothing else to do here.
___
*[README.md, line 95 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc5y6W1JTu4BZabx1T:-MJpD9-v8Y0xdK1YmgPy:b-ge9qp2) ([raw file](https://github.com/maxitg/setreplace/blob/cdf2644a67f414110d12046e31c434604bfbfec4/README.md#L95)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Done, also on Documentation/GettingStarted.md
</blockquote></details>

We shouldn't duplicate it, it will inevitably get out of sync then.
___
*[README.md, line 132 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJc6CoT5ebnrRBkn9ve:-MJpDMvx3mASzT_IiIAk:b-ycvafy) ([raw file](https://github.com/maxitg/setreplace/blob/cdf2644a67f414110d12046e31c434604bfbfec4/README.md#L132)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Done
</blockquote></details>

Looks great! But see comments below.
___
*[README.md, line 136 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKueG2Y8MDyRqyPay:-MJpKueG2Y8MDyRqyPaz:b-8a5z0x) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L136)):*
> ```Markdown
> - [SetReplace\*](Documentation/SymbolsAndFunctions/SetReplace*.md)
> - [ToPatternRules](Documentation/SymbolsAndFunctions/ToPatternRules.md)
> - Utility Functions
> ```

Put Utility Functions at the end. Also, I don't think it helps to sort properties and options alphabetically because the names here are not the same as the names of actual properties, so it would not really make it easier to find them.
___
*[README.md, line 137 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKVHOAdURs0VocjRs:-MJpKVHOAdURs0VocjRt:bhbvfez) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L137)):*
> ```Markdown
> - [ToPatternRules](Documentation/SymbolsAndFunctions/ToPatternRules.md)
> - Utility Functions
>   - [BuildData](Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md)
> ```

Add a space.
___
*[README.md, line 146 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKY6o0I30xJIiBOM6:-MJpKY6o0I30xJIiBOM7:b-t6mvcp) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L146)):*
> ```Markdown
> - [WolframModel and WolframModelEvolutionObject](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md)
>   - Properties
>     - ["AllEdgesThroughoutEvolution"](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/AllEdgesThroughoutEvolution.md)
> ```

It should be All Edges throughout Evolution (without quotes and with spaces).
___
*[README.md, line 150 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKeYC9vzYNhfVvu5v:-MJpKeYD5bj2TiGyqwaC:bre8ul9) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L150)):*
> ```Markdown
>     - [Creator And Destroyer Events](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CreatorAndDestroyerEvents.md)
>     - [Edge And Event Generations](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EdgeAndEventGenerations.md)
>     - [ElementCountLists](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/ElementCountLists.md)
> ```

Add spaces.
___
*[README.md, line 159 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKk8l44cVavaaqDvM:-MJpKk8l44cVavaaqDvN:b3c3i0v) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L159)):*
> ```Markdown
>     - [Plots Of Events](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/PlotsOfEvents.md)
>     - [Plots Of States](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/PlotsOfStates.md)
>     - [RuleIndices For Events](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/RuleIndicesForEvents.md)
> ```

Add a space between Rule and Indices.
___
*[README.md, line 173 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpLnxg9t8iyEK8mGEL:-MJpLnxg9t8iyEK8mGEM:bpk5652) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L173)):*
> ```Markdown
>     - ["EventSelectionFunction"](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventSelectionFunction.md)
>     - ["EventDeduplication"](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventDeduplication.md)
>     - ["IncludeBoundaryEvents"](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/IncludeBoundaryEvents.md)
> ```

This one and the one below are duplicates. But otherwise, I agree it's better to put `Method` and `TimeConstraint` at the end.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md, line 1 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhmLQO0KxznDI0rcov:-MJpNWsm-Db1YhjiSf4W:b8hjwjo) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md#L1)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Let me know on this
</blockquote></details>

I played with a few different heading styles, and I think the best approach would be to do something like this:
```md
###### [Symbols and Functions](/README.md#symbols-and-functions) > [WolframModel and WolframModelEvolutionObject](../WolframModelAndWolframModelEvolutionObject.md) > [Properties](../WolframModelAndWolframModelEvolutionObject.md#properties) >

# States as Edge Indices
```

or, for this case:
```md
###### [Symbols and Functions](/README.md#symbols-and-functions) > Utility Functions >

# Build Data
```
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqh0zBZF4YmGjn6Qi:-MJpI7nV7E2OPZYNoXNG:b-29f7ek) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md#L15)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Let me know on this one
</blockquote></details>

Let's not overcomplicate things, and keep them all in `/Documentation/Images` as you are doing now. But definitely use the absolute path in this case.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 5 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqNLcBFzxQqahRsyn:-MJpIpZLAxrd_9Jh8cyJ:b-bdf7uq) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L5)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Not sure on this [...]

2020-10-17 12:55 UTC, taliesinb reviewed
> Reviewed 157 of 164 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: all files reviewed, 12 unresolved discussions (waiting on @aokellermann, @daneelsan, and @wawo9193)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md, line 1 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhmLQO0KxznDI0rcov:-MJqb-RCAwwHVasD2EKM:biqhnxl) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I played with a few different heading styles, and I think the best approach would be to do something like this:
```md
###### [Symbols and Functions](/README.md#symbols-and-functions) > [WolframModel and WolframModelEvolutionObject](../WolframModelAndWolframModelEvolutionObject.md) > [Properties](../WolframModelAndWolframModelEvolutionObject.md#properties) >

# States as Edge Indices
```

or, for this case:
```md
###### [Symbols and Functions](/README.md#symbols-and-functions) > Utility Functions >

# Build Data
```
</blockquote></details>

I vote for Max's suggestion.


<!-- Sent from Reviewable.io -->

2020-10-19 03:10 UTC, wawo9193 reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: 115 of 158 files reviewed, 12 unresolved discussions (waiting on @aokellermann, @daneelsan, @maxitg, @taliesinb, and @wawo9193)

___
*[README.md, line 136 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKueG2Y8MDyRqyPay:-MJynuvlAefaCBnSB6GB:bgsbxei) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L136)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Put Utility Functions at the end. Also, I don't think it helps to sort properties and options alphabetically because the names here are not the same as the names of actual properties, so it would not really make it easier to find them.
</blockquote></details>

Utility functions added to end of README.md TOC. Is there a preference on the order? I just kind of went from top to bottom on my IDE and it had the files sorted, let me know and I can adjust
___
*[README.md, line 137 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKVHOAdURs0VocjRs:-MJyoElaEldDr2zoKzXU:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L137)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Add a space.
</blockquote></details>

Done.
___
*[README.md, line 146 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKY6o0I30xJIiBOM6:-MJyoG3u5ALbMMVfT50p:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L146)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It should be All Edges throughout Evolution (without quotes and with spaces).
</blockquote></details>

Done.
___
*[README.md, line 150 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKeYC9vzYNhfVvu5v:-MJyoHF4BSrRjqI0UcSS:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L150)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Add spaces.
</blockquote></details>

Done.
___
*[README.md, line 159 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKk8l44cVavaaqDvM:-MJyoICG4FxkisrVrPjd:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L159)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Add a space between Rule and Indices.
</blockquote></details>

Done.
___
*[README.md, line 173 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpLnxg9t8iyEK8mGEL:-MJyoJOuAvR5ZGIWAkRF:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L173)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This one and the one below are duplicates. But otherwise, I agree it's better to put `Method` and `TimeConstraint` at the end.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md, line 1 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhmLQO0KxznDI0rcov:-MJyoSL64eNG9mF31aol:b-o2emj4) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md#L1)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

I vote for Max's suggestion.
</blockquote></details>

Added and anything in that nav header going to a properties or options link will go to the properties/options header (TOC) in the WolframModelAndWolframModelEvolutionObject.md
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqh0zBZF4YmGjn6Qi:-MJypMfR8RNYNSbbAszL:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Let's not overcomplicate things, and keep them all in `/Documentation/Images` as you are doing now. But definitely use the absolute path in this case.
</blockquote></details>

Done.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 5 at r3](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhqNLcBFzxQqahRsyn:-MJypNmw2HAhDG7YLjte:b-gjauaq) ([raw file](https://github.com/maxitg/setreplace/blob/dad578133dd610ae9bfa7139732754be5416f875/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L5)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This is strange. It does work for me. That is, clicking the first link [here](https://github.com/wawo9193/SetReplace/blob/master/Research/LocalMultiwaySystem/LocalMultiwaySystem.md) goes to [event selection functions](https://github.com/wawo9193/SetReplace/blob/master/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventSelectionFunction.md) as expected.
</blockquote></details>

So I tried the one you suggested and it did work for me, for some reason VSCode only works with the relative links. I changed everything I could find to absolute.
___
*[Documentation/SymbolsAndFunctions/WolframModel.md, line 3 at r1](https://reviewable.io/reviews/maxitg/setreplace/466#-MJhp6Da5DJYmFOD-bik:-MJyok4C2XMj9Ythjb1P:bp0jl82) ([raw file](https://github.com/maxitg/setreplace/blob/1931588ff0b004a37bd6f0e8f15bf77a80a8a315/Documentation/SymbolsAndFunctions/WolframModel.md#L3)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This navigation bar is way too large, and it does not distinguish between properties and options. I think we should keep the original navigation bar here:
```md
[Rule Specification](#rule-specification) | [Automatic Initial State](#automatic-initial-state) | [Step Limiters](#step-limiters) | [Properties](#properties) | [Options](#options)
```
and have subsections for properties and options with vertical lists of links (TOCs) in each of them.

Also, now that I think about it, the only way we can make it consistent is to include "Rule Specification", "Automatic Initial State" and "Step Limiters" in this file as well as subsections. Otherwise, different buttons in the navigation bar will work differently which might not be user-friendly (sorry for changing my mind about this, I did not think it through the first time). Alternatively, we could add subsections with a single link to other files, but I think that would look weird.
</blockquote></details>

Hopefully I understood correctly, if not let me know. i took out the big navigation bar, consolidated "Rule Specification", "Automatic Initial State", and "Step Limiters" markdown files into WolframModelAndWolframModelEvolutionObject.md while also creating a properties and options TOC with vertical links at the bottom.
___
*[Documentation/SymbolsAndFunctions/WolframModel.md, line 185 at r2](https://reviewable.io/reviews/maxitg/setreplace/466#-MJcB_vF6bU3T1RpheJh:-MJypC3KDaD2U7ZaCM0j:by1zsfw) ([raw file](https://github.com/maxitg/setreplace/blob/1fa21b6faaf14f08a774c3a733cb33c62e6ebc37/Documentation/SymbolsAndFunctions/WolframModel.md#L185)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

We should have a navigation bar with anchor links at the top (see above), and the table of contents with links to other files here (for properties and options, in different subsections).
</blockquote></details>

Let me know, I commented on the one above about what was done for this. 


<!-- Sent from Reviewable.io -->

2020-10-19 03:16 UTC, wawo9193 commented
Recap on latest commit:
* Consolidated "Automatic Initial State", "Rule Specification", and "Step Limiters" into WolframModelAndWolframModelEvolutionObject.md with a properties and options vertical TOC at the bottom.
* Corrected links in README.md with spaces in name and other small errors.
* Changed links to absolute, they seem to not work on my IDE but work in GitHub, let me know if there are more that are preferred to be switched from relative to absolute.

Wondering about reducing the header level of subsections that were pulled out into individual files, e.g. WolframModelPlot.md was a subsection and the header itself was '###' but changed to a top level header level '#', should I increase the header size on the subheaders for that file to match the top level changing?

2020-10-20 04:08 UTC, maxitg requested changes
Yes, we can increase the subsections by the same number of levels. I.e., subsections should always be exactly one level more than their enclosing section.

And thank *you* for contributing!

> Reviewed 112 of 164 files at r3, 47 of 47 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466#-:-MK2mwON3QbabBTZ9h9o:b-ru14)* status: all files reviewed, 37 unresolved discussions (waiting on @aokellermann, @daneelsan, and @wawo9193)

___
*[README.md, line 136 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKueG2Y8MDyRqyPay:-MK2nlCc0I7xholKrbeu:bbny11h) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L136)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Utility functions added to end of README.md TOC. Is there a preference on the order? I just kind of went from top to bottom on my IDE and it had the files sorted, let me know and I can adjust
</blockquote></details>

Please use the same order as in the original. The order is designed so that it can be read sequentially.
___
*[README.md, line 146 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKY6o0I30xJIiBOM6:-MK2nyXG2NDoF_j4ukUS:byp7oyr) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L146)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please use the original capitalization. I.e., "All Edges throughout Evolution" (lowercase "throughout"). These are capitalized the same way as, e.g., movie names. Same for other properties.
___
*[README.md, line 136 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK2nfA66_3d_68fgCPV:-MK2nfA66_3d_68fgCPW:bw10r2c) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/README.md#L136)):*
> ```Markdown
> - [SetReplace\*](Documentation/SymbolsAndFunctions/SetReplace*.md)
> - [ToPatternRules](Documentation/SymbolsAndFunctions/ToPatternRules.md)
>   - Properties
> ```

These are the properties of `WolframModel`, not of `ToPatternRules`.
___
*[README.md, line 171 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK35tTP77JTTKsZyaA8:-MK35tTP77JTTKsZyaA9:bwxzim0) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/README.md#L171)):*
> ```Markdown
> - Utility Functions
>   - [Build Data](Documentation/SymbolsAndFunctions/UtilityFunctions/BuildData.md)
>   - [Generalized Grid Graph](Documentation/SymbolsAndFunctions/UtilityFunctions/GeneralizedGridGraph.md)
> ```

Except for "Build Data", these are function names, so there should not be any spaces.
___
*[.github/CONTRIBUTING.md, line 91 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK36ncC7ko1iSQpQHHo:-MK36ncC7ko1iSQpQHHp:b-rzpyh6) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L91)):*
> ```Markdown
> If sharing variables among multiple tests, use [`With`](https://reference.wolfram.com/language/ref/With.html) instead of [`Module`](https://reference.wolfram.com/language/ref/Module.html) or global assignment, because otherwise, variables will not appear resolved in the command line error message if the test fails (which makes it harder to weed whack). Also, try to avoid large inputs and outputs for the tests, if at all possible (by, for example, replacing `VerificationTest[large1[], large2[]]` with `VerificationTest[large1[] === large2[]]`).
> 
> You should also modify the [README](../README.md) or the corresponding files in the Documentation directory if you are implementing new functionality, or causing any outputs there to change.
> ```

Keep the link absolute.
___
*[.github/CONTRIBUTING.md, line 339 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK37-n33mMR0J79N8o3:-MK37-n33mMR0J79N8o4:b-axhsfk) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L339)):*
> ```Markdown
> 
> Some things to note are:
> * Large [README](../README.md) sections should include navigation bars in the beginning.
> ```

Keep the absolute link.
___
*[.github/CONTRIBUTING.md, line 340 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK373Uh3opKEaAMzUuy:-MK373Uh3opKEaAMzUuz:brhumzt) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L340)):*
> ```Markdown
> Some things to note are:
> * Large [README](../README.md) sections should include navigation bars in the beginning.
> * All references to functions should be links, either to [the Wolfram Language documentation](https://reference.wolfram.com/language/) or to the corresponding section in [README](../README.md).
> ```

Same here.
___
*[.github/CONTRIBUTING.md, line 414 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK377141qml5vU0qzXr:-MK377141qml5vU0qzXs:bu978rx) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L414)):*
> ```Markdown
> We are using GitHub-flavored Markdown for documentation and research notes.
> 
> Images (e.g., of output cells) should be made by selecting the relevant cells in the Front End, copying them as bitmaps, and saving them as .png files to [Documentation/Images](../Documentation/Images) (in the documentation) or to the Images directory of the corresponding research note. They should then be inserted using the code similar to this:
> ```

Make the link absolute.
___
*[.github/CONTRIBUTING.md, line 417 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK37Lf61em6SqrzSFKC:-MK37Lf61em6SqrzSFKD:bmx9mt3) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L417)):*
> ```Markdown
> 
>   ```html
>   <img src="Documentation/Images/image.png" width="xxx">
> ```

`... src="/Documentation/Images/image.png" ...`
___
*[Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK34ea01sObntucW28k:-MK34ea01sObntucW28l:b-l3fnwn) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md#L1)):*
> ```Markdown
> ###### [Symbols and Functions](/README.md#symbols-and-functions) > [WolframModel and WolframModelEvolutionObject](../WolframModelAndWolframModelEvolutionObject.md) >
> ```

`RulePlot` is not a part of "WolframModel and WolframModelEvolutionObject".
___
*[Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md, line 12 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK394j94bryjpJqL56s:-MK394j94bryjpJqL56t:brgo6tc) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md#L12)):*
> ```Markdown
> ```
> 
> <img src="../Images/RulePlot.png" width="429">
> ```

Use absolute links.
___
*[Documentation/SymbolsAndFunctions/SetReplace*.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK2sQ0v-59O_z_gal2s:-MK2sQ0v-59O_z_gal2t:bidyew9) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/SetReplace*.md#L1)):*
> ```Markdown
> ###### [Symbols and Functions](/README.md#symbols-and-functions) > [WolframModel and WolframModelEvolutionObject](../WolframModelAndWolframModelEvolutionObject.md) >
> ```

`SetReplace*` functions are not a part of `WolframModel and WolframModelEvolutionObject`.
___
*[Documentation/SymbolsAndFunctions/ToPatternRules.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK34UEg7ie5K0c_AdRe:-MK34UEh-CJ_rqCSMmlu:b-qywp9s) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFuncti [...]

2020-10-23 19:41 UTC, maxitg requested changes
We are getting very close! There are just a few broken links and other issues remaining, but it's looking great otherwise! Also, don't forget to rebase to incorporate the changes introduced after this PR was opened (e.g., `IndexHypergraph` utility function).

> Reviewed 21 of 21 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466#-:-MKLxmp956QAnixi0bGs:bcg9bab)* status: all files reviewed, 8 unresolved discussions (waiting on @aokellermann, @daneelsan, and @wawo9193)

___
*[.github/CONTRIBUTING.md, line 91 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK36ncC7ko1iSQpQHHo:-MKLtNXn5jA7b-DpleIH:bk3zo02) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L91)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Keep the link absolute.
</blockquote></details>

This is not an absolute link. Absolute links always start with `/`. The link you are using is equivalent to `./README.md` and is therefore broken. The same applies to other links throughout this document.
___
*[Documentation/SymbolsAndFunctions/ToPatternRules.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK34UEg7ie5K0c_AdRe:-MKLuoPW8zAPir7VyFh3:b-fjgie0) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/ToPatternRules.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`ToPatternRules` is not a part of "WolframModel and WolframModelEvolutionObject"
</blockquote></details>

Remove the trailing space after `>`.
___
*[Documentation/SymbolsAndFunctions/WolframModelPlot.md, line 59 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK33dje3uIMyyM4AxL-:-MKLv3tqEAqAcBaKW-V1:b8hwl18) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelPlot.md#L59)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The links to `"FinalStatePlot"` and `"EventsStatesPlotsList"` are broken.
</blockquote></details>

Still broken.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 325 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK2zzp9EjeUx_jJx432:-MKLwD0n0SBL-SvhkagW:bmfb08l) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L325)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Check the comments from the main readme file about the ordering and capitalization.
</blockquote></details>

Change the ordering as well (so that it's the same as in the main README).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 5 at r6](https://reviewable.io/reviews/maxitg/setreplace/466#-MKLvtLk9oJm8aFcWTc8:-MKLvtLk9oJm8aFcWTc9:b-g8bte2) ([raw file](https://github.com/maxitg/setreplace/blob/ed636afee5d537b48a1ce85c5c462ecaa1146d5e/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L5)):*
> ```Markdown
> # WolframModel and WolframModelEvolutionObject
> 
> [Rule Specification](#rule-specification) | [Automatic Initial State](#automatic-initial-state) | [Step Limiters](#wolframmodel-step-limiters) | [Properties](#properties) | [Options](#options)
> ```

The link to "Step Limiters" is now broken after renaming.


<!-- Sent from Reviewable.io -->

2020-10-24 23:40 UTC, wawo9193 commented
Completed the changes mentioned @maxitg 
* rebased and added IndexHypergraph.md and link to README TOC
* reorganized README utility functions TOC to match original order

first time contributing so I've never used `git rebase` before, I think I did it correctly.

I will go through reviewable and reply to comments soon

2020-10-25 03:27 UTC, maxitg requested changes
Rebase looks good to me. Some changes were missed (see comments below), but it was a very complicated rebase, so great job figuring out how to do it!

> Reviewed 49 of 49 files at r7.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466#-:-MKSmHglEQTU0G2fQA0S:b-johzn5)* status: all files reviewed, 11 unresolved discussions (waiting on @aokellermann, @daneelsan, and @wawo9193)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/IndexHypergraph.md, line 17 at r7](https://reviewable.io/reviews/maxitg/setreplace/466#-MKSaJmQA86g8DjT241y:-MKSaJmQA86g8DjT241z:b24dljl) ([raw file](https://github.com/maxitg/setreplace/blob/e61f2f37397e0de116070ff61d7bc664b0a5d19b/Documentation/SymbolsAndFunctions/UtilityFunctions/IndexHypergraph.md#L17)):*
> ```Markdown
> In[]:= IndexHypergraph[{{x, y, z}, {w, y}, {z, {x}, {{y}}}}, -10]
> Out[]= {{-9, -8, -7}, {-10, -8}, {-7, -6, -5}}
> ```
> ```

Add an empty line at the end of the file.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/Subhypergraph.md, line 5 at r7](https://reviewable.io/reviews/maxitg/setreplace/466#-MKSj_s_0sU9HYECKTBI:-MKSj_s_0sU9HYECKTBJ:b-rdslzd) ([raw file](https://github.com/maxitg/setreplace/blob/e61f2f37397e0de116070ff61d7bc664b0a5d19b/Documentation/SymbolsAndFunctions/UtilityFunctions/Subhypergraph.md#L5)):*
> ```Markdown
> # Subhypergraph
> 
> **`Subhypergraph`** is a small utility function that selects hyperedges that only contain vertices from the requested list.
> ```

Replace the "." at the end with ":". This was changed in 26047a9 and got lost in the rebase.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/Subhypergraph.md, line 11 at r7](https://reviewable.io/reviews/maxitg/setreplace/466#-MKSjpKG2ZZ5KvDLE1ru:-MKSjpKG2ZZ5KvDLE1rv:b-7gp2p6) ([raw file](https://github.com/maxitg/setreplace/blob/e61f2f37397e0de116070ff61d7bc664b0a5d19b/Documentation/SymbolsAndFunctions/UtilityFunctions/Subhypergraph.md#L11)):*
> ```Markdown
> Out[]= {{2, 3, 3}, {2, 3, 4}}
> ```
> **`WeakSubhypergraph`** is the weak version of the previous function, where hyperedges are selected if they contain any vertex from the requested list.
> ```

Similarly, change "." to ":".
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 207 at r7](https://reviewable.io/reviews/maxitg/setreplace/466#-MKSf3rV1wKv5C5uwGTH:-MKSf3rV1wKv5C5uwGTI:b-vfv2vy) ([raw file](https://github.com/maxitg/setreplace/blob/e61f2f37397e0de116070ff61d7bc664b0a5d19b/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L207)):*
> ```Markdown
> 
> Note, in this case, we will automatically get a multiway system.
> In fact, the [match-all](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventSelectionFunction.md) version of it.
> ```

This has accidentally reverted a change from #474. These two lines should be replaced with "`Note, in this case, we will automatically get a multiway system&mdash;in fact, the
[match-all](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventSelectionFunction.md) version of it.`"
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 242 at r7](https://reviewable.io/reviews/maxitg/setreplace/466#-MKSgdlh5YDVKc9bpZ5E:-MKSgdlh5YDVKc9bpZ5F:b-xhfl0d) ([raw file](https://github.com/maxitg/setreplace/blob/e61f2f37397e0de116070ff61d7bc664b0a5d19b/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L242)):*
> ```Markdown
> now, `{1, 2}` has been deleted, and the second rule requires both `{1, 2}` and `{2, 3}` as inputs.
> In other words, `{1, 2}` and `{2, 3}` are **timelike** expressions, and our singleway
> [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) only matches **spacelike** expressions.
> ```

Restore the changes here:
```markdown
now, `{1, 2}` has been deleted and the second rule requires both `{1, 2}` and `{2, 3}` as inputs.
In other words, `{1, 2}` and `{2, 3}` are *timelike* expressions, and our singleway
[`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) only matches *spacelike* expressions.
```

Note, when resolving conflicts, it's important to make sure ***both*** changes are preserved.
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 280 at r7](https://reviewable.io/reviews/maxitg/setreplace/466#-MKShITZ5Iz-9WoIJDOF:-MKShITZ5Iz-9WoIJDOG:b-yzz283) ([raw file](https://github.com/maxitg/setreplace/blob/e61f2f37397e0de116070ff61d7bc664b0a5d19b/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L280)):*
> ```Markdown
> Note in the above there are two possibilities to match `{{1, 2}}`, which are incompatible according to the ordinary
> [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) and can only be achieved one-at-a-time with
> different choices of the [`"EventOrderingFunction"`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventOrderingFunction.md).
> ```

Again, changes from `master` were lost. Should be:
```markdown
Note in the above there are two possibilities to match `{{1, 2}}`, which are incompatible according to the ordinary
[`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) and can only be achieved one at a time with
different choices of the [`"EventOrderingFunction"`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Options/EventOrderingFunction.md).
```
___
*[Research/LocalMultiwaySystem/LocalMultiwaySystem.md, line 284 at r7](https://reviewable.io/reviews/maxitg/setreplace/466#-MKShtVH7-ud4IrweIMR:-MKShtVH7-ud4IrweIMS:bh10vc5) ([raw file](https://github.com/maxitg/setreplace/blob/e61f2f37397e0de116070ff61d7bc664b0a5d19b/Research/LocalMultiwaySystem/LocalMultiwaySystem.md#L284)):*
> ```Markdown
> 
> Further note the obvious feature of the match-all system that it produces expressions and events that would occur in
> neither the singleway [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) nor the global
> ```

Same issue here. Should be:
```markdown
Further note the obvious feature of the match-all system: it produces expressions and events that would occur in neither
the singleway [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) nor the global
```


<!-- Sent from Reviewable.io -->

2020-10-26 23:25 UTC, maxitg reviewed
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: all files reviewed, 4 unresolved discussions (waiting on @aokellermann, @daneelsan, and @wawo9193)



<!-- Sent from Reviewable.io -->

2020-10-27 00:13 UTC, wawo9193 reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: all files reviewed, 4 unresolved discussions (waiting on @aokellermann, @daneelsan, and @maxitg)

___
*[README.md, line 136 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKueG2Y8MDyRqyPay:-MKGBluU5XJUsWnv6sgn:b-2u6s80) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L136)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Please use the same order as in the original. The order is designed so that it can be read sequentially.
</blockquote></details>

All restored to previous order, except the method/time constraint you mentioned earlier being at the bottom.
___
*[README.md, line 146 at r4](https://reviewable.io/reviews/maxitg/setreplace/466#-MJpKY6o0I30xJIiBOM6:-MKGNtbTCrGj2exfSuCB:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/1904e9bc7f2a424e22cfec92fca64ddcb93c4bdf/README.md#L146)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Please use the original capitalization. I.e., "All Edges throughout Evolution" (lowercase "throughout"). These are capitalized the same way as, e.g., movie names. Same for other properties.
</blockquote></details>

Completed.
___
*[README.md, line 171 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK35tTP77JTTKsZyaA8:-MKGNvTyDQJny8ncbVC1:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/README.md#L171)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Except for "Build Data", these are function names, so there should not be any spaces.
</blockquote></details>

Completed.
___
*[.github/CONTRIBUTING.md, line 91 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK36ncC7ko1iSQpQHHo:-MKGO6i1EgACZ0eWAMRG:bn8oho) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L91)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Keep the link absolute.
</blockquote></details>

changed to /README.md
___
*[.github/CONTRIBUTING.md, line 339 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK37-n33mMR0J79N8o3:-MKGOAf95_Q5a5cE1Gmb:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L339)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Keep the absolute link.
</blockquote></details>

Completed.
___
*[.github/CONTRIBUTING.md, line 340 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK373Uh3opKEaAMzUuy:-MKGOCpSCS4dxnOteBs6:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L340)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Completed.
___
*[.github/CONTRIBUTING.md, line 414 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK377141qml5vU0qzXr:-MKGOEA82l62y0COcRt9:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L414)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Make the link absolute.
</blockquote></details>

Completed.
___
*[.github/CONTRIBUTING.md, line 417 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK37Lf61em6SqrzSFKC:-MKGOEpx7X-B_dUwRId3:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L417)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`... src="/Documentation/Images/image.png" ...`
</blockquote></details>

Completed.
___
*[Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK34ea01sObntucW28k:-MKGOFub52_P7pTY2Eob:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`RulePlot` is not a part of "WolframModel and WolframModelEvolutionObject".
</blockquote></details>

Completed.
___
*[Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md, line 12 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK394j94bryjpJqL56s:-MKGOGma4_xGxQPdoUqh:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/RulePlotOfWolframModel.md#L12)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use absolute links.
</blockquote></details>

Completed.
___
*[Documentation/SymbolsAndFunctions/SetReplace*.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK2sQ0v-59O_z_gal2s:-MKGOHyZ8pZnQASkk-r3:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/SetReplace*.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`SetReplace*` functions are not a part of `WolframModel and WolframModelEvolutionObject`.
</blockquote></details>

Completed.
___
*[Documentation/SymbolsAndFunctions/ToPatternRules.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK34UEg7ie5K0c_AdRe:-MKGOIrUDcGcnDJDdwS7:bss4a2b) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/ToPatternRules.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`ToPatternRules` is not a part of "WolframModel and WolframModelEvolutionObject"
</blockquote></details>

Removed.
___
*[Documentation/SymbolsAndFunctions/WolframModelPlot.md, line 13 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK39INqEKaRntcJQuWJ:-MKGOPYC1dMUSer8g1j4:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelPlot.md#L13)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use absolute paths.
</blockquote></details>

Completed.
___
*[Documentation/SymbolsAndFunctions/WolframModelPlot.md, line 59 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK33dje3uIMyyM4AxL-:-MKGOQdt6c3Xtavyyyoe:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelPlot.md#L59)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The links to `"FinalStatePlot"` and `"EventsStatesPlotsList"` are broken.
</blockquote></details>

Completed.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 1 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK34FeG3HyUeTOzKWo8:-MKGOSVd94uAuuoOVIm-:bgw8bs) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Put the header with the link to "Symbol and Functions" here like on other pages.
</blockquote></details>

Completed.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 198 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK2t4ey5N37l1XWtRU0:-MKbOU4q8D2flk8vTvxe:b-896fix) ([raw file](https:// [...]

2020-10-27 00:15 UTC, wawo9193 reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: all files reviewed, 4 unresolved discussions (waiting on @aokellermann, @daneelsan, and @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelPlot.md, line 59 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK33dje3uIMyyM4AxL-:-MKbP5ZU7F00y3sjEjCm:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelPlot.md#L59)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Completed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-27 00:24 UTC, maxitg requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: all files reviewed, 4 unresolved discussions (waiting on @aokellermann, @daneelsan, and @wawo9193)

___
*[.github/CONTRIBUTING.md, line 339 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK37-n33mMR0J79N8o3:-MKbPKmQ2rY3Ebl-E9aM:b7wvfwq) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L339)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Completed.
</blockquote></details>

The absolute link should start with `/`. This link is broken.
___
*[.github/CONTRIBUTING.md, line 340 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK373Uh3opKEaAMzUuy:-MKbPSAp696iJ0f2oGyC:brhumzt) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L340)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Completed.
</blockquote></details>

Same here.
___
*[Documentation/SymbolsAndFunctions/WolframModelPlot.md, line 59 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK33dje3uIMyyM4AxL-:-MKbPp_rAJKUE7lqBl9j:b-fxxvuf) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelPlot.md#L59)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still broken. Check [here](https://github.com/wawo9193/SetReplace/blob/master/Documentation/SymbolsAndFunctions/WolframModelPlot.md). Delete `/` at the beginning of the links to make them relative.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 198 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK2t4ey5N37l1XWtRU0:-MKbQPU39YqrjNAP_Ywe:b417ekm) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L198)):*
<details><summary><i>Previously, wawo9193 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please open [on GitHub](https://github.com/wawo9193/SetReplace/blob/master/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) to verify. The images are no longer in `READMEImages`.


<!-- Sent from Reviewable.io -->

2020-10-27 01:00 UTC, wawo9193 reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: 156 of 159 files reviewed, 4 unresolved discussions (waiting on @aokellermann, @daneelsan, and @maxitg)

___
*[.github/CONTRIBUTING.md, line 339 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK37-n33mMR0J79N8o3:-MKbZ7kXEGz1re4IMMwh:btvjsfh) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L339)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The absolute link should start with `/`. This link is broken.
</blockquote></details>

Looks like this one maybe got lost in the rebase. Fixed it now.
___
*[.github/CONTRIBUTING.md, line 340 at r5](https://reviewable.io/reviews/maxitg/setreplace/466#-MK373Uh3opKEaAMzUuy:-MKbZFMB8yiUOfyzjIZ2:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/2e44839b92d9cf612da342a982cda843463c47ed/.github/CONTRIBUTING.md#L340)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-27 02:05 UTC, maxitg requested changes
I just read through all of it again, and except for the last few broken links, it's looking great! After fixing those, we can merge it!

> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466#-:-MKb_I8U9M-JzhaafXIg:b5v1n80)* status: all files reviewed, 5 unresolved discussions (waiting on @aokellermann, @daneelsan, and @wawo9193)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TerminationReason.md, line 5 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbglns0ProrixQqFL0:-MKbglns0ProrixQqFL1:b4ykl5k) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TerminationReason.md#L5)):*
> ```Markdown
> # Termination Reason
> 
> **`"TerminationReason"`** shows why the evaluation of the model was stopped. It's particularly useful if multiple [stopping conditions](../WolframModelAndWolframModelEvolutionObject.md#wolframmodel-step-limiters) are specified.
> ```

Change `#wolframmodel-step-limiters` to `#step-limiters` in the link.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 30 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbd7a_CkyGDwNkSr6u:-MKbd7a_CkyGDwNkSr6v:b-i8gann) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L30)):*
> ```Markdown
> * The rule is specified in the "anonymous" form ([`ToPatternRules`](../ToPatternRules.md) is done implicitly).
> * The number of steps here is the number of generations, which is equivalent to steps of [`SetReplaceAll`](../SetReplace*.md). Here each edge can have at most 10 generations of predecessors.
> * The output is not a final state, but a **`WolframModelEvolutionObject`** containing the entire evolution (similar to [`SetReplaceList`](../SetReplace*.md) but with additional information about the relationships between edges and the events that produced them. From the information field on that object, one can see that the evolution was done for 10 generations (i.e., the evolution did not terminate early), and 109 replacements (aka events) were made in total. More properties can be computed from an evolution object.
> ```

The word "properties" should link to `#properties` like in the previous one-page README.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 87 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbdjrp90c1kZ0S37KZ:-MKbdjrp90c1kZ0S37K_:bf5feok) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L87)):*
> ```Markdown
> * `"Version"` is the data format of the evolution object. This description is for version 2, which is the first version to support multiway systems. Version 1 does not have the `"Version"` key. The objects of older versions are automatically migrated when they are evaluated.
> * `"Rules"` is an exact copy of the corresponding `WolframModel` argument.
> * `"MaxCompleteGenerations"` shows the largest generation in which no matches are possible that only involve expressions of this or earlier generations. In this particular case, it is the same as the largest generation of any edge, but it might be different if a more elaborate [step specification](#wolframmodel-step-limiters) is used.
> ```

The link to "step specification" is broken, change `#wolframmodel-step-limiters` -> `#step-limiters`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 89 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbe29zDJHHmGe_3uwJ:-MKbe29zDJHHmGe_3uwK:b-xgigsj) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L89)):*
> ```Markdown
> * `"MaxCompleteGenerations"` shows the largest generation in which no matches are possible that only involve expressions of this or earlier generations. In this particular case, it is the same as the largest generation of any edge, but it might be different if a more elaborate [step specification](#wolframmodel-step-limiters) is used.
> * `"TerminationReason"` shows the reason evaluation was stopped. See the [`"TerminationReason"`](Properties/TerminationReason.md) property for more details.
> * `"EventRuleIDs"` shows which rule was used for each event. It's rather boring in this particular case, as this example only has one rule. See [Rule Indices for Events](Properties/RuleIndicesForEvents.md) for a more interesting case. The first value, `0`, corresponds to the initial event, which is included in the evolution object but is omitted [by default](Options/IncludeBoundaryEvents.md) when computing properties.
> ```

"properties" at the end should link to `#properties`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 102 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbeE_98-Z3as1LkIL1:-MKbeE_98-Z3as1LkIL2:bhmxhfh) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L102)):*
> ```Markdown
> ```
> 
> Properties section describes and gives examples for each available property. The full list of them can also be obtained with the `"Properties"` property:
> ```

"Properties section" should link to `#properties`.


<!-- Sent from Reviewable.io -->

2020-10-27 04:19 UTC, wawo9193 reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466)* status: 157 of 159 files reviewed, 5 unresolved discussions (waiting on @aokellermann, @daneelsan, and @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TerminationReason.md, line 5 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbglns0ProrixQqFL0:-MKcGy7i658di9HbQVbT:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TerminationReason.md#L5)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Change `#wolframmodel-step-limiters` to `#step-limiters` in the link.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 30 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbd7a_CkyGDwNkSr6u:-MKcGujDC0jhGYqHxciM:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L30)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The word "properties" should link to `#properties` like in the previous one-page README.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 87 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbdjrp90c1kZ0S37KZ:-MKcGw7b4kod-1zrArHi:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L87)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The link to "step specification" is broken, change `#wolframmodel-step-limiters` -> `#step-limiters`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 89 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbe29zDJHHmGe_3uwJ:-MKcGwtbEZ68NiYygGMF:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L89)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

"properties" at the end should link to `#properties`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 102 at r9](https://reviewable.io/reviews/maxitg/setreplace/466#-MKbeE_98-Z3as1LkIL1:-MKcGxaz9Um2-k65JSW_:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9eedab94e4b61e904d87eb11af6ff7fd318791d1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L102)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

"Properties section" should link to `#properties`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-27 04:27 UTC, maxitg approved these changes
Awesome! Thanks a lot for contributing! I'm going to merge now :rocket:

> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/466#-:-MKcIeQgAIk1zigez8Dt:b-snrh18)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aokellermann and @daneelsan)



<!-- Sent from Reviewable.io -->

2020-10-27 04:44 UTC, merged