Features Extractor (on Causal Graphs)
maxitg/SetReplace pull request #504
Opened 2020-11-01 17:11 UTC by mrektor

First version of features extractor. It computes very simple statistics about the causal graph.

## Changes
* New property for WolframModelEvolutionObject which computes some features that may be useful machine learning explorations
* This first version just consider the CausalGraph associated with the WolframModelEvolutionObject

## Comments
* There might be some "problems" when the property is called on empty objects (with no vertexes). In particular the quantile computation remains unevaluated.

## Examples
 ``
-In[] = WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, 
     w}}, {{0, 0}, {0, 0}}, 5]["FeaturesExtractor"]
``
``
-Out[] = {22, 42, 0, 2, 2, 2, 6, 6}
``

2020-11-02 00:38 UTC, daneelsan requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @maxitg and @mrektor)

___
*[Tests/WolframModelEvolutionObject.wlt, line 1897 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-ML5O5QK6BlAWy8ueDy3:-ML5O5QK6BlAWy8ueDy4:bqxstmm) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Tests/WolframModelEvolutionObject.wlt#L1897)):*
> ```Mathematica
>         }
> 
>       ]
> ```

Missing comma, probably the reason the tests are failing.


<!-- Sent from Reviewable.io -->

2020-11-02 23:50 UTC, maxitg requested changes
This is a good start! I left lots of comments below. Most of them have to do with style/formatting. The only serious issues are a failure for the empty evolutions and the VertexConnectivity which is always zero the way it's implemented.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504#-:-MLALhvlEVqiRD8ACE_9:b8wwm5s)* status: all files reviewed, 32 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 345 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLABX0kCfR-G1InPeHi:-MLAAukIDvXPRBQw_vF1:b-nypt0) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L345)):*
> ```Markdown
> - [Total Element Counts](Properties/TotalElementCounts.md)
> - [Rules](Properties/Rules.md)
> - [Features Extractor](Properties/FeaturesExtractor.md)
> ```

I don't think "FeaturesExtractor" is the correct name since it's not returning a function. I think a better name would be "FeatureVector".
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 345 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLABaaA71XNNye_b97R:-MLABaaA71XNNye_b97S:bli8elw) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L345)):*
> ```Markdown
> - [Total Element Counts](Properties/TotalElementCounts.md)
> - [Rules](Properties/Rules.md)
> - [Features Extractor](Properties/FeaturesExtractor.md)
> ```

Also, add it to the index in `README.md`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 5 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLABq1o3UiafFyKUTkC:-MLABq1o3UiafFyKUTkD:blql2wg) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L5)):*
> ```Markdown
> # FeaturesExtractor
> 
> **`"FeaturesExtractor"`** computes on the fly some features about the `WolframModel`. For now it only computes properties associated to the causal graph `g`.
> ```

Why "on the fly"? It's not doing it during the evolution.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 5 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAC1Vf6aPB2Jg-wh1K:-MLAC1Vf6aPB2Jg-wh1L:b-wu798) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L5)):*
> ```Markdown
> # FeaturesExtractor
> 
> **`"FeaturesExtractor"`** computes on the fly some features about the `WolframModel`. For now it only computes properties associated to the causal graph `g`.
> ```

... features **of** the `WolframModel` **evolution**.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 5 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAC8mU8bS_A8zn-pqx:-MLAC8mU8bS_A8zn-pqy:bbhgsms) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L5)):*
> ```Markdown
> # FeaturesExtractor
> 
> **`"FeaturesExtractor"`** computes on the fly some features about the `WolframModel`. For now it only computes properties associated to the causal graph `g`.
> ```

`WolframModel` should link to the [relevant documentation page](https://github.com/maxitg/SetReplace/blob/featureExtractor/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 5 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLACRbV5xiz2SPje7me:-MLACRbV5xiz2SPje7mf:b-jquk11) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L5)):*
> ```Markdown
> # FeaturesExtractor
> 
> **`"FeaturesExtractor"`** computes on the fly some features about the `WolframModel`. For now it only computes properties associated to the causal graph `g`.
> ```

Add a comma after "For now".
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 5 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLACZfr9t--z9NrfusN:-MLACZfr9t--z9NrfusO:b-hvtu53) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L5)):*
> ```Markdown
> # FeaturesExtractor
> 
> **`"FeaturesExtractor"`** computes on the fly some features about the `WolframModel`. For now it only computes properties associated to the causal graph `g`.
> ```

Associated **with** ...
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 7 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLACcOe0iuQrcwnyxxB:-MLACcOe0iuQrcwnyxxC:b41d4h6) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L7)):*
> ```Markdown
> **`"FeaturesExtractor"`** computes on the fly some features about the `WolframModel`. For now it only computes properties associated to the causal graph `g`.
> 
> The list of properties are:
> ```

The list ... **is**
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 8 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAE8NmAqmhH9P7Qobz:-MLAE8NmAqmhH9P7Qoc-:bjrrew7) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L8)):*
> ```Markdown
> 
> The list of properties are:
> - VertexCount: number of vertexes
> ```

Also known as events count, which I think would be the better way to call it here.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 8 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAEFi-E6IIiD7AI5hO:-MLAEFi-E6IIiD7AI5hP:bgkz4wu) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L8)):*
> ```Markdown
> 
> The list of properties are:
> - VertexCount: number of vertexes
> ```

Is there any particular reason you are using camelcase here given that the property names are not returned?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md, line 8 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAEMp29O8baJ6dhiTz:-MLAEMp29O8baJ6dhiU-:btbp4bl) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeaturesExtractor.md#L8)):*
> ```Markdown
> 
> The list  [...]

2020-11-04 17:34 UTC, mrektor commented
I tried to fix all the suggestions of @maxitg 
Now it works even with empty evolutions

2020-11-05 16:53 UTC, maxitg requested changes
By the way, it would help if you go to Reviewable and reply to the comments after you address them (or if you disagree with them).

> Reviewed 1 of 6 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504#-:-MLOJa8-BIXqLuoPLEyi:b-ark1xk)* status: all files reviewed, 16 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 5 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJqmNm7fXrlCpMu8jz:-MLJqmNn1FEud4DFYJv0:b-k5o8yk) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L5)):*
> ```Markdown
> # FeatureVector
> 
> **`"FeatureVector"`** computes some features of the [`WolframModel`](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution. For now, it only computes properties associated with the causal graph `g`:
> ```

Add `/` to the beginning of the link. The links without `/` are relative, and thus it tries to find it in `/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject.md`, which of course fails. Adding a `/` to the beginning makes the link absolute.

The same applies to other links below.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 7 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJzP0-77r4yJ5G1HYk:-MLJzP0-77r4yJ5G1HYl:b-aixqmc) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L7)):*
> ```Markdown
> **`"FeatureVector"`** computes some features of the [`WolframModel`](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution. For now, it only computes properties associated with the causal graph `g`:
> 
> Example usage:
> ```

We don't need the words "Example usage" here. It's already obvious it's an example.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsBD2BAGNaXWpNoku:-MLJsBD2BAGNaXWpNokv:b-lsddmg) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
> ```Markdown
> 
> The list of properties is:
> - VertexCount: number of vertexes, also known as [`EventsCount`](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md)
> ```

Why not just call it "events count" to begin with?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJyilW6mtbM8Rjz81s:-MLJyilW6mtbM8Rjz81t:bejlwe) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
> ```Markdown
> 
> The list of properties is:
> - VertexCount: number of vertexes, also known as [`EventsCount`](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md)
> ```

Is there any particular reason you are using CamelCase here given that the property names are not returned?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-MLJsJMT9I_yaQzWpQkL:b-avurh3) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
> ```Markdown
> The list of properties is:
> - VertexCount: number of vertexes, also known as [`EventsCount`](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md)
> - EdgeCount: number of edges, also known as the total number of expressions (except for expressions in the initial and final states). See [Total Element Counts](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TotalElementCounts.md)
> ```

Is there any benefit to computing the edge count in the causal graph instead of just total expressions count (which is a more natural property)?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 30 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJzhPIDOYNeYx8FpS_:-MLJzhPIDOYNeYx8FpSa:bazoh0p) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L30)):*
> ```Markdown
> 
> ```wl
> In[] := possibileInitsBi = 
> ```

Remove trailing spaces everywhere below (frontend adds them to copied code for some reason, so they need to be removed manually afterwards).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 30 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOAxYT1cAJNNPSExJs:-MLOAxYU7N4pJa2mDBHv:bo7e60a) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L30)):*
> ```Markdown
> 
> ```wl
> In[] := possibileInitsBi = 
> ```

Use descriptive names. I don't know what `Bi` is, for example.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 31 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOB2f-CIE3W9TSQDrW:-MLOB2f-CIE3W9TSQDrX:bnph9fv) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L31)):*
> ```Markdown
> ```wl
> In[] := possibileInitsBi = 
>   Flatten[Table[{{i, j}, {z, k}}, {i, {0, 1, 2, 3}}, {j, {0, 1, 2, 
> ```

Here is a simpler way to do this:

```wl
inits = Partition[#, 2] & /@ Tuples[ConstantArray[Range[0, 3], 4]];
```
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 45 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOFwjh-5VuxTT_o8B2:-MLOFwjh-5VuxTT_o8B3:b-ejqjxn) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L45)):*
> ```Markdown
> 
> 
> FeatureSpacePlot[feats -> plots, LabelingFunction -> Tooltip]
> ```

Since labels are not visible in the documentation, I suggest to reduce these examples to one:

```wl
In[] := FeatureSpacePlot[#["FeatureVector"] -> #[
     "CausalGraph"] & /@ (WolframModel[{{x, y}, {x, z}} -> {{x,
         z}, {x, w}, {y, w}, {z, w}}, #, 6] &) /@ inits]
```
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 50 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOG79j2VCZQr19OFcg:-MLOG79j2VCZQr19OFch:baoo4iz) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelE [...]

2020-11-05 17:44 UTC, mrektor reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504#-:-MLOQ96Z2OO7Aq9OS8fN:bnfp4nl)* status: all files reviewed, 16 unresolved discussions (waiting on @daneelsan, @maxitg, and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 5 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJqmNm7fXrlCpMu8jz:-MLOQmlvEKpV6jSnsThT:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L5)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Add `/` to the beginning of the link. The links without `/` are relative, and thus it tries to find it in `/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject.md`, which of course fails. Adding a `/` to the beginning makes the link absolute.

The same applies to other links below.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 7 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJzP0-77r4yJ5G1HYk:-MLOQur3EiSKDXaDMhmv:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L7)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

We don't need the words "Example usage" here. It's already obvious it's an example.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsBD2BAGNaXWpNoku:-MLORdNK2h2mWioCmX0u:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Why not just call it "events count" to begin with?
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJyilW6mtbM8Rjz81s:-MLORdpvBS_qjdu1UCIo:bxo652o) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Is there any particular reason you are using CamelCase here given that the property names are not returned?
</blockquote></details>

Yes I was using camelCase because I wanted to be transparent about which functions I was calling. I think that it is more reasonable as you say to use the words "of the field", so Event Counts and Expression Count w.r.t VertexCount and EdgeCount of the causal graph. Actually I am just now really getting to know these creatures, I was not aware of this equivalence.

Should I define the implementation of these quantities as #["EventCounts"] instead of VertexDegree[#["CausalGraph"]] ? Are we losing performances in my implementation?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-MLOSQ9SBPl0SARFYVad:b-i78amp) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Is there any benefit to computing the edge count in the causal graph instead of just total expressions count (which is a more natural property)?
</blockquote></details>

See previous discussion.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 30 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJzhPIDOYNeYx8FpS_:-MLOTJHL6geSawDitafR:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L30)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove trailing spaces everywhere below (frontend adds them to copied code for some reason, so they need to be removed manually afterwards).
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 30 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOAxYT1cAJNNPSExJs:-MLOTJfn5jNtzU_EMI2k:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L30)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use descriptive names. I don't know what `Bi` is, for example.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 31 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOB2f-CIE3W9TSQDrW:-MLOTPkr0NzG56zKsJbO:b7eue7f) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Here is a simpler way to do this:

```wl
inits = Partition[#, 2] & /@ Tuples[ConstantArray[Range[0, 3], 4]];
```
</blockquote></details>

Cool! I knew it was not elegant my implementation... Thanks for this script.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 50 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOG79j2VCZQr19OFcg:-MLOUgUj7DE9NJ5HocKm:bxttdv1) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L50)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This should (obviously) be an image. If you are on a Mac, [this](https://github.com/maxitg/SetReplace/blob/master/.github/CONTRIBUTING.md#markdown) should work. Otherwise, take a look at #506. But for this case, here is the image:

![image.png](https://files.reviewableusercontent.io/images/reviewable/1479325/GH2UsxGNRDPF4j8M1hTur0Mm/image.png)
</blockquote></details>

Done. I hope it works.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 52 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOGjtjEuKhVIwQNqmG:-MLOUq2Z14skBBl6rVUR:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L52)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove excessive empty lines at t [...]

2020-11-06 14:55 UTC, maxitg requested changes
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 15 unresolved discussions (waiting on @daneelsan, @maxitg, and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJyilW6mtbM8Rjz81s:-MLPBr3zD7o0pDcjsIIt:bvn1kww) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Yes I was using camelCase because I wanted to be transparent about which functions I was calling. I think that it is more reasonable as you say to use the words "of the field", so Event Counts and Expression Count w.r.t VertexCount and EdgeCount of the causal graph. Actually I am just now really getting to know these creatures, I was not aware of this equivalence.

Should I define the implementation of these quantities as #["EventCounts"] instead of VertexDegree[#["CausalGraph"]] ? Are we losing performances in my implementation?
</blockquote></details>

Yes, `#["EventsCount"]` is faster.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-MLPCWQB25daE-OWcV98:b-hgpvo1) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

See previous discussion.
</blockquote></details>

This case is more important because it changes the output, not only performance.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 50 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLOG79j2VCZQr19OFcg:-MLPG3XLA4JhIzXLwSTE:b-fp73re) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L50)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done. I hope it works.
</blockquote></details>

Yes, it does.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 7 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPDb2e3KLNbm_Jqpta:-MLPDb2e3KLNbm_Jqptb:b-1h0f1p) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L7)):*
> ```Markdown
> **`"FeatureVector"`** computes some features of the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution. For now, it only computes properties associated with the causal graph `g`:
> ```

There should be at most one empty line at a time.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPBUYG7Xg6r864oYYg:-MLPBUYH1VY1quvpIq_J:b-91qbe7) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
> ```Markdown
> 
> The list of properties is:
> - [`EventsCount`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md): Also equal to the number of vertex in the causal graph.
> ```

vertex -> vertices
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPBawBA7nj9Ox81fv4:-MLPBawC1XBSoWeZrn4R:bvm483b) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
> ```Markdown
> 
> The list of properties is:
> - [`EventsCount`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md): Also equal to the number of vertex in the causal graph.
> ```

Capitalization after the colon in each line should be consistent.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPC9u9D2Li4Fy1b7kH:-MLPC9u9D2Li4Fy1b7kI:bhucab) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
> ```Markdown
> The list of properties is:
> - [`EventsCount`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md): Also equal to the number of vertex in the causal graph.
> - [`TotalElementCounts`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TotalElementCounts.md): the total number of expressions (except for expressions in the initial and final states). Equivalent to the number of edges in the causal graph. 
> ```

`TotalElementCounts` -> `ExpressionsCountTotal`. Because you are not using the count of atoms (which is the other type of "element").
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPDJar7SC6XVra482e:-MLPDJar7SC6XVra482f:bdiro19) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
> ```Markdown
> The list of properties is:
> - [`EventsCount`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md): Also equal to the number of vertex in the causal graph.
> - [`TotalElementCounts`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TotalElementCounts.md): the total number of expressions (except for expressions in the initial and final states). Equivalent to the number of edges in the causal graph. 
> ```

Remove a trailing space (I suggest enabling drawing white space in the editor to avoid these)
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 18 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPCvoOBINzLAm7TZXO:-MLPCvoOBINzLAm7TZXP:b-1bxdfq) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L18)):*
> ```Markdown
> - [`TotalElementCounts`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TotalElementCounts.md): the total number of expressions (except for expressions in the initial and final states). Equivalent to the number of edges in the causal graph. 
> - [`VertexConnectivity`](https://reference.wolfram.com/language/ref/VertexConnectivity.html): the smallest number of vertices whose deletion from `g` disconnects `g`. This is computed on the undirected version of the causal graph.
> - VertexDegreesQuantiles: The quantiles 0, 0.25, 0.50, 0.75, 1 of the [vertex degrees](https://reference.wolfram.com/language/ref/Ve [...]

2020-11-06 18:30 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 15 unresolved discussions (waiting on @daneelsan, @maxitg, and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJyilW6mtbM8Rjz81s:-MLTj5vO3yJidnQH4nhH:b-jbd2x) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Yes, `#["EventsCount"]` is faster.
</blockquote></details>

I was thinking that since I still compute the causal graph (for other features) the VertexCount should be "free" in a sense... what do you think? (Just for keeping the implementation simple as it is)
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-MLTjnurA4H-4lqJHPgy:b-m72d20) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This case is more important because it changes the output, not only performance.
</blockquote></details>

Since I'm already computing the causal graph, do you want that I implement those properties just as property calling or can I leave it as it is?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 7 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPDb2e3KLNbm_Jqpta:-MLTisc0ACoSZDbcUylt:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L7)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

There should be at most one empty line at a time.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPBUYG7Xg6r864oYYg:-MLTjVnr879SSc2rdhwf:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

vertex -> vertices
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPBawBA7nj9Ox81fv4:-MLTje_M243inAu53a8S:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Capitalization after the colon in each line should be consistent.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPDJar7SC6XVra482e:-MLTldwrCqmfnRWxGL3K:b-abp309) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove a trailing space (I suggest enabling drawing white space in the editor to avoid these)
</blockquote></details>

I do not understand which space
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 18 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPCvoOBINzLAm7TZXO:-MLTlPyXBceSDgGSd-dU:brkwc75) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L18)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Would it be better to change it to

[`VertexDegree`](https://reference.wolfram.com/language/ref/VertexDegree.html) quantiles: the quantiles ...

Because otherwise, the camelcase does not refer to any existing symbol or property.
</blockquote></details>

make sense
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 18 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPDGyf1sZFVFUMiU2x:-MLTlo7oEgfhq-rG0d_H:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L18)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Add a period after "distribution".
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 27 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPDynzB8-twu9DNHig:-MLTlxh9CW5QetZGMawt:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L27)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think it will look better if we move `In[] :=` here, that is,

```wl
inits = ...;

In[] := FeatureSpacePlot[...]
```
</blockquote></details>

Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1889 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAKJZd6BoK2TAhs8n7:-MLToJnh94NzSGG_KIaD:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Tests/WolframModelEvolutionObject.wlt#L1889)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Will add more
</blockquote></details>

Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1894 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLT0mrx5AFxJfcYITjK:-MLToa-S4v-a0ee3H8xV:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Tests/WolframModelEvolutionObject.wlt#L1894)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`VerificationTest` needs to compute the thing being tested within itself. Otherwise, the error message you would get will not tell you what the input was. So, I think the best way to do it here would be to store the rule and the init in variables (using `With` as you do above) and compute the `"FeatureVector"` here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-06 18:31 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: 4 of 6 files reviewed, 15 unresolved discussions (waiting on @daneelsan, @maxitg, and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPC9u9D2Li4Fy1b7kH:-MLTov97EbyyiO-ffGbQ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`TotalElementCounts` -> `ExpressionsCountTotal`. Because you are not using the count of atoms (which is the other type of "element").
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-06 18:33 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: 3 of 6 files reviewed, 15 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 32 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPAlGi3ZmQfQsIOdZu:-MLTpLrLEtzf2Cq71-Zr:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L32)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

We don't use hyphens in any other image names, so I suggest removing it here as well for consistency.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-08 03:03 UTC, maxitg requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 8 unresolved discussions (waiting on @daneelsan and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJyilW6mtbM8Rjz81s:-ML_eZNs7dic6xN-TnU9:b-8n327p) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I was thinking that since I still compute the causal graph (for other features) the VertexCount should be "free" in a sense... what do you think? (Just for keeping the implementation simple as it is)
</blockquote></details>

Yes, good point.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-ML_fgpXExifGkgMa9Y7:b-snsf81) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Since I'm already computing the causal graph, do you want that I implement those properties just as property calling or can I leave it as it is?
</blockquote></details>

Well, ok, we can leave it for now. (Although in this case let's go back to your original description as the `EdgeCount` in the causal graph.)

But once we add other features related to properties of the evolution object, I think it will make more sense to put `"ExpressionsCountTotal"` there, and remove this property (because it would essentially be computing the same thing).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPBUYG7Xg6r864oYYg:-ML_fBNc728_OeaGy8HX:b-txjogq) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I mean there is a typo in the `EventsCount`: "... the number of vertex in the causal graph ..." -> "... the number of vertices in the causal graph".
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPBawBA7nj9Ox81fv4:-ML_fQkB3E6ZFcBSajN2:b50zidf) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same on the next line (after `ExpressionsCountTotal`).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPDJar7SC6XVra482e:-ML_gp_-6Afl-t5uiYDo:bm1ww3e) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I do not understand which space
</blockquote></details>

It's no longer there (the space at the end of this line).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 18 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPCvoOBINzLAm7TZXO:-ML_h2aFEcRg2lQB3QpI:b-aq7vz1) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L18)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

make sense
</blockquote></details>

The property is `VertexDegree `, not `VertexDegrees`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 18 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-ML_hzX9DKZy6-xJrirj:-ML_hzX9DKZy6-xJrirk:b-lblw5r) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L18)):*
> ```Markdown
> - [`TotalElementCounts`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TotalElementCounts.md): the total number of expressions (except for expressions in the initial and final states). Equivalent to the number of edges in the causal graph. 
> - [`VertexConnectivity`](https://reference.wolfram.com/language/ref/VertexConnectivity.html): the smallest number of vertices whose deletion from `g` disconnects `g`. This is computed on the undirected version of the causal graph.
> - VertexDegreesQuantiles: The quantiles 0, 0.25, 0.50, 0.75, 1 of the [vertex degrees](https://reference.wolfram.com/language/ref/VertexDegree.html) distribution
> ```

It should be "vertex degrees", not "vertices degrees" after the quantile numbers (and we probably don't need to link it twice).
___
*[Tests/WolframModelEvolutionObject.wlt, line 1886 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAJjMs5LQZN-deqXmP:-ML_j2H4CZcyPoLl1OfP:brebr6l) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Tests/WolframModelEvolutionObject.wlt#L1886)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

There are still trailing spaces. And `featuresEmptyGraph` should be on the next line (indentation needs to be consistent).
</blockquote></details>

There are still trailing spaces (spaces at the end of lines).
___
*[Tests/WolframModelEvolutionObject.wlt, line 1886 at r5](https://reviewable.io/reviews/maxitg/setreplace/504#-ML_jhG772vOIlwA7Z_q:-ML_jhG772vOIlwA7Z_r:bxa7vm3) ([raw file](https://github.com/maxitg/setreplace/blob/973712446e6a32c98e55211ba917e3aa5c69d14c/Tests/WolframModelEvolutionObject.wlt#L1886)):*
> ```Mathematica
>       (* FeatureVector *)
>       With[{
>           featuresEmptyGraph = 
> ```

Why don't we do the following?

We can generate all these evolutions with one line:

```wl
evolutionObjects = WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, ##] & @@@
  {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}
```

And then, we can test them in one line as well:

```wl
VerificationTest[And @@ NumberQ /@ #["FeatureVector"]] & /@ evolutionObjects
```


<!-- Sent from Reviewable.io -->

2020-11-08 13:42 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 8 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-MLc320Q-Mm9cjUPs58c:b-gs1cmz) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Well, ok, we can leave it for now. (Although in this case let's go back to your original description as the `EdgeCount` in the causal graph.)

But once we add other features related to properties of the evolution object, I think it will make more sense to put `"ExpressionsCountTotal"` there, and remove this property (because it would essentially be computing the same thing).
</blockquote></details>

I agree. As soon as we have this first version 0.x of this feature I will begin extending it.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 15 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPBawBA7nj9Ox81fv4:-MLc2w0yDrjuYkCjkD6e:b-8vtl2r) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L15)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Same on the next line (after `ExpressionsCountTotal`).
</blockquote></details>

sorry I missed that
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 18 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-MLPCvoOBINzLAm7TZXO:-MLc3J_J01pEDkb1LUXo:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L18)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The property is `VertexDegree `, not `VertexDegrees`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 18 at r4](https://reviewable.io/reviews/maxitg/setreplace/504#-ML_hzX9DKZy6-xJrirj:-MLc3TKY-13MIY8f4BcY:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/5f5aa46b06cfa538f008c06399385797759a4bab/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L18)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It should be "vertex degrees", not "vertices degrees" after the quantile numbers (and we probably don't need to link it twice).
</blockquote></details>

Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1886 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAJjMs5LQZN-deqXmP:-MLc45rc6sHjXXEfy60s:boxjog2) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Tests/WolframModelEvolutionObject.wlt#L1886)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

There are still trailing spaces (spaces at the end of lines).
</blockquote></details>

I hope is ok now (I tried to emulate other with statements in the code), if not we could meet on Discord so that the changes can be done correctly in one shot (I am still learning the proper style)
___
*[Tests/WolframModelEvolutionObject.wlt, line 1886 at r5](https://reviewable.io/reviews/maxitg/setreplace/504#-ML_jhG772vOIlwA7Z_q:-MLc4dIb7_vkCjMsLcRq:bm8c7v6) ([raw file](https://github.com/maxitg/setreplace/blob/973712446e6a32c98e55211ba917e3aa5c69d14c/Tests/WolframModelEvolutionObject.wlt#L1886)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Why don't we do the following?

We can generate all these evolutions with one line:

```wl
evolutionObjects = WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, ##] & @@@
  {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}
```

And then, we can test them in one line as well:

```wl
VerificationTest[And @@ NumberQ /@ #["FeatureVector"]] & /@ evolutionObjects
```
</blockquote></details>

Neat!!!


<!-- Sent from Reviewable.io -->

2020-11-08 16:39 UTC, maxitg requested changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 3 unresolved discussions (waiting on @daneelsan and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-MLcg2LGESPXqshULjgS:b9rugax) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I agree. As soon as we have this first version 0.x of this feature I will begin extending it.
</blockquote></details>

I think the description is kind of confusing now though. Let's go with one more similar to your original description, i.e., something like this:

```markdown
- [EdgeCount](https://reference.wolfram.com/language/ref/EdgeCount.html): Related to the [total number of expressions](TotalElementCounts.md)
```
___
*[Tests/WolframModelEvolutionObject.wlt, line 1886 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAJjMs5LQZN-deqXmP:-MLcd2ivCyxlhvvcrldx:b-4aft85) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Tests/WolframModelEvolutionObject.wlt#L1886)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I hope is ok now (I tried to emulate other with statements in the code), if not we could meet on Discord so that the changes can be done correctly in one shot (I am still learning the proper style)
</blockquote></details>

There are two problems with the style currently: the line width should be limited to 120 characters, and the indentation for code on deeper levels should never go to the left.

E.g., instead of this:

```wl
  With[{x = 1},
x + 1
  ]
```

Do this (two spaces at a time for code at deeper levels):

```wl
  With[{x = 1},
    x + 1
  ]
```

The indentation level should only be the same if the lines are "parallel" (either compound expression, or multiple arguments to the same function).

I.e., this is good:

```wl
ModuleScope[
  x = 1;
  y = x + 1;
  Graph[  (* the entire graph expression can be on one line as well if within 120 line width *)
    {x, y},
    {x -> y, y -> x}]
]
```

but not this:

```wl
ModuleScope[
  x = 1;
  y = x + 1;
    Graph[
    {x, y},
    {x -> y, y -> x}]
]
```

For this code specifically, here is a way to do it (it's not necessary to put `VerificationTest[...]` in a list):

```wl
      (* FeatureVector *)
      With[{
          evolutionObjects =
            WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, ##] & @@@
              {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}},
        VerificationTest[And @@ NumberQ /@ #["FeatureVector"]] & /@ evolutionObjects
      ],
```


<!-- Sent from Reviewable.io -->

2020-11-08 18:28 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 3 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 16 at r3](https://reviewable.io/reviews/maxitg/setreplace/504#-MLJsJMT9I_yaQzWpQkK:-MLd4tF4BplUH4j38Sv7:b-wv081v) ([raw file](https://github.com/maxitg/setreplace/blob/92877c29c74ab429752662d044465bd0d2a58b38/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think the description is kind of confusing now though. Let's go with one more similar to your original description, i.e., something like this:

```markdown
- [EdgeCount](https://reference.wolfram.com/language/ref/EdgeCount.html): Related to the [total number of expressions](TotalElementCounts.md)
```
</blockquote></details>

Ok, I'll change it also EventsCount->VertexCount for consistency then.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1886 at r1](https://reviewable.io/reviews/maxitg/setreplace/504#-MLAJjMs5LQZN-deqXmP:-MLd6LhQ43h6SG8TOOlj:b-odk0a7) ([raw file](https://github.com/maxitg/setreplace/blob/8b2cefb16c62d79393de5e3470a28e543f4ebaf4/Tests/WolframModelEvolutionObject.wlt#L1886)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

There are two problems with the style currently: the line width should be limited to 120 characters, and the indentation for code on deeper levels should never go to the left.

E.g., instead of this:

```wl
  With[{x = 1},
x + 1
  ]
```

Do this (two spaces at a time for code at deeper levels):

```wl
  With[{x = 1},
    x + 1
  ]
```

The indentation level should only be the same if the lines are "parallel" (either compound expression, or multiple arguments to the same function).

I.e., this is good:

```wl
ModuleScope[
  x = 1;
  y = x + 1;
  Graph[  (* the entire graph expression can be on one line as well if within 120 line width *)
    {x, y},
    {x -> y, y -> x}]
]
```

but not this:

```wl
ModuleScope[
  x = 1;
  y = x + 1;
    Graph[
    {x, y},
    {x -> y, y -> x}]
]
```

For this code specifically, here is a way to do it (it's not necessary to put `VerificationTest[...]` in a list):

```wl
      (* FeatureVector *)
      With[{
          evolutionObjects =
            WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, ##] & @@@
              {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}},
        VerificationTest[And @@ NumberQ /@ #["FeatureVector"]] & /@ evolutionObjects
      ],
```
</blockquote></details>

Thanks, I think I got it.


<!-- Sent from Reviewable.io -->

2020-11-09 03:13 UTC, maxitg requested changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 6 unresolved discussions (waiting on @daneelsan and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 13 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLexY7_4D8NGSHKOvcr:-MLexY7a-vd4m-e8jn0B:b7nncx) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L13)):*
> ```Markdown
> 
> The list of properties is:
> - [`VertexCount`](https://reference.wolfram.com/language/ref/VertexCount.html): The number of vertices in the causal graph. Related to the [total number of events]((/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/EventCounts.md)
> ```

The second link does not work because of the extra opening parentheses.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1887 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyAjW5V8eZOJrmH8E:-MLeyAjW5V8eZOJrmH8F:b-jb8c1m) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1887)):*
> ```Mathematica
> 
>       With[{
>           evolutionObjects = 
> ```

Remove the trailing space.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1889 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyCq27OrQ1dRjXov0:-MLeyCq27OrQ1dRjXov1:b-jb8c1m) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1889)):*
> ```Mathematica
>           evolutionObjects = 
>             WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, ##] & @@@
>               {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}}, 
> ```

Remove the trailing space.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1890 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyTrR2rpE5I2b5Ocj:-MLeyTrR2rpE5I2b5Ock:b35hi5x) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1890)):*
> ```Mathematica
>             WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, ##] & @@@
>               {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}}, 
>             VerificationTest[And @@ NumberQ /@ #["FeatureVector"]] & /@ evolutionObjects
> ```

`VerificationTest` should not be indented farther to the right than `evolutionObject` because this way it looks like a part of the `evolutionObject`'s definition.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1891 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeydUK6Gf5afN2k80b:-MLeydUK6Gf5afN2k80c:bjb3jud) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1891)):*
> ```Mathematica
>               {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}}, 
>             VerificationTest[And @@ NumberQ /@ #["FeatureVector"]] & /@ evolutionObjects
>         ],
> ```

The closing bracket should be indented the same as the corresponding code that opens it.

E.g.,

```wl
With[...
  ...
]
```

not

```wl
With[...
    ...
  ]
```

(Sorry for nitpicking so much about the code style, but the consistent style makes the code a lot more readable because one can see the structure immediately without having to understand the code first. We have a plan to automate this process #247 at which point this will no longer be an issue.)


<!-- Sent from Reviewable.io -->

2020-11-09 20:00 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 13 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLexY7_4D8NGSHKOvcr:-MLiZlveBpQZGStPiQzl:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L13)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The second link does not work because of the extra opening parentheses.
</blockquote></details>

Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1887 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyAjW5V8eZOJrmH8E:-MLiZtIV17rIRyfsuUvB:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1887)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove the trailing space.
</blockquote></details>

Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1889 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyCq27OrQ1dRjXov0:-MLi_NEb1aOkVAdX960V:b-ggwtv3) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1889)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove the trailing space.
</blockquote></details>

I guess you mean after @@@, Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1890 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyTrR2rpE5I2b5Ocj:-MLi_eKV8E0nnrluuLU7:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1890)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`VerificationTest` should not be indented farther to the right than `evolutionObject` because this way it looks like a part of the `evolutionObject`'s definition.
</blockquote></details>

Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1891 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeydUK6Gf5afN2k80b:-MLi_nIhCnJkyDvLrXHS:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1891)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The closing bracket should be indented the same as the corresponding code that opens it.

E.g.,

```wl
With[...
  ...
]
```

not

```wl
With[...
    ...
  ]
```

(Sorry for nitpicking so much about the code style, but the consistent style makes the code a lot more readable because one can see the structure immediately without having to understand the code first. We have a plan to automate this process #247 at which point this will no longer be an issue.)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-09 20:42 UTC, maxitg requested changes
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 3 unresolved discussions (waiting on @daneelsan and @mrektor)

___
*[Tests/WolframModelEvolutionObject.wlt, line 1887 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyAjW5V8eZOJrmH8E:-MLiih_J2cGovkBmq4m-:b7vvtcu) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1887)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, I don't mean the linebreak. I mean the space at the end of the line, which is still there in `...evolutionObjects = `. The line is now too long. There is a 120 characters limit.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1889 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyCq27OrQ1dRjXov0:-MLiis1x3JdRTQySg8Li:brhumzt) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1889)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I guess you mean after @@@, Done.
</blockquote></details>

Same here.


<!-- Sent from Reviewable.io -->

2020-11-09 22:06 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 3 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Tests/WolframModelEvolutionObject.wlt, line 1887 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyAjW5V8eZOJrmH8E:-MLj1_-GBYUIM05g7tDv:byv0agc) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1887)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

No, I don't mean the linebreak. I mean the space at the end of the line, which is still there in `...evolutionObjects = `. The line is now too long. There is a 120 characters limit.
</blockquote></details>

Now I think I get it. I do not have a flag on trailing spaces on my editor... maybe I should set it up so we can manage these problems with fewer ping-pong commits


<!-- Sent from Reviewable.io -->

2020-11-10 15:57 UTC, maxitg requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 2 unresolved discussions (waiting on @daneelsan and @mrektor)

___
*[Tests/WolframModelEvolutionObject.wlt, line 1887 at r7](https://reviewable.io/reviews/maxitg/setreplace/504#-MLeyAjW5V8eZOJrmH8E:-MLmoD2d-jr_E-KUq0xJ:bhsmgkn) ([raw file](https://github.com/maxitg/setreplace/blob/b221f3417d66845d8c087755a252cd96cb95b5a1/Tests/WolframModelEvolutionObject.wlt#L1887)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Now I think I get it. I do not have a flag on trailing spaces on my editor... maybe I should set it up so we can manage these problems with fewer ping-pong commits
</blockquote></details>

Ok, almost there.
1. Remove the trailing space after `@@@`.
2. Move the indentation in `WolframModel...` and `VerificationTest...` two spaces to the left.

The indentation is two spaces at a time. Currently, it's four spaces between `With...` and the closest one which is `VerificationTest...`.

In other words, this:

```wl
With[{a = 1},
    a + 1
]
```

or this:

```wl
With[{
      a = 1},
    a + 1
]
```

have too many spaces, but this one is ok because even though the next line after `With...` is indented 4 spaces, the line after that (which is still inside `With[...]` is only indented 2):

```wl
With[{
    a = 1},
  a + 1
]
```

3. Keep `{{0}}, ...` line where it is because it is (semantically) inside `WolframModel`, so it should be indented two spaces compared to it.

In other words, the entire code block with all the above constraints becomes:

```wl
      With[{evolutionObjects =
          WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, ##] & @@@
            {{0}, {3, "EventSelectionFunction" -> "MultiwaySpacelike"}, {3}, {8}}},
        VerificationTest[And @@ NumberQ /@ #["FeatureVector"]] & /@ evolutionObjects
      ],
```

By the way, the reason `WolframModel...` is indented more than `VerificationTest...` is because it's at a deeper level within the expression:

`With` -> `List` -> `evolutionObject = ` -> `WolframModel...` on one hand, versus
`With` -> `VerificationTest...` on the other.

I realize these rules might seem arbitrary and unnecessary at first, but after some practice, they make it much easier to read the code because one can see the structure immediately without the need for brackets counting.

We actually have a system that can format the C++ code automatically using a similar approach (`./lint.sh` script). Unfortunately, we don't yet have it for Wolfram Language because the tools are not quite as developed (I plan to work on a partial implementation this week).


<!-- Sent from Reviewable.io -->

2020-11-10 20:38 UTC, maxitg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> :rocket:

> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504#-:-MLnsHRuEO7CxLdTgXO8:b-snql9h)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)



<!-- Sent from Reviewable.io -->

2020-11-10 23:44 UTC, daneelsan approved these changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/504)* status: all files reviewed, 1 unresolved discussion (waiting on @daneelsan)



<!-- Sent from Reviewable.io -->

2020-11-11 15:30 UTC, maxitg commented
@mrektor, don't forget to copy the PR message into the commit message when merging.

2020-11-11 18:19 UTC, merged