RandomHypergraph
maxitg/SetReplace pull request #511
Opened 2020-11-03 02:51 UTC by daneelsan

## Changes
* Close #510.
* Implements `RandomHypergraph` function.

## Comments
* Unsure whether the error message name is the best choice: `"invalidEnum"`.

## Examples

```wl
In[]:= SeedRandom[123];
RandomHypergraph[8]
Out[]= {{5, 6, 3}, {5, 1}, {2, 2}, {5}}

In[]:= RandomHypergraph[{10, {5, 2}}]
Out[]= {{4, 1}, {8, 4}, {2, 5}, {6, 10}, {10, 5}}

In[]:= RandomHypergraph[{10, {{5, 2}, {4, 3}}}]
Out[]= {{5, 5}, {1, 10}, {3, 1}, {8, 10}, {10, 6}, {8, 9, 7}, {7, 3, 10}, {6, 9, 2}, {4, 3, 3}}
```

```wl
In[]:= SeedRandom[111];
Grid[Partition[
  Table[Labeled[WolframModelPlot@#, # -> i] &[
    RandomHypergraph[i]], {i, 1, 12}], 3, 3, 1], Frame -> All]
```
![image](https://user-images.githubusercontent.com/40190339/97945430-8d00d600-1d55-11eb-86f3-cfc3b1a4521a.png)

## Documentation

![image](https://user-images.githubusercontent.com/40190339/97945209-cc7af280-1d54-11eb-8c7f-ac6d2c2d91a3.png)

2020-11-03 07:34 UTC, taliesinb requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @daneelsan and @maxitg)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 7 at r1](https://reviewable.io/reviews/maxitg/setreplace/511#-MLC0RN-6Hm4HBWfSFYM:-MLC0RN-6Hm4HBWfSFYN:b-xntckd) ([raw file](https://github.com/maxitg/setreplace/blob/5dc1872051b25355386b3153f9c54a8c6427e9b1/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L7)):*
> ```Markdown
> **`RandomHypergraph`** generates a random hypergraph.
> 
> Pass a non-negative integer `n` to generate a hypergraph that has `n` as its total number of hyperedge parts, i.e. its "complexity":
> ```

Mathematica's `RandomGraph` function doesn't directly support a single `n` syntax. Do you have an argument for why we should do that?

Also, what is a "hyperedge part"? Do you mean the a hyperedge vertex? Or the number of hyperedges? We should avoid vague language in favor of saying precisely what we mean.
___
*[Kernel/RandomHypergraph.m, line 40 at r1](https://reviewable.io/reviews/maxitg/setreplace/511#-MLC0LNT3QtXYnpfR5pv:-MLC0LNT3QtXYnpfR5pw:bp4qv08) ([raw file](https://github.com/maxitg/setreplace/blob/5dc1872051b25355386b3153f9c54a8c6427e9b1/Kernel/RandomHypergraph.m#L40)):*
> ```
> randomHypergraph[enum_Integer ? NonNegative] :=
>   RandomInteger[{1, enum}, #] & /@ RandomChoice[IntegerPartitions[enum]]
> ```

Can you explain the strategy here?


<!-- Sent from Reviewable.io -->

2020-11-03 16:12 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 7 at r1](https://reviewable.io/reviews/maxitg/setreplace/511#-MLC0RN-6Hm4HBWfSFYM:-MLDqYy17tfSY8YQyqSx:b-wlwrvp) ([raw file](https://github.com/maxitg/setreplace/blob/5dc1872051b25355386b3153f9c54a8c6427e9b1/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L7)):*
<details><summary><i>Previously, taliesinb (Taliesin Beynon) wrote…</i></summary><blockquote>

Mathematica's `RandomGraph` function doesn't directly support a single `n` syntax. Do you have an argument for why we should do that?

Also, what is a "hyperedge part"? Do you mean the a hyperedge vertex? Or the number of hyperedges? We should avoid vague language in favor of saying precisely what we mean.
</blockquote></details>

Yes you are right. I'll explain the `n` argument below.
___
*[Kernel/RandomHypergraph.m, line 40 at r1](https://reviewable.io/reviews/maxitg/setreplace/511#-MLC0LNT3QtXYnpfR5pv:-MLDqe_88d3uLnNxOvfO:b3rkuer) ([raw file](https://github.com/maxitg/setreplace/blob/5dc1872051b25355386b3153f9c54a8c6427e9b1/Kernel/RandomHypergraph.m#L40)):*
See @maxitg comments in:

* https://github.com/maxitg/SetReplace/issues/510#issuecomment-720789127

* https://github.com/maxitg/SetReplace/issues/462
> For all functions below, I think we should also allow a single integer as the argument, specifying the complexity, Length[Flatten[# /. Rule -> List]] &(assuming atom names are not lists), which would then produce all rules/hypergraphs up to that complexity, including systems of multiple rules.

So the idea was to have this integer `n` be the (total) sum of the hyperedge arities of the generated hypergraph.
For example, for `6`, `IntegerPartitions` returns all possible configuration of hyperedge arities that total 6:
```wl
In[]:= IntegerPartitions[6]
Out[]= {{6}, {5, 1}, {4, 2}, {4, 1, 1}, {3, 3}, {3, 2, 1}, {3, 1, 1, 1}, {2, 2, 2}, {2, 2, 1, 1}, {2, 1, 1, 1, 1}, {1, 1, 1, 1, 1, 1}}
```
Then I choose one of them randomly to generate the hypergraph.

I might be mistaken in the implementation, so feel free to correct me.


<!-- Sent from Reviewable.io -->

2020-11-04 10:54 UTC, maxitg requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: all files reviewed, 13 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 7 at r1](https://reviewable.io/reviews/maxitg/setreplace/511#-MLC0RN-6Hm4HBWfSFYM:-MLHj26YEieu-_syhBhR:b-fnsx0i) ([raw file](https://github.com/maxitg/setreplace/blob/5dc1872051b25355386b3153f9c54a8c6427e9b1/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L7)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Yes you are right. I'll explain the `n` argument below.
</blockquote></details>

It doesn't hurt to explain more if it's confusing, but isn't "hyperedge part" exactly the right term? Since it's literally, `Part[{a, b, c}, 2]`. Hyperedge vertex is ambiguous because it might mean vertex count rather than the number of hyperedge parts. E.g., `{{1, 2, 3}, {3, 4, 5}}` has 5 vertices but 6 hyperedge parts.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 10 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHndti4c1ez-p6wvI1:-MLHndti4c1ez-p6wvI2:b-f0l6w9) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L10)):*
> ```Markdown
> 
> ```wl
> In[]:= SeedRandom[123];
> ```

I don't think we need to specify the seed here (since these are not tests, and it would not affect understandability).
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 10 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHsPu_8GGhARl9zjP6:-MLHsPu_8GGhARl9zjP7:bdnn9is) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L10)):*
> ```Markdown
> 
> ```wl
> In[]:= SeedRandom[123];
> ```

The convention everywhere else in the docs is that there is a space in `In[] :=` and `Out[] =`.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 14 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHnqCh-zWujmTLKsce:-MLHnqCh-zWujmTLKscf:b-gxuwny) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L14)):*
> ```Markdown
> Total[Length /@ hg]
> 
> Out[]= {{4, 7, 4}, {4}, {8}, {4}, {2}, {5}}
> ```

I think it might be cleaner to rearrange it as In/Out pairs, and add `In[]:=` to each line, i.e.,
```wl
In[] := RandomHypergraph[8]
Out[] = {{4, 7, 4}, {4}, {8}, {4}, {2}, {5}}
```
```wl
In[] := Total[Length /@ %]
Out[] = 8
```
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 21 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHodu0BRuhl5O7Ezgh:-MLHodu0BRuhl5O7Ezgi:bt8lj5m) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L21)):*
> ```Markdown
> ```wl
> In[]:= RandomHypergraph[{10, {5, 2}}]
> Out[]= {{4, 1}, {8, 4}, {2, 5}, {6, 10}, {10, 5}}
> ```

Do you think it would make sense to do an `IndexHypergraph` before returning?
___
*[Kernel/RandomHypergraph.m, line 32 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHp9IT5YBA4sY-F8bH:-MLHp9IT5YBA4sY-F8bI:b-u7w9f5) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L32)):*
> ```objc
> (* Error messages *)
> RandomHypergraph::invalidEnum = "The argument at position 1 in `1` should be a non-negative integer or \
> a list of positive integer and a signature(s).";
> ```

... a list of ***a*** positive integer ...
___
*[Kernel/RandomHypergraph.m, line 32 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHpQULAl6iG_3YL5_I:-MLHpQULAl6iG_3YL5_J:b1gzbpa) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L32)):*
> ```objc
> (* Error messages *)
> RandomHypergraph::invalidEnum = "The argument at position 1 in `1` should be a non-negative integer or \
> a list of positive integer and a signature(s).";
> ```

The convention in, e.g., `WolframModelRuleValue` is to call it *signature* (singular) even if there are multiple arities.
___
*[Kernel/RandomHypergraph.m, line 38 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHpyyv0IfJUJgEBf6E:-MLHpyyv0IfJUJgEBf6F:b-tdvh2f) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L38)):*
> ```objc
> Out[]= {{4, 4, 3}, {2, 7}, {5, 6}, {8}}
> *)
> randomHypergraph[enum_Integer ? NonNegative] :=
> ```

Why do you call it `enum`? What does it enumerate?
___
*[Kernel/RandomHypergraph.m, line 39 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHk6sb-C7Ix30ovtMy:-MLHk6sb-C7Ix30ovtMz:b-r3tb39) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L39)):*
> ```objc
> *)
> randomHypergraph[enum_Integer ? NonNegative] :=
>   RandomInteger[{1, enum}, #] & /@ RandomChoice[IntegerPartitions[enum]]
> ```

This has essentially exponential complexity. It would be better to come up with a way to choose arities without enumerating all of them. Given that we don't expect it to sample uniformly anyway, it shouldn't be too hard to do that.
___
*[Kernel/RandomHypergraph.m, line 42 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHlXn121BNAKYeJbs1:-MLHlXn121BNAKYeJbs2:b-hhl7sc) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L42)):*
> ```objc
> 
> (*
> In[]:= RandomHypergraph[{10, {5, 2}}]
> ```

Do you think it will be better to split this argument into two?

```wl
RandomHypergraph[{5, {3, 3}}] -> RandomHypergraph[{3, 3}, 5]
```

We can then also make the second argument optional and default to the maximum possible number of atoms for the given signature (i.e., `Total[Times @@ #] &`).
___
*[Kernel/RandomHypergraph.m, line 53 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHqR8yDxtiIXL69Gw9:-MLHqR8yDxtiIXL69GwA:b-r92p6q) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L53)):*
> ```objc
> *)
> randomHypergraph[{n_Integer ? Positive, sig : {{_Integer ? NonNegative, _Integer ? NonNegative} ..}}] :=
>  Catenate[RandomInteger[{1, n}, #] & /@ sig]
> ```

Nit: Why not call the previous function here?
___
*[Tests/RandomHypergraph.wlt, line 46 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHqvtL03YXva5ieeKL:-MLHqvtM7JCXPvfNBgbv:b-gsemfh) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Tests/RandomHypergraph.wlt#L46)):*
> ```Mathematica
>       VerificationTest[
>         SeedRandom[123]; RandomHypergraph[8],
>         {{5, 6, 3}, {5, 1}, {2, 2}, {5}}
> ```

I'm not sure we should require the seed to be stable between versions. I would instead just generate a hundred of them and check that all the expected constraints are satisfied (and that they are not all the same).

Same for the tests below.


<!-- Sent from Reviewable.io -->

2020-11-06 05:48 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 7 at r1](https://reviewable.io/reviews/maxitg/setreplace/511#-MLC0RN-6Hm4HBWfSFYM:-MLR48sl-p7ipwlwo6p8:bsm1u8g) ([raw file](https://github.com/maxitg/setreplace/blob/5dc1872051b25355386b3153f9c54a8c6427e9b1/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L7)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It doesn't hurt to explain more if it's confusing, but isn't "hyperedge part" exactly the right term? Since it's literally, `Part[{a, b, c}, 2]`. Hyperedge vertex is ambiguous because it might mean vertex count rather than the number of hyperedge parts. E.g., `{{1, 2, 3}, {3, 4, 5}}` has 5 vertices but 6 hyperedge parts.
</blockquote></details>

Let me know if it is clearer. I used "arities" instead.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 10 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHndti4c1ez-p6wvI1:-MLR47zE4JMN5xppOpA9:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L10)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't think we need to specify the seed here (since these are not tests, and it would not affect understandability).
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 10 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHsPu_8GGhARl9zjP6:-MLR4XdVA_q0ujg-tnaB:b-z2ouw2) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L10)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The convention everywhere else in the docs is that there is a space in `In[] :=` and `Out[] =`.
</blockquote></details>

Then I will have to change some documentation already merged. Done.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 14 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHnqCh-zWujmTLKsce:-MLR479J-42ekdXoLik5:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L14)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think it might be cleaner to rearrange it as In/Out pairs, and add `In[]:=` to each line, i.e.,
```wl
In[] := RandomHypergraph[8]
Out[] = {{4, 7, 4}, {4}, {8}, {4}, {2}, {5}}
```
```wl
In[] := Total[Length /@ %]
Out[] = 8
```
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 21 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHodu0BRuhl5O7Ezgh:-MLR4Ik76aqzg1wm_IGW:b-rr5ftr) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L21)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Do you think it would make sense to do an `IndexHypergraph` before returning?
</blockquote></details>

I don't think so, specially since there is now a second argument specifying the maximum number of distinct vertices.
___
*[Kernel/RandomHypergraph.m, line 32 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHp9IT5YBA4sY-F8bH:-MLR4e_h-FubPXcVLxB6:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L32)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

... a list of ***a*** positive integer ...
</blockquote></details>

Done.
___
*[Kernel/RandomHypergraph.m, line 32 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHpQULAl6iG_3YL5_I:-MLR4fG11eekEBE09a3Q:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L32)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The convention in, e.g., `WolframModelRuleValue` is to call it *signature* (singular) even if there are multiple arities.
</blockquote></details>

Done.
___
*[Kernel/RandomHypergraph.m, line 38 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHpyyv0IfJUJgEBf6E:-MLR4g3x0HF8NSAhz7OS:bfxob20) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L38)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Why do you call it `enum`? What does it enumerate?
</blockquote></details>

Changed it to `col` for complexity.
___
*[Kernel/RandomHypergraph.m, line 39 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHk6sb-C7Ix30ovtMy:-MLR4k0W0aLE0-5s9IcB:bcmksiy) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L39)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This has essentially exponential complexity. It would be better to come up with a way to choose arities without enumerating all of them. Given that we don't expect it to sample uniformly anyway, it shouldn't be too hard to do that.
</blockquote></details>

I found a way. There is also `RandomPartition` from the `Combinatorica` package.
___
*[Kernel/RandomHypergraph.m, line 42 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHlXn121BNAKYeJbs1:-MLR5-B26ritZOZrLY_G:bx98sdo) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L42)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Do you think it will be better to split this argument into two?

```wl
RandomHypergraph[{5, {3, 3}}] -> RandomHypergraph[{3, 3}, 5]
```

We can then also make the second argument optional and default to the maximum possible number of atoms for the given signature (i.e., `Total[Times @@ #] &`).
</blockquote></details>

I liked the idea!
___
*[Tests/RandomHypergraph.wlt, line 46 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHqvtL03YXva5ieeKL:-MLR5D6j6vEY6RzyJh1e:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Tests/RandomHypergraph.wlt#L46)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I'm not sure we should require the seed to be stable between versions. I would instead just generate a hundred of them and check that all the expected constraints are satisfied (and that they are not all the same).

Same for the tests below.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-06 16:55 UTC, maxitg requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: all files reviewed, 8 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 5 at r4](https://reviewable.io/reviews/maxitg/setreplace/511#-MLTJxl8Cskf9tFyAxjV:-MLTJxl98_Q6H1ljUWNv:b-ranp77) ([raw file](https://github.com/maxitg/setreplace/blob/4b764f5117c642ad5050467092a53c3a50e3e4ac/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L5)):*
> ```Markdown
> # RandomHypergraph
> 
> **`RandomHypergraph`** generates a random hypergraph. The first argument is the condition for generating the hypergraph. The second (optional) argument is the maximum possible number of distinct vertices of said hypergraph.
> ```

I don't think "condition" is the right word. It sounds like it's a condition that could fail in which case the hypergraph would not be generated at all. I suggest we say either that it specifies the hypergraph "structure", or mention the two cases separately.
___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 41 at r4](https://reviewable.io/reviews/maxitg/setreplace/511#-MLTLfA60iWGQ9o0dbsO:-MLTLfA60iWGQ9o0dbsP:bwabx65) ([raw file](https://github.com/maxitg/setreplace/blob/4b764f5117c642ad5050467092a53c3a50e3e4ac/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L41)):*
> ```Markdown
> In[] := RandomHypergraph[{{5, 2}, {4, 3}}, 2]
> Out[] = {{1, 1}, {1, 2}, {1, 2}, {2, 1}, {2, 1}, {2, 2, 2}, {1, 1, 2}, {1, 1, 2}, {1, 1, 1}}
> ```
> ```

Nit: Add an empty line.
___
*[Kernel/RandomHypergraph.m, line 38 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHpyyv0IfJUJgEBf6E:-MLTOoP4BNBe8NEKvUNF:b1rne5a) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L38)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Changed it to `col` for complexity.
</blockquote></details>

I would never have guessed that `col` is complexity? Why not just call it `complexity`?
___
*[Kernel/RandomHypergraph.m, line 39 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHk6sb-C7Ix30ovtMy:-MLTPAgj4_biCKjmPbrb:b-sc2mam) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L39)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

I found a way. There is also `RandomPartition` from the `Combinatorica` package.
</blockquote></details>

Nice!

<img src="https://files.reviewableusercontent.io/images/reviewable/1479325/DbmqyR2EwwMZbHBfsa71XmO_/image.png" width="400">
___
*[Kernel/RandomHypergraph.m, line 47 at r4](https://reviewable.io/reviews/maxitg/setreplace/511#-MLTR0UvBJpxhXa7FdDu:-MLTR0UvBJpxhXa7FdDv:b-wxh88i) ([raw file](https://github.com/maxitg/setreplace/blob/4b764f5117c642ad5050467092a53c3a50e3e4ac/Kernel/RandomHypergraph.m#L47)):*
> ```objc
> Out[]= {{4, 4, 3}, {2, 7}, {5, 6}, {8}}
> *)
> randomHypergraph[call_, col_Integer ? Positive, n : (_Integer ? Positive | Automatic)] :=
> ```

`call` -> `caller` (use full variable names).
___
*[Tests/RandomHypergraph.wlt, line 46 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHqvtL03YXva5ieeKL:-MLTRrxd5dsVHZDDUm_I:bs58vh2) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Tests/RandomHypergraph.wlt#L46)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Two problems here:
1. We need to specify a seed in the beginning to make the tests reproducible. (The tests should pass for any seed, but if they fail, we want to be able to run them again and get the same result.)
2. The `RandomHypergraph` computation here happens outside of `VerificationTest`, which means the error message would not make any sense, and the tests would not be parallelized. It's better to put `VerificationTest` inside the table and compute `RandomGraph` within.
___
*[Tests/RandomHypergraph.wlt, line 118 at r4](https://reviewable.io/reviews/maxitg/setreplace/511#-MLTTfLP5RvMhbCSZj6_:-MLTTfLQ-hAvvmlYNmxf:b-hxdxep) ([raw file](https://github.com/maxitg/setreplace/blob/4b764f5117c642ad5050467092a53c3a50e3e4ac/Tests/RandomHypergraph.wlt#L118)):*
> ```Mathematica
>           (* All generated hypergraphs should not be the same *)
>           VerificationTest[Length[Tally[Map[Sort, random1, {1, 2}]]] > 1, True],
>           VerificationTest[Length[Tally[Map[Sort, random2, {1, 2}]]] > 1, True],
> ```

This needs some refactoring so that the same code is not duplicated 6 times.


<!-- Sent from Reviewable.io -->

2020-11-06 18:30 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md, line 5 at r4](https://reviewable.io/reviews/maxitg/setreplace/511#-MLTJxl8Cskf9tFyAxjV:-MLToVoM9xI1czzWUS27:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4b764f5117c642ad5050467092a53c3a50e3e4ac/Documentation/SymbolsAndFunctions/UtilityFunctions/RandomHypergraph.md#L5)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't think "condition" is the right word. It sounds like it's a condition that could fail in which case the hypergraph would not be generated at all. I suggest we say either that it specifies the hypergraph "structure", or mention the two cases separately.
</blockquote></details>

Done.
___
*[Kernel/RandomHypergraph.m, line 38 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHpyyv0IfJUJgEBf6E:-MLToU6A0dJaE_O9zQEO:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L38)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I would never have guessed that `col` is complexity? Why not just call it `complexity`?
</blockquote></details>

Done.
___
*[Kernel/RandomHypergraph.m, line 39 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHk6sb-C7Ix30ovtMy:-MLToX5p22ymoYtn6NWB:bb70t73) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Kernel/RandomHypergraph.m#L39)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Nice!

<img src="https://files.reviewableusercontent.io/images/reviewable/1479325/DbmqyR2EwwMZbHBfsa71XmO_/image.png" width="400">
</blockquote></details>

Neat
___
*[Kernel/RandomHypergraph.m, line 47 at r4](https://reviewable.io/reviews/maxitg/setreplace/511#-MLTR0UvBJpxhXa7FdDu:-MLToUJGBqvh84vROSRI:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4b764f5117c642ad5050467092a53c3a50e3e4ac/Kernel/RandomHypergraph.m#L47)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`call` -> `caller` (use full variable names).
</blockquote></details>

Done.
___
*[Tests/RandomHypergraph.wlt, line 46 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHqvtL03YXva5ieeKL:-MLTo_1_1M6G-GGns_nv:bpd2huh) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Tests/RandomHypergraph.wlt#L46)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Two problems here:
1. We need to specify a seed in the beginning to make the tests reproducible. (The tests should pass for any seed, but if they fail, we want to be able to run them again and get the same result.)
2. The `RandomHypergraph` computation here happens outside of `VerificationTest`, which means the error message would not make any sense, and the tests would not be parallelized. It's better to put `VerificationTest` inside the table and compute `RandomGraph` within.
</blockquote></details>

I put `Table` inside `VerificationTest`. Let me know what you think.
___
*[Tests/RandomHypergraph.wlt, line 118 at r4](https://reviewable.io/reviews/maxitg/setreplace/511#-MLTTfLP5RvMhbCSZj6_:-MLTofr0CEp_95IowG2z:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4b764f5117c642ad5050467092a53c3a50e3e4ac/Tests/RandomHypergraph.wlt#L118)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This needs some refactoring so that the same code is not duplicated 6 times.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-08 03:17 UTC, maxitg requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: all files reviewed, 4 unresolved discussions (waiting on @daneelsan and @taliesinb)

___
*[Tests/RandomHypergraph.wlt, line 46 at r2](https://reviewable.io/reviews/maxitg/setreplace/511#-MLHqvtL03YXva5ieeKL:-ML_ql105uAu488jXd7f:b-qn5lbb) ([raw file](https://github.com/maxitg/setreplace/blob/345fc806f561ce3b3d5e37629eadd4c9a61169f0/Tests/RandomHypergraph.wlt#L46)):*
<details><summary><i>Previously, daneelsan (Daniel Sanchez) wrote…</i></summary><blockquote>

I put `Table` inside `VerificationTest`. Let me know what you think.
</blockquote></details>

Perfect!
___
*[Tests/RandomHypergraph.wlt, line 10 at r5](https://reviewable.io/reviews/maxitg/setreplace/511#-ML_pQJ-16HoPSlmtW7i:-ML_pQJ-16HoPSlmtW7j:baseba9) ([raw file](https://github.com/maxitg/setreplace/blob/7db6e9c827fa5d4a035f473a04f4048549142846/Tests/RandomHypergraph.wlt#L10)):*
> ```Mathematica
>       validVertexRangeQ[range_, hypergraph_] := SubsetQ[range, Flatten @ hypergraph];
> 
>       seed = 123;
> ```

This seed variable is not used anywhere.
___
*[Tests/RandomHypergraph.wlt, line 70 at r5](https://reviewable.io/reviews/maxitg/setreplace/511#-ML_pbK24oh2NyKpAxIj:-ML_pbK24oh2NyKpAxIk:b66mzg1) ([raw file](https://github.com/maxitg/setreplace/blob/7db6e9c827fa5d4a035f473a04f4048549142846/Tests/RandomHypergraph.wlt#L70)):*
> ```Mathematica
>           Table[RandomHypergraph[8], 100],
>           Total[Length /@ #] === 8 &],
>         True
> ```

`VerificationTest` has a one-argument form, where it just checks if the output is `True`, i.e., `VerificationTest[2 === 2]` works.


<!-- Sent from Reviewable.io -->

2020-11-08 03:23 UTC, daneelsan reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @maxitg and @taliesinb)

___
*[Tests/RandomHypergraph.wlt, line 10 at r5](https://reviewable.io/reviews/maxitg/setreplace/511#-ML_pQJ-16HoPSlmtW7i:-ML_sHY7CJh1520tMK5H:b-5c2ydc) ([raw file](https://github.com/maxitg/setreplace/blob/7db6e9c827fa5d4a035f473a04f4048549142846/Tests/RandomHypergraph.wlt#L10)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This seed variable is not used anywhere.
</blockquote></details>

Leftover
___
*[Tests/RandomHypergraph.wlt, line 70 at r5](https://reviewable.io/reviews/maxitg/setreplace/511#-ML_pbK24oh2NyKpAxIj:-ML_sDmMBZVz1B9z06Ds:b7jwele) ([raw file](https://github.com/maxitg/setreplace/blob/7db6e9c827fa5d4a035f473a04f4048549142846/Tests/RandomHypergraph.wlt#L70)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`VerificationTest` has a one-argument form, where it just checks if the output is `True`, i.e., `VerificationTest[2 === 2]` works.
</blockquote></details>

Nice! and done.


<!-- Sent from Reviewable.io -->

2020-11-08 03:28 UTC, maxitg approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: all files reviewed, 2 unresolved discussions (waiting on @taliesinb)



<!-- Sent from Reviewable.io -->

2020-11-08 21:33 UTC, taliesinb commented
I would suggest making the seeding explicit with a RandomSeeding option, which is used widely in Mathematica for exactly this purpose. Take a look at the documentation for an idea of how it should behave.

2020-11-09 03:24 UTC, maxitg approved these changes
It sounds like a good idea, but for a different PR (since it's a new feature and requires adding options handling).

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511#-:-MLf-RoO1uSVd8uB7vUT:by69uxi)* status: all files reviewed, 2 unresolved discussions (waiting on @taliesinb)



<!-- Sent from Reviewable.io -->

2020-11-09 04:46 UTC, daneelsan commented
@taliesinb , as Max said I'll add it in a different PR. There exists an issue about adding the `"Connected" -> True` option (to generate random connected hypergraphs). To do that I'll need option handling and will add the `RandomSeeding` option then.

2020-11-09 10:45 UTC, taliesinb approved these changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/511)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-09 15:11 UTC, merged