Feature association
maxitg/SetReplace pull request #528
Opened 2020-11-13 21:34 UTC by mrektor

## Changes
* Computes features and present them as an association
* Computes graph features about the causal graph and the graph version of the final state (using HypergraphToGraph with StructurePreserving method)
* Changed Feature Vector as Flatten @ Values @ #["FeatureAssociation"]

## Comments
* Some functions could have a more elegant implementation...

## Examples
```wl
In[] := WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, 5]["FeatureAssociation"]
Out[] = <| "CausalGraphVertexCount" -> 22, "CausalGraphEdgeCount" -> 42, 
 "CausalGraphVertexConnectivity" -> 1, 
 "CausalGraphVertexDegreesQuantiles" -> {2, 2, 2, 6, 6}, 
 "StructurePreservingFinalStateVertexCount" -> 115, 
 "StructurePreservingFinalStateEdgeCount" -> 138, 
 "StructurePreservingFinalStateVertexConnectivity" -> 2, 
 "StructurePreservingFinalStateVertexDegreesQuantiles" -> {2, 2, 2, 2, 8} |>
```

2020-11-16 18:23 UTC, maxitg commented
We need to compute the evolution objects *within* the `VerificationTest`. The output from the failed tests is way too large and makes it very hard to understand what's going on.

2020-11-17 16:13 UTC, mrektor commented
I think that what's "failing" are the error messages checks (testUnevaluated)

![image](https://user-images.githubusercontent.com/26904650/99415505-27395000-28f8-11eb-883d-1999f5acf395.png)

2020-11-24 02:48 UTC, maxitg commented
> I think that what's "failing" are the error messages checks (testUnevaluated)

I think it's because the `WolframModel` has evaluated into `WolframModelEvolutionObject`, and `testUnevaluated` expects the input to remain completely unevaluated. A solution would be to generate the evolution object before the test or pass the property to `WolframModel` directly.

2020-12-03 20:49 UTC, maxitg commented
That does not fix the tests, that skips them. You just evaluated the argument of `testUnevaluated` before it even gets into the test, so of course the test passes because there is nothing left to evaluate.

It does, however, produce messages while pre-evaluating it which is why CI fails (it does not allow messages).

2020-12-04 03:14 UTC, daneelsan commented
If:
1. the attribute of `testUnevaluated` in the `.wlt` file is set to `HoldAllComplete`
2. `Evaluate` is replaced with `With`
, then the tests pass:

```
      Attributes[Global`testUnevaluated] = Attributes[Global`testSymbolLeak] = {HoldAllComplete};
```
```
          (* Error Messages check *)
          With[{obj = evolutionObjects[[3]]}, {
            testUnevaluated[obj["FeatureAssociation", 3], {WolframModelEvolutionObject::invalidFeatureSpec}],
            testUnevaluated[obj["FeatureAssociation", "EasterEgg"], {WolframModelEvolutionObject::unknownFeatureGroup}]
          }]
```

![image](https://user-images.githubusercontent.com/40190339/101117434-f07c5e80-35b4-11eb-83c6-5020ae11dce7.png)

2020-12-05 00:38 UTC, maxitg requested changes
Remove the paclet files from the commit. Due to recent changes to the build system, `.gitignore` no longer expects them in the repository root.

> Reviewed 2 of 6 files at r1, 1 of 2 files at r3, 4 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528#-:-MNjAq3L8RapJ8z78HNZ:bz80dgk)* status: all files reviewed, 38 unresolved discussions (waiting on @maxitg and @mrektor)

___
*[README.md, line 166 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjC1Xa8DmGw5bwBwG3:-MNjC1Xb9yCKIFowDiOY:bfh939o) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/README.md#L166)):*
> ```Markdown
>     - [Total Element Counts](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/TotalElementCounts.md)
>     - [Rules](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/Rules.md)
>     - [Feature Association](Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md)
> ```

Add this link to the `WolframModel` documentation page as well.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2gSB43UqX-YZjI0Od:-MM2gSB43UqX-YZjI0Oe:b-u60rto) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L9)):*
> ```Markdown
> ```wl
> In[] := WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, 5]["FeatureAssociation"]
> Out[] = <| "CausalGraphVertexCount" -> 22, "CausalGraphEdgeCount" -> 42, 
> ```

I suggest we format this to have one property per line, as:

```wl
Out[] = <|
  "CausalGraphVertexCount" -> 22,
  "CausalGraphEdgeCount" -> 42,
  "CausalGraphVertexConnectivity" -> 1,
  "CausalGraphVertexDegreesQuantiles" -> {2, 2, 2, 6, 6},
  "StructurePreservingFinalStateVertexCount" -> 115,
  "StructurePreservingFinalStateEdgeCount" -> 138,
  "StructurePreservingFinalStateVertexConnectivity" -> 2,
  "StructurePreservingFinalStateVertexDegreesQuantiles" -> {2, 2, 2, 2, 8}|>
```
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 3 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjC8VE-YznHgnxVLYB:-MNjC8VE-YznHgnxVLYC:b-mcmg1i) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L3)):*
> ```Markdown
> ###### [Symbols and Functions](/README.md#symbols-and-functions) > [WolframModel and WolframModelEvolutionObject](../WolframModelAndWolframModelEvolutionObject.md) > [Properties](../WolframModelAndWolframModelEvolutionObject.md#properties) >
> 
> # FeatureAssociation
> ```

The name should be consistent with the link name. Add a space in between "Feature" and "Association".
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 5 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjE_dn6lNO5zKkewfj:-MNjE_dn6lNO5zKkewfk:b9oxu9z) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L5)):*
> ```Markdown
> # FeatureAssociation
> 
> **`"FeatureAssociation"`** computes some features about the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution and returns an association whose keys describe each feature computed. For now, it computes properties associated with these feature groups:
> ```

some features ***of*** the WolframModel
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 5 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjEjmM7qC9Kjw3Ij3U:-MNjEjmM7qC9Kjw3Ij3V:b-shzihy) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L5)):*
> ```Markdown
> # FeatureAssociation
> 
> **`"FeatureAssociation"`** computes some features about the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution and returns an association whose keys describe each feature computed. For now, it computes properties associated with these feature groups:
> ```

association should be formatted as code and link to WL documentation.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 6 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjkwbyAwuYwJe6hEA7:-MNjkwbz-_zBxfCx1LBD:b-gisb1w) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L6)):*
> ```Markdown
> 
> **`"FeatureAssociation"`** computes some features about the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution and returns an association whose keys describe each feature computed. For now, it computes properties associated with these feature groups:
> - `"CausalGraph"`: [`CausalGraph`](LINK)
> ```

The link is missing.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 6 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjvKRf9OdGWJIACLRW:-MNjvKRf9OdGWJIACLRX:br1ipa1) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L6)):*
> ```Markdown
> 
> **`"FeatureAssociation"`** computes some features about the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution and returns an association whose keys describe each feature computed. For now, it computes properties associated with these feature groups:
> - `"CausalGraph"`: [`CausalGraph`](LINK)
> ```

I don't think it helps to put anything to the right of the colon if it's just the same thing with a link. I suggest just putting the link on `"CausalGraph"` to the left of the colon instead.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 7 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjlK2k1UL93_royGAA:-MNjlK2k1UL93_royGAB:b-y1sb6i) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L7)):*
> ```Markdown
> **`"FeatureAssociation"`** computes some features about the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md) evolution and returns an association whose keys describe each feature computed. For now, it computes properties associated with these feature groups:
> - `"CausalGraph"`: [`CausalGraph`](LINK)
> - `"StructurePreservingFinalState"`: The graph version of the [`FinalState`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/States.md) as given by [`HypergraphToGraph`](/Documentation/Symbols [...]

2020-12-08 02:07 UTC, maxitg reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 37 unresolved discussions (waiting on @mrektor)

___
*[Tests/WolframModelEvolutionObject.wlt, line 1905 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNkCovv8hUVGeyblP-I:-MO-5Mu44wGiRA6O42CO:b-i74mdg) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Tests/WolframModelEvolutionObject.wlt#L1905)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Also, test an empty list for the feature group spec. The test will actually fail right now because it will interpret `{}` as an empty list of options. I'm going to implement a fix in a separate PR (most likely early next week).
</blockquote></details>

Done in #553.


<!-- Sent from Reviewable.io -->

2020-12-11 21:16 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: 1 of 7 files reviewed, 37 unresolved discussions (waiting on @maxitg and @mrektor)

___
*[README.md, line 166 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjC1Xa8DmGw5bwBwG3:-MNtHETA0vuUdJgcAm7d:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/README.md#L166)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Add this link to the `WolframModel` documentation page as well.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2gSB43UqX-YZjI0Od:-MOCSkwp7vt2dE0nsG6b:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L9)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I suggest we format this to have one property per line, as:

```wl
Out[] = <|
  "CausalGraphVertexCount" -> 22,
  "CausalGraphEdgeCount" -> 42,
  "CausalGraphVertexConnectivity" -> 1,
  "CausalGraphVertexDegreesQuantiles" -> {2, 2, 2, 6, 6},
  "StructurePreservingFinalStateVertexCount" -> 115,
  "StructurePreservingFinalStateEdgeCount" -> 138,
  "StructurePreservingFinalStateVertexConnectivity" -> 2,
  "StructurePreservingFinalStateVertexDegreesQuantiles" -> {2, 2, 2, 2, 8}|>
```
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 3 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjC8VE-YznHgnxVLYB:-MNtK6D8BkETpvH4k-HB:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L3)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The name should be consistent with the link name. Add a space in between "Feature" and "Association".
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 5 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjE_dn6lNO5zKkewfj:-MNtK6Wv9ztt5gCWSV-m:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L5)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

some features ***of*** the WolframModel
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 5 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjEjmM7qC9Kjw3Ij3U:-MNtKTeF2ZBVZKlnBxOQ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L5)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

association should be formatted as code and link to WL documentation.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 6 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjkwbyAwuYwJe6hEA7:-MOCRcQf2qxaccClnh6Z:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The link is missing.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 6 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjvKRf9OdGWJIACLRW:-MOCRr8hEZCcRjJa_UNr:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't think it helps to put anything to the right of the colon if it's just the same thing with a link. I suggest just putting the link on `"CausalGraph"` to the left of the colon instead.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 7 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjlK2k1UL93_royGAA:-MOCS-8k18yvNUumbPGf:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L7)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I suggest calling this `"StructurePreservingFinalStateGraph"`, as `"StructurePreserving"` does not make much sense without `"Graph"`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 7 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjl_ea--EkLl6DE3Mb:-MOCSCLM2VNB84yjGCl3:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L7)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Graph should be formatted as code and link to WL documentation.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 7 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjvWNa2Vt29ftj0gVU:-MOCSGxo2DkHWg2llNp0:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L7)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`FinalState` should be in quotes: `"FinalState"`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 20 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNk0KnO244o6NUrlphv:-MOCSv5d1pBHUNgm5Cus:b-8je2tb) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L20)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Should we say "the list of features" instead of "the list of properties"?
</blockquote></details>

Yes I think it makes sense
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 21 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjmX505mBrPVw1wzty:-MOCT73XDgtEB1fEawt6:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L21)):*
<details><summary><i>Previousl [...]

2020-12-11 22:27 UTC, maxitg requested changes
> Reviewed 6 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 23 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2gSB43UqX-YZjI0Od:-MOIoNuI-wH6GXkD3m50:bevx2pg) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L9)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove trailing spaces.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 5 at r5](https://reviewable.io/reviews/maxitg/setreplace/528#-MNjEjmM7qC9Kjw3Ij3U:-MOIhWUg8USEJQTZpBEk:b-kz82ha) ([raw file](https://github.com/maxitg/setreplace/blob/9c1e0117ff1baee50e6a8a823225082d9cdbb481/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L5)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Link the actual symbol: https://reference.wolfram.com/language/ref/Association.html, not the guide page (for consistency).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 16 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIiFX_-rabKVPSNquk:-MOIiFX_-rabKVPSNqul:b90sntz) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L16)):*
> ```Markdown
>  "CausalGraphVertexConnectivity" -> 1, 
>  "CausalGraphVertexDegreesQuantiles" -> {2, 2, 2, 6, 6}, 
>  "StructurePreservingFinalStateVertexCount" -> 115, 
> ```

Update the output (so that it has `"StructurePreservingFinalStateGraphVertexCount"`, etc.).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 19 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIoQ8q-FFc9jOck8UJ:-MOIoQ8q-FFc9jOck8UK:b-bsxc6p) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L19)):*
> ```Markdown
>  "StructurePreservingFinalStateEdgeCount" -> 138, 
>  "StructurePreservingFinalStateVertexConnectivity" -> 2, 
>  "StructurePreservingFinalStateVertexDegreesQuantiles" -> {2, 2, 2, 2, 8} |>
> ```

Remove the space before `|>`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIojlM9IRq33XyYxM9:-MOIojlM9IRq33XyYxMA:b-q3x2x7) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
> ```Markdown
> 
> ```wl
> In[] := FeatureSpacePlot[#[\"FeatureAssociation\"] 
> ```

`"` should not be escaped (it should be possible to run the copied code directly), same on the next line.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIovQX8JyE9QvGj-MN:-MOIovQX8JyE9QvGj-MO:bevx2pg) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
> ```Markdown
> 
> ```wl
> In[] := FeatureSpacePlot[#[\"FeatureAssociation\"] 
> ```

Remove trailing spaces.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 32 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIosxLCImmlI82E0ib:-MOIosxLCImmlI82E0ic:b-smrrve) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L32)):*
> ```Markdown
> ```wl
> In[] := FeatureSpacePlot[#[\"FeatureAssociation\"] 
>     \[Rule] #[\"CausalGraph\"] & /@ (WolframModel[{{x, y}, {x, z}} 
> ```

Use `->` instead of `\[Rule]`
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 33 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIh2E91XMzZPsHh0KM:-MOIh2E91XMzZPsHh0KN:b-iwk3x9) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L33)):*
> ```Markdown
> In[] := FeatureSpacePlot[#[\"FeatureAssociation\"] 
>     \[Rule] #[\"CausalGraph\"] & /@ (WolframModel[{{x, y}, {x, z}} 
>        \[Rule] {{x, z}, {x, w}, {y, w}, {z, w}}, #, 6] &) /@ inits]
> ```

`inits` should be defined on this page, there is no way for the reader to find them from the `"FeatureVector"` page.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 38 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIpJv3Ein4lvmKqPht:-MOIpJv3Ein4lvmKqPhu:b-u966z1) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L38)):*
> ```Markdown
> <img src="/Documentation/Images/FeatureAssociationFeatureSpacePlot.png" width=478.2>
> 
> For [`MultiwaySystems`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/MultiwayQ.md) it only computes features associated with the [`CausalGraph"`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md), returning `Missing["NotExistent", {"MultiwaySystem", "FinalState"}]` for features related to `"StructurePreservingFinalState"`, as there is no [`"FinalState"`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/States.md) in a Multiway System:
> ```

What happened to the `""` before `CausalGraph`?
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 38 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIpQXJ11lQBCbcXX06:-MOIpQXJ11lQBCbcXX07:b4vswjg) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L38)):*
> ```Markdown
> <img src="/Documentation/Images/FeatureAssociationFeatureSpacePlot.png" width=478.2>
> 
> For [`MultiwaySystems`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/MultiwayQ.md) it only computes features associated with the [`CausalGraph"`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md), returning `Missing["NotExistent", {"MultiwaySystem", "FinalState"}]` for features related to `"StructurePreservingFinalState"`, as there is no [`"FinalState"`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/States.md) in a Multiway System:
> ```

`"StructurePreservingFinalStateGraph"`
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 42 at r7](https://reviewable.io/reviews/maxitg/setreplace/ [...]

2020-12-21 20:50 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 23 unresolved discussions (waiting on @maxitg and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 16 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIiFX_-rabKVPSNquk:-MOXAaGz4xsH085gr1Mz:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L16)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Update the output (so that it has `"StructurePreservingFinalStateGraphVertexCount"`, etc.).
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 19 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIoQ8q-FFc9jOck8UJ:-MOXAaimBPuxQhYVb-VC:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L19)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove the space before `|>`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIojlM9IRq33XyYxM9:-MOXAx0rCoZ51EnQrsiL:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`"` should not be escaped (it should be possible to run the copied code directly), same on the next line.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIovQX8JyE9QvGj-MN:-MOXAzBiBCheWYOE6Yag:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove trailing spaces.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 32 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIosxLCImmlI82E0ib:-MOXB3S69FhGR5bex6gA:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L32)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use `->` instead of `\[Rule]`
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 33 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIh2E91XMzZPsHh0KM:-MOXBHmd5OBX8oT5440Z:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L33)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`inits` should be defined on this page, there is no way for the reader to find them from the `"FeatureVector"` page.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 38 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIpJv3Ein4lvmKqPht:-MOXBcOg01amIVrk7Pei:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L38)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

What happened to the `""` before `CausalGraph`?
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 38 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIpQXJ11lQBCbcXX06:-MOXBgSm9lg9MMcbIc_U:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L38)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`"StructurePreservingFinalStateGraph"`
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 42 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIpnZA-dZ9hin0qQXl:-MP5zKAZ8eOPtnvxaob3:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L42)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

All function arguments should be indented the same amount and be on separate lines. I.e., either

```wl
In[] := WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}},
                     {{1, 1}, {1, 0}, {1, 1}},
                     3,
                     "EventSelectionFunction" -> "MultiwaySpacelike"]["FeatureAssociation"]
```

or

```wl
In[] := WolframModel[
  {{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}},
  {{1, 1}, {1, 0}, {1, 1}},
  3,
  "EventSelectionFunction" -> "MultiwaySpacelike"]["FeatureAssociation"]
```
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 45 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIqQhQ2QSRPtxb563G:-MP6-SDPEsOdxD_o-9lT:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L45)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

These should be indented two spaces.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 49 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIiMdd2yiW1cEa8EaD:-MP60Ewu9rQl1ZoLif_R:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L49)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Update the output (`"StructurePreservingFinalStateGraphVertexCount"`).
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 53 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIqVn1AyCanE20_ZX7:-MP60JIU5mNBj-Sy686n:bt604ky) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L53 [...]

2020-12-28 16:44 UTC, maxitg requested changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 6 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2gSB43UqX-YZjI0Od:-MPe60Y42NiwnLVUMBlS:bsk3lq5) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L9)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove trailing spaces.
</blockquote></details>

Including after `<|` on this line.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 38 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIpJv3Ein4lvmKqPht:-MPe79WkBef6uHhX-72m:bt34h15) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L38)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If `"CausalGraph"` is used as a property name, it should not have a space. If it is used as ordinary text, it should not be formatted as code, should not have quotes, and should not be capitalized.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 45 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIqQhQ2QSRPtxb563G:-MPe7dng9fgN7ntFXLRe:b-e3t6r) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L45)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What you added are tabs, not spaces (please look at the changes on Reviewable before replying, it shows whitespace characters).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 53 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIqVn1AyCanE20_ZX7:-MPe8kVf4qcKvVc9YrXo:bkm2iwg) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L53)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I did set the tab to two spaces, now it should be ok
</blockquote></details>

You need to set your editor to emit spaces instead of tabs (they are different characters):

```wl
In[] := ToCharacterCode[" \t"]
Out[] = {32, 9}
```
___
*[Kernel/WolframModelEvolutionObject.m, line 938 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIsQiqCgIaZBHUVwEA:-MPeClKuDzm23i8KkTPk:b-j1obes) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Kernel/WolframModelEvolutionObject.m#L938)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I'm sorry I do not understand what I should do in this case
</blockquote></details>

The first argument of `Replace` is on the first line, and the other two are on the next line, furthermore, the arguments start at different horizontal positions. Here is a way to fix it (also putting the comma in `If` on a separate line making it obvious there is an else):

```wl
    "StructurePreservingFinalStateGraph" -> If[!propertyEvaluate[True, boundary][obj, caller, "MultiwayQ"],
      graphFeatureAssociation @ HypergraphToGraph[#, "StructurePreserving"] & @
        propertyEvaluate[True, boundary][obj, caller, "FinalState"]
    ,
      Replace[
        graphFeatureAssociation[Graph[{1 -> 2}]],
        {_ ? NumberQ -> Missing["NotExistent", {"MultiwaySystem", "FinalState"}]},
        Infinity]
    ],
```


<!-- Sent from Reviewable.io -->

2020-12-30 10:41 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 6 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 9 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2gSB43UqX-YZjI0Od:-MPnBjDgBriXqOQkrOGM:b-8vtl2r) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L9)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Including after `<|` on this line.
</blockquote></details>

sorry I missed that
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 45 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIqQhQ2QSRPtxb563G:-MPnCQcV-aPRX3kdEVS_:b-3w8ac1) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L45)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

What you added are tabs, not spaces (please look at the changes on Reviewable before replying, it shows whitespace characters).
</blockquote></details>

Oh sorry I didn't know about that. Now I set on Sublime the indentation as two whitespaces... hopefully won't make this mistake again.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 53 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIqVn1AyCanE20_ZX7:-MPnCjvvDJ4oaVP-_ELr:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L53)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

You need to set your editor to emit spaces instead of tabs (they are different characters):

```wl
In[] := ToCharacterCode[" \t"]
Out[] = {32, 9}
```
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 26 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2f9CY9ApFSNtrSVb4:-MPnCrcZDXbaINctQm29:btg93hd) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L26)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The picture needs to be updated for the new properties.

However, I think we need a new example because most of the cases here don't even run for one event:

```wl
In[] := FeatureSpacePlot[#["FeatureVector"] -> #[
     "EventsCount"] & /@ (WolframModel[{{x, y}, {x, z}} -> {{x, 
         z}, {x, w}, {y, w}, {z, w}}, #, 6] &) /@ inits]
```

![image.png](https://files.reviewableusercontent.io/images/reviewable/1479325/E5wE1rnrz_nPdDyF3h8XzdeP/image.png)
</blockquote></details>

Shall we update with a more sensible example in the next release of the function? where we use EvolutionObject properties and the new FeatureExtraction for the graph feature groups?
___
*[Kernel/WolframModelEvolutionObject.m, line 938 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIsQiqCgIaZBHUVwEA:-MPnECim8Bw5RapMRFA5:b-6cflco) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Kernel/WolframModelEvolutionObject.m#L938)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The first argument of `Replace` is on the first line, and the other two are on the next line, furthermore, the arguments start at different horizontal positions. Here is a way to fix it (also putting the comma in `If` on a separate line making it obvious there is an else):

```wl
    "StructurePreservingFinalStateGraph" -> If[!propertyEvaluate[True, boundary][obj, caller, "MultiwayQ"],
      graphFeatureAssociation @ HypergraphToGraph[#, "StructurePreserving"] & @
        propertyEvaluate[True, boundary][obj, caller, "FinalState"]
    ,
      Replace[
        graphFeatureAssociation[Graph[{1 -> 2}]],
        {_ ? NumberQ -> Missing["NotExistent", {"MultiwaySystem", "FinalState"}]},
        Infinity]
    ],
```
</blockquote></details>

ok thanks


<!-- Sent from Reviewable.io -->

2020-12-30 15:26 UTC, maxitg requested changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 3 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 38 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIpJv3Ein4lvmKqPht:-MPoDEVE3pS7zrRg2LGE:b-yeh474) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L38)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

If `"CausalGraph"` is used as a property name, it should not have a space. If it is used as ordinary text, it should not be formatted as code, should not have quotes, and should not be capitalized.
</blockquote></details>

Using ` `` ` makes it formatted as code. The same is true for "Multiway Systems" before (I did not notice last time). However, since it's not code (it's not a name of any property/symbol like other links), there is no reason to format it like code, so it should simply be `[causal graph](url)` and `[Multiway Systems](url)`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 26 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2f9CY9ApFSNtrSVb4:-MPoETF288S4x8iUeqi-:b-gx0xmy) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L26)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Shall we update with a more sensible example in the next release of the function? where we use EvolutionObject properties and the new FeatureExtraction for the graph feature groups?
</blockquote></details>

Sure. However, we still need to update the picture in the meantime, because it's currently inconsistent with the input.
___
*[Kernel/WolframModelEvolutionObject.m, line 938 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MOIsQiqCgIaZBHUVwEA:-MPoEgHrAPzufOWaLNhc:bsk0xzv) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Kernel/WolframModelEvolutionObject.m#L938)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

ok thanks
</blockquote></details>

The first argument in `Replace` (`graphFeatureAssociation[...]`) should start at the same horizontal position as well (i.e., it should be on the next line).


<!-- Sent from Reviewable.io -->

2021-01-26 15:53 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 26 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2f9CY9ApFSNtrSVb4:-MRzMti71c9X94qp9Vvo:btzhk1v) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L26)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Sure. However, we still need to update the picture in the meantime, because it's currently inconsistent with the input.
</blockquote></details>

I changed it, I think the new example is pretty (even though maybe not super useful, but at least it should be informative)


<!-- Sent from Reviewable.io -->

2021-01-26 18:55 UTC, maxitg requested changes
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 2 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r10](https://reviewable.io/reviews/maxitg/setreplace/528#-MS-25MF9sR_SIiIseMz:-MS-25MF9sR_SIiIseN-:bt6mwnq) ([raw file](https://github.com/maxitg/setreplace/blob/894a40ac616cf9f1f81636c51ff684a870be1077/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
> ```Markdown
> 
> ```wl
> In[] := SeedRandom[2];
> ```

I'd suggest to use `BlockRandom` here instead with the `RandomSeeding` option (so that everything can be copied as a single expression).
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 26 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2f9CY9ApFSNtrSVb4:-MS-0P2P5f9OrqZqMT6s:br6v7kf) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L26)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I changed it, I think the new example is pretty (even though maybe not super useful, but at least it should be informative)
</blockquote></details>

I think the new example is very nice! But you need to use it here as well (just use `"FeatureVector"` property here instead). Currently, the code you have here is still inconsistent with the input.


<!-- Sent from Reviewable.io -->

2021-01-27 14:52 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 2 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r10](https://reviewable.io/reviews/maxitg/setreplace/528#-MS-25MF9sR_SIiIseMz:-MS3JUvl2j88nmCa1bxA:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/894a40ac616cf9f1f81636c51ff684a870be1077/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I'd suggest to use `BlockRandom` here instead with the `RandomSeeding` option (so that everything can be copied as a single expression).
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 26 at r1](https://reviewable.io/reviews/maxitg/setreplace/528#-MM2f9CY9ApFSNtrSVb4:-MS3K1sm3oE5wNP6nczk:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/ac2d486584e805f6c6ebb8b613daedc0c4fa21bd/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L26)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think the new example is very nice! But you need to use it here as well (just use `"FeatureVector"` property here instead). Currently, the code you have here is still inconsistent with the input.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-03 15:55 UTC, maxitg requested changes
> Reviewed 8 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 5 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 346 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MScaWZJ04QI2xTJ-jr5:-MScaWZKAWtgYnNpQbo1:bgnvs8l) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L346)):*
> ```Markdown
> - [Total Element Counts](Properties/TotalElementCounts.md)
> - [Rules](Properties/Rules.md)
> - [Feature Association](Properties/FeatureAssociation.md)
> ```

Feature Association seems to have gotten lost in the rebase.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r10](https://reviewable.io/reviews/maxitg/setreplace/528#-MS-25MF9sR_SIiIseMz:-MScZZZx-0I4qUPulbrJ:b-xz9j2q) ([raw file](https://github.com/maxitg/setreplace/blob/894a40ac616cf9f1f81636c51ff684a870be1077/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You need to give `RandomSeeding -> 2` option to `BlockRandom`, otherwise it's not reproducible. It will give you the same result if you evaluate it twice, but the result still depends on prior seeding of the random generator.

Consider, e.g.,

```wl
In[] := {BlockRandom[RandomInteger[100]],
         BlockRandom[RandomInteger[100]],
         RandomInteger[100],
         BlockRandom[RandomInteger[100]]}
Out[] = {89, 89, 89, 62}
```
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 45 at r11](https://reviewable.io/reviews/maxitg/setreplace/528#-MScZnv00OHlFLRy6B0v:-MScZnv15-o444QA5Kab:bg10t8) ([raw file](https://github.com/maxitg/setreplace/blob/97b4dc172df62cc676e9e3451c5ecfe4ebb4d192/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L45)):*
> ```Markdown
>     (WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, #, 6] &) /@
>       Table[RandomHypergraph[{3, 2}, 2], 10], LabelingFunction -> Callout]
>   ]
> ```

Move the bracket two spaces to the left so that it's on the same vertical position as the indentation on the line `BlockRandom` begins.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 22 at r11](https://reviewable.io/reviews/maxitg/setreplace/528#-MSc_ugO3ZCNOqx8Xejs:-MSc_ugO3ZCNOqx8Xejt:b4trtge) ([raw file](https://github.com/maxitg/setreplace/blob/97b4dc172df62cc676e9e3451c5ecfe4ebb4d192/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L22)):*
> ```Markdown
> 
> ```wl
> In[] := BlockRandom[
> ```

Same here, add `RandomSeeding` option to `BlockRandom`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 26 at r11](https://reviewable.io/reviews/maxitg/setreplace/528#-MSc_zW82yVw4keawMd3:-MSc_zW82yVw4keawMd4:bib9mhp) ([raw file](https://github.com/maxitg/setreplace/blob/97b4dc172df62cc676e9e3451c5ecfe4ebb4d192/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L26)):*
> ```Markdown
>     (WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, #, 6] &) /@
>       Table[RandomHypergraph[{3, 2}, 2], 10], LabelingFunction -> Callout]
>   ]
> ```

Similarly, move the `]` to spaces to the left. Now it looks like as if it's closing `FeatureSpacePlot`.


<!-- Sent from Reviewable.io -->

2021-02-03 16:40 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 5 unresolved discussions (waiting on @maxitg and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 45 at r11](https://reviewable.io/reviews/maxitg/setreplace/528#-MScZnv00OHlFLRy6B0v:-MScl4vYDs_ShJazu1Zt:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/97b4dc172df62cc676e9e3451c5ecfe4ebb4d192/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L45)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Move the bracket two spaces to the left so that it's on the same vertical position as the indentation on the line `BlockRandom` begins.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 22 at r11](https://reviewable.io/reviews/maxitg/setreplace/528#-MSc_ugO3ZCNOqx8Xejs:-MScl63o-_AjKviU0zOf:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/97b4dc172df62cc676e9e3451c5ecfe4ebb4d192/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L22)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Same here, add `RandomSeeding` option to `BlockRandom`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 26 at r11](https://reviewable.io/reviews/maxitg/setreplace/528#-MSc_zW82yVw4keawMd3:-MScl6Wa2jwaDX1yROzr:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/97b4dc172df62cc676e9e3451c5ecfe4ebb4d192/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L26)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Similarly, move the `]` to spaces to the left. Now it looks like as if it's closing `FeatureSpacePlot`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-03 16:51 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md, line 346 at r7](https://reviewable.io/reviews/maxitg/setreplace/528#-MScaWZJ04QI2xTJ-jr5:-MSclM7h0sz0bYVJWCIA:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/cb1c1da09a1f70f5e2621e9a39ced398085393e4/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md#L346)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Feature Association seems to have gotten lost in the rebase.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-03 17:16 UTC, maxitg requested changes
> Reviewed 5 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 1 unresolved discussion (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r10](https://reviewable.io/reviews/maxitg/setreplace/528#-MS-25MF9sR_SIiIseMz:-MScsGIjBTzclOlw72tc:b-c8jcuu) ([raw file](https://github.com/maxitg/setreplace/blob/894a40ac616cf9f1f81636c51ff684a870be1077/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

You need to give `RandomSeeding -> 2` option to `BlockRandom`, otherwise it's not reproducible. It will give you the same result if you evaluate it twice, but the result still depends on prior seeding of the random generator.

Consider, e.g.,

```wl
In[] := {BlockRandom[RandomInteger[100]],
         BlockRandom[RandomInteger[100]],
         RandomInteger[100],
         BlockRandom[RandomInteger[100]]}
Out[] = {89, 89, 89, 62}
```
</blockquote></details>

I'm getting different outputs for both examples. Are you sure you evaluated the same `BlockRandom` with the same `RandomSeeding` to get those pictures?


<!-- Sent from Reviewable.io -->

2021-02-04 11:27 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r10](https://reviewable.io/reviews/maxitg/setreplace/528#-MS-25MF9sR_SIiIseMz:-MSgl99m1K93orwY2K_r:b1ze7n) ([raw file](https://github.com/maxitg/setreplace/blob/894a40ac616cf9f1f81636c51ff684a870be1077/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I'm getting different outputs for both examples. Are you sure you evaluated the same `BlockRandom` with the same `RandomSeeding` to get those pictures?
</blockquote></details>

Maybe I see the problem: I used a different RandomSeeding for Vector and for Association. But when I use the same RandomSeeding I still get different pictures. I think that the problem is that  Values[#["FeatureAssociation"]] is a List of Lists for the presence of the quantiles of the distributions of degrees...

Thus:
```wl
In[] := Values@featureAssociation == featureVector
Out[] = False

In[] := Flatten /@ Values@ featureAssociation == featureVector
Out[] = True
```

Do we want to have them the same behaviour?


<!-- Sent from Reviewable.io -->

2021-02-04 14:43 UTC, maxitg requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 1 unresolved discussion (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r10](https://reviewable.io/reviews/maxitg/setreplace/528#-MS-25MF9sR_SIiIseMz:-MShTU8OC1pJj4DzbfMk:birrd5o) ([raw file](https://github.com/maxitg/setreplace/blob/894a40ac616cf9f1f81636c51ff684a870be1077/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Maybe I see the problem: I used a different RandomSeeding for Vector and for Association. But when I use the same RandomSeeding I still get different pictures. I think that the problem is that  Values[#["FeatureAssociation"]] is a List of Lists for the presence of the quantiles of the distributions of degrees...

Thus:
```wl
In[] := Values@featureAssociation == featureVector
Out[] = False

In[] := Flatten /@ Values@ featureAssociation == featureVector
Out[] = True
```

Do we want to have them the same behaviour?
</blockquote></details>

I don't think that's a big issue (although may be worth mentioning in the documentation).

I was referring not to the differences between the `"FeatureVector"` and `"FeatureAssociation"`, but to the fact that I'm getting different outputs for your inputs with your seeds. E.g.,

```wl
In[] := BlockRandom[
  FeatureSpacePlot[#["FeatureVector"] -> Image[#["FinalStatePlot"], ImageSize -> Tiny] & /@
    (WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, #, 6] &) /@
      Table[RandomHypergraph[{3, 2}, 2], 10], LabelingFunction -> Callout], RandomSeeding -> 2
]
```

<img src="https://files.reviewableusercontent.io/images/reviewable/1479325/ibw0a7U6q6nKlHnpSwuttuO5/image.png" width="478.2">

I thought maybe it was platform-dependent, but I tried on a Docker Linux image (just the values not the pictures), and I'm getting the same result as on a Mac, still different from yours, and that was in a different WL version as well.


<!-- Sent from Reviewable.io -->

2021-02-04 15:14 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528)* status: all files reviewed, 1 unresolved discussion (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 31 at r10](https://reviewable.io/reviews/maxitg/setreplace/528#-MS-25MF9sR_SIiIseMz:-MSh_weHBGt6G_fIV5wa:beshqfm) ([raw file](https://github.com/maxitg/setreplace/blob/894a40ac616cf9f1f81636c51ff684a870be1077/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L31)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I don't think that's a big issue (although may be worth mentioning in the documentation).

I was referring not to the differences between the `"FeatureVector"` and `"FeatureAssociation"`, but to the fact that I'm getting different outputs for your inputs with your seeds. E.g.,

```wl
In[] := BlockRandom[
  FeatureSpacePlot[#["FeatureVector"] -> Image[#["FinalStatePlot"], ImageSize -> Tiny] & /@
    (WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, #, 6] &) /@
      Table[RandomHypergraph[{3, 2}, 2], 10], LabelingFunction -> Callout], RandomSeeding -> 2
]
```

<img src="https://files.reviewableusercontent.io/images/reviewable/1479325/ibw0a7U6q6nKlHnpSwuttuO5/image.png" width="478.2">

I thought maybe it was platform-dependent, but I tried on a Docker Linux image (just the values not the pictures), and I'm getting the same result as on a Mac, still different from yours, and that was in a different WL version as well.
</blockquote></details>

Oh sorry now I see what was happening, I was using in my code 20 random hyper graphs instead of 10. I changed it to 10 and now is the same as yours.


<!-- Sent from Reviewable.io -->

2021-02-04 15:17 UTC, maxitg approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/528#-:-MShbgNQDecMbzFT7IZA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-04 15:27 UTC, merged