Inplace builds
maxitg/SetReplace pull request #529
Opened 2020-11-20 22:32 UTC by taliesinb

This is ready for code review, although I still need to update the documentation to explain the new workflow, and we still need to fix the Ant build script. But we can start looking through the code in the meantime. Note this incorporates the changes from https://github.com/maxitg/SetReplace/pull/526

2020-11-21 19:42 UTC, taliesinb commented
@maxitg CircleCI is failing because it the images don't have GitLink on them apparently. Should we add it to the images?

2020-11-21 20:19 UTC, taliesinb commented
I added an explicit `Quiet` so that the CI build doesn't failure because of missing GitLink (but it will fail if any *other* message occurs). I did this so that we could get it to test everything else, which might show up other problems. It's now run a full test suite, and the only failure in the CI tests came from the without GitLink available the value of `$SetReplaceLibraryGitSHA` is `Missing[]` and so the corresponding test fails. 

This is good news! It indicates that is the only remaining issue. I think we should keep the `Quiet` in the build script, since a test failure will still result as we saw above and we'll always get more info that way.

2020-11-25 18:56 UTC, maxitg requested changes
This looks to be a fantastic workflow! One extra thing I like about it is that we can eventually separate `DevUtils` into a separate repository, and use it in multiple packages which would save us from lots of duplicated code.

> Reviewed 24 of 28 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/529#-:-MN-__gaCEvFii-0QPrY:b7yjjrf)* status: all files reviewed, 51 unresolved discussions (waiting on @aokellermann, @daneelsan, @maxitg, and @taliesinb)

___
*[dev_build.wls, line 1 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv5H-J8td_7v9TK05c:-MMv5H-J8td_7v9TK05d:bj558k7) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/dev_build.wls#L1)):*
> ```
> #!/usr/bin/env wolframscript
> ```

Looks like this one should not be here.
___
*[install.wls, line 8 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv6UzFAkrEUInohvo1:-MMv6UzFAkrEUInohvo2:bccj6hc) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/install.wls#L8)):*
> ```
>   Print["Message occurred during loading of DevUtils. Build failed."];
>   Exit[1];
> ];
> ```

I think we should wrap everything in `Check` because messages can occur in `InstallGitLink[]`, `PacletFind[...]`, etc., and it's much easier to deal with a single check capturing everything than individual ones that can be missed.

The same applies to the other scripts.
___
*[README.md, line 107 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv8vA48fkTBdOliUAi:-MMv8vA48fkTBdOliUAj:bqixdf6) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/README.md#L107)):*
> ```Markdown
> ## Build Instructions
> 
> For users who wish to make use of SetReplace functionality, and not modify the source code itself, we recommend simply building and installing the paclet.
> ```

Use italic *SetReplace* as is a convention throughout the documentation.
___
*[README.md, line 118 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv9RAo07EVfK4NOgxu:-MMv9RAo07EVfK4NOgxv:b-c9v55e) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/README.md#L118)):*
> ```Markdown
> Please note that if you do not have GitLink installed, it will be installed for you.
> 
> For more info about doing development on the SetReplace codebase and the associated workflows, see the Contributing guide.
> ```

Use italic *SetReplace*.
___
*[README.md, line 118 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMvAAoQ9IkcHxNDL4dz:-MMvAAoQ9IkcHxNDL4e-:bfdscx0) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/README.md#L118)):*
> ```Markdown
> Please note that if you do not have GitLink installed, it will be installed for you.
> 
> For more info about doing development on the SetReplace codebase and the associated workflows, see the Contributing guide.
> ```

"Contributing guide" should be a link.
___
*[README.md, line 120 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMvAk8C6VMLY8_0eBFu:-MMvAk8C6VMLY8_0eBFv:b-9n4zxc) ([raw file](https://github.com/maxitg/setreplace/blob/b57a7079384e111e105e3a981e97c34404657dcc/README.md#L120)):*
> ```Markdown
> 3. Run `./install.wls` to install the paclet into your Wolfram system.
> 4. Evaluate `PacletDataRebuild[]` in all running Wolfram kernels.
> 5. Evaluate ``<< SetReplace` `` every time before using the package.
> ```

Don't remove this line because some users might not know how packages work.
___
*[.github/CONTRIBUTING.md, line 83 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxBY9z83AedOd0y8re:-MMxBY9z83AedOd0y8rf:b-yxhdle) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L83)):*
> ```Markdown
> ### Building in-place
> 
> The main workflow we recommend is what we are calling an "in-place build". This largely happens automatically when you load the SetReplace package by calling `Get["~/git/SetReplace/Kernel/init.m"]` or equivalent. If the C++ library has not already been built, it will automatically be built for you, and the resulting libraries placed in the `LibraryResources` subdirectory of the repository root.
> ```

Use italics for *SetReplace*.
___
*[.github/CONTRIBUTING.md, line 85 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxC9Z80GmHgkdhTFJk:-MMxC9Z80GmHgkdhTFJl:b-w7i1in) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L85)):*
> ```Markdown
> The main workflow we recommend is what we are calling an "in-place build". This largely happens automatically when you load the SetReplace package by calling `Get["~/git/SetReplace/Kernel/init.m"]` or equivalent. If the C++ library has not already been built, it will automatically be built for you, and the resulting libraries placed in the `LibraryResources` subdirectory of the repository root.
> 
> If you later modify the C++ code and call `Get[...]` again, the library will be automatically rebuilt, and hot-loaded into your current Mathematica session (you do not need to Quit). Moreover, builds of the library will be cached based on the hash of the C++ code, making it easy to switch quickly between several library versions (say, in different Git branches).
> ```

`Quit` should be formatted as code.
___
*[.github/CONTRIBUTING.md, line 105 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxCpEG6svx8VqGNzry:-MMxCpEHB8Yl6fA1yK7Y:b-h2mqzm) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L105)):*
> ```Markdown
> ### Build Paclets
> 
> You may occasionally want to build and install a paclet from the current state of the repository. This will package together all the Wolfram Language source code, along with the library, and various metadata, into a single ".paclet" file, which has a automatically computed version number associated with it.
> ```

"... has a automatically ..." -> "... has an automatically ..."
___
*[.github/CONTRIBUTING.md, line 123 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxF1Kr0wuWGRUcyICV:-MMxF1Kr0wuWGRUcyICW:bfcrdfa) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L123)):*
> ```Markdown
> ```
> 
> The paclet will be installed in your system, replacing any existing version of the paclet you may have. This will allow you to load the paclet in future by running simply ``Get["SetReplace`"] ``.
> ```

in ***the*** future
___
*[.github/CONTRIBUTING.md, line 125 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxF5REB4QZsy8TU3jn:-MMxF5REB4QZsy8TU3jo:b-l92rns) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L125)):*
> ```Markdown
> The paclet will be installed in your system, replacing any existing version of the paclet you may have. This will allow you to load the paclet in future by running simply ``Get["SetReplace`"] ``.
> 
> A less frequently updated version is available through the Wolfram public paclet server and can be installed with `PacletInstall["SetReplace"]`.
> ```

If we are going to mention this, it should be in the README since it's not very useful for developers usually being at least a week old.
___
*[.github/CONTRIBUTING.md, line 153 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxFVbn8F9YX1zb7cu-:-MMxFVbn8F9YX1zb7cu0:b-xxyhn5) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L153)):*
> ```Markdown
> ### Automated tests
> 
> To run the tests, `cd` to the repository root, and run `./test.wls` from the command line. Note that `./test.wls` will automatically rebuild libSetReplace for you before running the tests if your libSetR [...]

2020-11-25 20:46 UTC, taliesinb reviewed
Agree -- it would be nice to share these utilities.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/529#-:-MN-xdgc1DODqaW0mMWJ:bdhum2w)* status: 7 of 26 files reviewed, 49 unresolved discussions (waiting on @aokellermann, @daneelsan, @maxitg, and @taliesinb)

___
*[dev_build.wls, line 1 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv5H-J8td_7v9TK05c:-MN-xn6rEvdYV9lGJb8S:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/dev_build.wls#L1)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Looks like this one should not be here.
</blockquote></details>

Done.
___
*[install.wls, line 8 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv6UzFAkrEUInohvo1:-MN-y9JwAEH0XU1j4NI2:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/install.wls#L8)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think we should wrap everything in `Check` because messages can occur in `InstallGitLink[]`, `PacletFind[...]`, etc., and it's much easier to deal with a single check capturing everything than individual ones that can be missed.

The same applies to the other scripts.
</blockquote></details>

Done.
___
*[README.md, line 107 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv8vA48fkTBdOliUAi:-MN-yPzY4v2o94RTvwan:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/README.md#L107)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use italic *SetReplace* as is a convention throughout the documentation.
</blockquote></details>

Done.
___
*[README.md, line 118 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMv9RAo07EVfK4NOgxu:-MN-yQgpBxKzZqcJBfcY:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/README.md#L118)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use italic *SetReplace*.
</blockquote></details>

Done.
___
*[README.md, line 118 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMvAAoQ9IkcHxNDL4dz:-MN-yZ865j413ZWHSyVZ:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/README.md#L118)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

"Contributing guide" should be a link.
</blockquote></details>

Done.
___
*[README.md, line 120 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MMvAk8C6VMLY8_0eBFu:-MN-z2QS7by55qZU1Rq5:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/b57a7079384e111e105e3a981e97c34404657dcc/README.md#L120)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Don't remove this line because some users might not know how packages work.
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 83 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxBY9z83AedOd0y8re:-MN-zM77A1P6xr0fF8Ov:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L83)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Use italics for *SetReplace*.
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 85 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxC9Z80GmHgkdhTFJk:-MN-zQIr9c8JGCKrri_e:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L85)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`Quit` should be formatted as code.
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 105 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxCpEG6svx8VqGNzry:-MN-zSiBDiMR4Szwpq9v:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L105)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

"... has a automatically ..." -> "... has an automatically ..."
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 123 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxF1Kr0wuWGRUcyICV:-MN-zVDP-mFRxDZ6QIf6:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L123)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

in ***the*** future
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 125 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxF5REB4QZsy8TU3jn:-MN-zX0-Eep6NtFspAG9:binf466) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L125)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

If we are going to mention this, it should be in the README since it's not very useful for developers usually being at least a week old.
</blockquote></details>

I'll just remove it.
___
*[.github/CONTRIBUTING.md, line 153 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxFVbn8F9YX1zb7cu-:-MN-zZ37BLL1EkEqFiwa:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L153)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Similarly, *libSetReplace* and *SetReplace* should be italic.
</blockquote></details>

Done.
___
*[.github/CONTRIBUTING.md, line 394 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMxG2tr5k3p53NYb4Ag:-MN0-zQxD9iNrqcPwqa8:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/.github/CONTRIBUTING.md#L394)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This needs to be updated as well to explain how `DevUtils` work.
</blockquote></details>

Done.
___
*[DevUtils/Console.m, line 6 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN-KRGd6fVZhsqsNn5a:-MN05Acb5qAchEgWvsWE:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/Console.m#L6)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Shouldn't we have a usage message for these two as well since they are public?
</blockquote></details>

Done.
___
*[DevUtils/Console.m, line 9 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN-Hs3d8urSjHOU9cTP:-MN05BvK1ZIIprHYzAP3:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/Console.m#L9)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove the empty line.
</blockquote></details>

Done.
___
*[DevUtils/Console.m, line 20 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN-I5MX3ZtTt0JjXNIK:-MN05Gv0DgE8uHSGt47C:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/Console.m#L20)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The periods at the end of printed lines should be consistent.
</blockquote></details>

Done.
___
*[DevUtils/Console.m, line 36 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN-IVF-6eeQumpbF7S4:-MN05Gg18TYogp94Lwl5:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/Console.m#L36)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Remove the empty line.
</blockquote></details>

Done.
___
*[DevUtils/Consol [...]

2020-11-25 20:47 UTC, taliesinb reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/529)* status: 7 of 26 files reviewed, 49 unresolved discussions (waiting on @aokellermann, @daneelsan, and @maxitg)

___
*[DevUtils/BuildLibrary.m, line 173 at r2](https://reviewable.io/reviews/maxitg/setreplace/529#-MMzwJS2-gRCIejwokn2:-MN09BsmBDxWixmTpYbc:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/7f560a00d7c3855db96481fa7bcfc64ddb379f3a/DevUtils/BuildLibrary.m#L173)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Shouldn't it be `127` if this is called before the build and we claim in the usage that `128` is the maximum?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-25 22:23 UTC, maxitg requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/529)* status: 7 of 26 files reviewed, 52 unresolved discussions (waiting on @aokellermann, @daneelsan, @maxitg, and @taliesinb)

___
*[DevUtils/GitLink.m, line 10 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN06fA16p0MKZfJDT87:-MN06fA16p0MKZfJDT88:bh315gq) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/GitLink.m#L10)):*
> ```objc
> (* unfortunately, owing to a bug in GitLink, GitLink *needs* to be on the $ContextPath or GitRepo objects
> end up in the wrong context, since they are generated in a loopback link unqualified *)
> $GitLinkAvailableQ := $GitLinkAvailableQ = !FailureQ[Quiet @ Check[Needs["GitLink`"], $Failed]];
> ```

I think the caching here won't work if `$GitLinkAvailableQ` is called first, then `GitLink` is installed, and then `$GitLinkAvailableQ` is called again.
___
*[DevUtils/GitLink.m, line 38 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN0E1-u3Dwi-CokWQqk:-MN0E1-u3Dwi-CokWQql:bfzbaen) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/GitLink.m#L38)):*
> ```objc
> "
> 
> InstallGitLink[] := If[PacletFind["GitLink", "Internal" -> All] === {},
> ```

Prepend ``PacletManager` `` context to `PacletFind` and `PacletInstall`. The RE build does not work otherwise.
___
*[scripts/re_pack_paclet.wls, line 20 at r4](https://reviewable.io/reviews/maxitg/setreplace/529#-MN0Hf3i8bdQt3CYAPuD:-MN0Hf3i8bdQt3CYAPuE:b7nd8l4) ([raw file](https://github.com/maxitg/setreplace/blob/dfbbdbbba0fa4dbbd3fe3db7832deeba62b78cb1/scripts/re_pack_paclet.wls#L20)):*
> ```
> 
> $opts = {
>   "RootDirectory" -> $buildDir,
> ```

This root directory does not have `.git` and `version.wl`, so some of the git-related functions fail (see the comment in the `xml` file).


<!-- Sent from Reviewable.io -->

2020-11-25 22:52 UTC, taliesinb reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/529)* status: 7 of 26 files reviewed, 52 unresolved discussions (waiting on @aokellermann, @daneelsan, and @maxitg)

___
*[DevUtils/GitLink.m, line 10 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN06fA16p0MKZfJDT87:-MN0asc5DXBia7ykOa4V:buwnho6) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/GitLink.m#L10)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think the caching here won't work if `$GitLinkAvailableQ` is called first, then `GitLink` is installed, and then `$GitLinkAvailableQ` is called again.
</blockquote></details>

I've turned off caching.
___
*[DevUtils/GitLink.m, line 38 at r3](https://reviewable.io/reviews/maxitg/setreplace/529#-MN0E1-u3Dwi-CokWQqk:-MN0a8Tf1cOPRnR16yyE:blp7h4r) ([raw file](https://github.com/maxitg/setreplace/blob/e10300ec7897ed5fb32ea91383f106c3fad33592/DevUtils/GitLink.m#L38)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Prepend ``PacletManager` `` context to `PacletFind` and `PacletInstall`. The RE build does not work otherwise.
</blockquote></details>

That won't work under 12.1, unfortunately, since those symbols were moved. I'll just PackageImport["PacletManager`"], which won't have any real effect >= 12.1
___
*[scripts/re_pack_paclet.wls, line 20 at r4](https://reviewable.io/reviews/maxitg/setreplace/529#-MN0Hf3i8bdQt3CYAPuD:-MN0a1BJDdFl0p3cDzmy:b-t64z0v) ([raw file](https://github.com/maxitg/setreplace/blob/dfbbdbbba0fa4dbbd3fe3db7832deeba62b78cb1/scripts/re_pack_paclet.wls#L20)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

This root directory does not have `.git` and `version.wl`, so some of the git-related functions fail (see the comment in the `xml` file).
</blockquote></details>

Fixed by introducing the new RepositoryDirectory option.


<!-- Sent from Reviewable.io -->

2020-11-26 02:30 UTC, maxitg approved these changes
The RE builds still fail, but as discussed, we can merge now and fix it on Monday (since they only affect me anyway). There is a small typo in the new text, you can open a new PR to fix it. Other than that, everything looks ok.

> Reviewed 10 of 20 files at r4, 1 of 4 files at r5, 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/529#-:-MN1NLju0SPzc7kaUJbv:bdgrz9w)* status: all files reviewed, 2 unresolved discussions (waiting on @aokellermann, @daneelsan, and @taliesinb)

___
*[README.md, line 118 at r6](https://reviewable.io/reviews/maxitg/setreplace/529#-MN1JZOSEBNans7P1c_N:-MN1JZOSEBNans7P1c_O:b5d1srh) ([raw file](https://github.com/maxitg/setreplace/blob/e0ae9b89cba3aba2f86ad53d25a44278916c9170/README.md#L118)):*
> ```Markdown
> Please note that if you do not have GitLink installed, it will be installed for you.
> 
> Now that you have installed the *SetReplace* paclet, you should evaluate ``<< SetReplace` `` every time you start a fresh Mathematica session. This will load the paclet and bring the various functions into scope, so that you can call thaem.
> ```

Typo: thaem -> them.
___
*[scripts/re_build_SetReplace.xml, line 15 at r1](https://reviewable.io/reviews/maxitg/setreplace/529#-MN1MTj7EhRVjOLRU6is:-MN1MTj7EhRVjOLRU6it:bjsxjs9) ([raw file](https://github.com/maxitg/setreplace/blob/c9990bd63f405e60a8e1b481fd1dbc5c6dc57107/scripts/re_build_SetReplace.xml#L15)):*
> ```XML
>     Component (platform-independent)
>   -->
>   <target name='Component.SetReplace.execute' extensionOf='Component.execute'>
> ```

This did not work. Here is the log:

```
Build 'Internal / SetReplace / Component / Build' #168, default branch '<default>'
Triggered 2020-11-25 20:05:59 by 'Snapshot dependency; Max Piskunov (maxp); Internal / SetReplace / Build, build #194'
Started 2020-11-25 20:14:28 on agent 'build34'
Finished 2020-11-25 20:14:38 with status FAILURE 'Exit code 1 (Step: NativeLibrary.build (Ant)) (new)'
VCS revisions: 'ReScripts' (Git, instance id 11676): 'b4dc2a7f6e34b97dc847462aac30d235b342514d' (branch: 'refs/heads/master', checkout rules: '+:. => re-scripts')
               'Internal_SetReplace_SetReplace' (Git, instance id 13859): 'e0ae9b89cba3aba2f86ad53d25a44278916c9170' (branch: 'refs/heads/internalBuild', checkout rules: '+:. => SetReplace')
TeamCity URL https://teamcity.wolfram.com/viewLog.html?buildId=1797868&buildTypeId=Internal_SetReplace_Component_Build 
TeamCity server version is 2020.1.4 (build 78906), server timezone: CST (UTC-06:00)

[20:05:59]E: bt15934 (8m:38s)
[20:05:59]i: TeamCity server version is 2020.1.4 (build 78906)
[20:06:00] : Collecting changes in 3 VCS roots (5s)
[20:06:00] :	 [Collecting changes in 3 VCS roots] VCS Root details
[20:06:00] :		 [VCS Root details] "SetReplace" {instance id=13859, parent internal id=1366, parent id=Internal_SetReplace_SetReplace, description: "ssh://git@stash.wolfram.com:7999/pac/setreplace.git#refs/heads/internalBuild"}
[20:06:00] :		 [VCS Root details] "RETC/Internal" {instance id=12572, parent internal id=1325, parent id=Internal, description: "ssh://git@stash.wolfram.com:7999/retc/internal.git#refs/heads/master"}
[20:06:00] :		 [VCS Root details] "re-scripts" {instance id=11676, parent internal id=1300, parent id=ReScripts, description: "ssh://git@stash.wolfram.com:7999/re/re-scripts.git#refs/heads/master"}
[20:06:00]i:	 [Collecting changes in 3 VCS roots] Detecting changes in VCS root 'RETC/Internal' (used in 'Build', 'Build' and 18 other configurations)
[20:06:00]i:	 [Collecting changes in 3 VCS roots] Will collect changes for 'RETC/Internal' starting from revision c07d1689672df05b6d23e3c3cf7a409db9c37140
[20:06:00]i:	 [Collecting changes in 3 VCS roots] Detecting changes in VCS root 'SetReplace' (used in 'Build', 'Build' and 4 other configurations)
[20:06:00]i:	 [Collecting changes in 3 VCS roots] Will collect changes for 'SetReplace' starting from revision 71791b24cc36e29bb159249f44d594641d898135
[20:06:00]i:	 [Collecting changes in 3 VCS roots] VCS revisions for 'SetReplace' - 71791b24cc36e29bb159249f44d594641d898135..e0ae9b89cba3aba2f86ad53d25a44278916c9170
[20:06:00]i:	 [Collecting changes in 3 VCS roots] Processing combined checkout rule for 'SetReplace' 
[20:06:00]i:	 [Collecting changes in 3 VCS roots] Detecting changes in VCS root 're-scripts' (used in 'AlphaDocs (.html)', 'AlphaDocs (.nb)' and 393 other configurations)
[20:06:00]i:	 [Collecting changes in 3 VCS roots] Will collect changes for 're-scripts' starting from revision b4dc2a7f6e34b97dc847462aac30d235b342514d
[20:06:01]i:	 [Collecting changes in 3 VCS roots] VCS root 'SetReplace': git fetch ssh://git@stash.wolfram.com:7999/pac/setreplace.git
[20:06:04]i:	 [Collecting changes in 3 VCS roots] VCS root 'SetReplace': update ref remote name: refs/heads/internalBuild, local name: refs/heads/internalBuild, old object id: 71791b24cc36e29bb159249f44d594641d898135, new object id: e0ae9b89cba3aba2f86ad53d25a44278916c9170, result: FORCED
[20:06:04]i:	 [Collecting changes in 3 VCS roots] VCS root 'SetReplace': Remote process messages: 
                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                                                                

                                               [...]

2020-11-26 08:23 UTC, merged

2020-11-26 14:04 UTC, taliesinb commented
@maxitg The RE failure you pasted is in all likelihood because of the deletion of the XML snippet that copied the Kernel/ files into the build directory (which we believed to b e pointless!). It may actually still be pointless, and RE needs to be informed that they can remove the corresponding component so that it doesn't fail. Also, I've opened a PR to fix the typo.