Add ObjectProperties group to FeatureAssociation (and FeatureVector)
maxitg/SetReplace pull request #630
Opened 2021-03-30 13:50 UTC by mrektor

An expansions of the feature association by using some of the properties readily available in the WolframModelEvolutionObject.

2021-03-30 20:41 UTC, maxitg requested changes
Please add some examples to the PR description.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630#-:-MX3o31UATaTn2daH1Oc:b2yxpcn)* status: all files reviewed, 3 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 19 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX3qNH2BvwA2liFNv9s:-MX3qNH2BvwA2liFNv9t:biylwre) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L19)):*
> ```Markdown
> `"StructurePreserving"` transformation
> - `"ObjectProperties"`: A list of properties of the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md)
> that return a numeric value. Right now the list of properties is: "EventsCount", "TotalGenerationsCount",
> ```

`"EventsCount"` is identical to `"CausalGraphVertexCount"`. So, we should probably remove one of them.
___
*[Kernel/WolframModelEvolutionObject.m, line 971 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX3ov2r-kun24_aDFFU:-MX3ov2r-kun24_aDFFV:bg1afzv) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L971)):*
> ```objc
> 
> getNumericObjectProperties[obj_, caller_, boundary_] := <|# -> propertyEvaluate[True, boundary][obj, caller, #] & /@
>   {"EventsCount", "TotalGenerationsCount", "PartialGenerationsCount", "AllEventsCount",
> ```

`"EventsCount"` and `"AllEventsCount"` are the same thing, no need to include it twice.
___
*[Kernel/WolframModelEvolutionObject.m, line 971 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX3p2vg4P9kwJa1HgRB:-MX3p2vg4P9kwJa1HgRC:b-unqq6j) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L971)):*
> ```objc
> 
> getNumericObjectProperties[obj_, caller_, boundary_] := <|# -> propertyEvaluate[True, boundary][obj, caller, #] & /@
>   {"EventsCount", "TotalGenerationsCount", "PartialGenerationsCount", "AllEventsCount",
> ```

Also, `"TotalGenerationsCount" == "CompleteGenerationsCount" + "PartialGenerationsCount"`, so we probably don't need all three.


<!-- Sent from Reviewable.io -->

2021-03-31 10:22 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630)* status: all files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 19 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX3qNH2BvwA2liFNv9s:-MX6jnhJ5OzitGKrrSLD:bdd46vv) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L19)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`"EventsCount"` is identical to `"CausalGraphVertexCount"`. So, we should probably remove one of them.
</blockquote></details>

I Agree, but if we are going to change the process of feature extraction from the causal graph (i.e. using feature extractor) the issue is going to be that we do not really know if vertexDegree is going to be computed (even though I guess it will, as it is a really basic easy and quick statistic). Anyway it could be a pity to discard EventCount when a user just ask only for ObjectProperties feature group... but I'm afraid that implementation-wise this can start to become quite complex to handle...
___
*[Kernel/WolframModelEvolutionObject.m, line 971 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX3ov2r-kun24_aDFFU:-MX6mwlCDqxJzrJ-Hoyh:bayvjcw) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L971)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`"EventsCount"` and `"AllEventsCount"` are the same thing, no need to include it twice.
</blockquote></details>

Ok, I kept EventsCount
___
*[Kernel/WolframModelEvolutionObject.m, line 971 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX3p2vg4P9kwJa1HgRB:-MX6mzy58n_aCnGH8PhU:b-964lrk) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L971)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Also, `"TotalGenerationsCount" == "CompleteGenerationsCount" + "PartialGenerationsCount"`, so we probably don't need all three.
</blockquote></details>

Discarded TotalGenerationsCount


<!-- Sent from Reviewable.io -->

2021-03-31 11:07 UTC, mrektor reviewed
Where should I add the example of the PR? should I update the first comment? 

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630#-:-MX6xlWg9qnVVWHxcda5:b7lcsxp)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @maxitg)



<!-- Sent from Reviewable.io -->

2021-03-31 19:38 UTC, maxitg requested changes
Yes. It gives you [the template](https://github.com/maxitg/SetReplace/blob/master/.github/PULL_REQUEST_TEMPLATE.md) when you open a PR. It has the "Examples" section specifically for this purpose.

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630#-:-MX8_Kir9fw5T4yIfUDU:b-g6j0bx)* status: all files reviewed, 7 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 19 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX3qNH2BvwA2liFNv9s:-MX8ik2kA416uy2FSzAU:b-4q3733) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L19)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

I Agree, but if we are going to change the process of feature extraction from the causal graph (i.e. using feature extractor) the issue is going to be that we do not really know if vertexDegree is going to be computed (even though I guess it will, as it is a really basic easy and quick statistic). Anyway it could be a pity to discard EventCount when a user just ask only for ObjectProperties feature group... but I'm afraid that implementation-wise this can start to become quite complex to handle...
</blockquote></details>

Yes, good point. I did not think of the case where only some groups of features are requested.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 22 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8iZ465Knw_WLViw7V:-MX8iZ465Knw_WLViw7W:b-yf9fme) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L22)):*
> ```Markdown
> that return a numeric value. Right now the list of properties is: "EventsCount",
> "PartialGenerationsCount", "AllEventsDistinctElementsCount", "AllEventsEdgesCount",
> "CompleteGenerationsCount", "TerminationReason", "GenerationComplete".
> ```

`"GenerationComplete"` is equivalent to `"PartialGenerationCount" === 0`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 25 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8kHzhCX8EqsvFviSV:-MX8kHzi5oxSTiBwguOp:b-rgebil) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L25)):*
> ```Markdown
> 
> ```wl
> In[] :=  WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, 5]["FeatureAssociation"]
> ```

Formatting: remove the extra space after `In[] :=`.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 28 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8bIRR3qwdVkwkgb_l:-MX8bIRR3qwdVkwkgb_m:bxx5a9s) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L28)):*
> ```Markdown
> ```
> 
> <img src="/Documentation/Images/FeatureAssociationExample-01.png" width="621.0">"
> ```

I think instead of `-01` and `-02` it would be better to call them `FeatureAssociationExampleSingleHistory` and `FeatureAssociationExampleMultihistory`. The problem with numbers is that they might all need to be renamed if an example is added in the beginning in the future.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 14 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8bdMz-gN-fMJQ2wR9:-MX8bdMz-gN-fMJQ2wRA:b-u43kre) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L14)):*
> ```Markdown
> ```
> 
> <img src="/Documentation/Images/FeatureVectorExample-01.png" width="513.0">
> ```

Similarly here, a better name would be `FeatureVectorExampleSingleHistory`.
___
*[Kernel/WolframModelEvolutionObject.m, line 989 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8l4633rPfpc1GEYXn:-MX8l464-d41pQCJ2SOE:b3vum9v) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L989)):*
> ```objc
>     featuresSpecs_ : All] := With[{featureGroupList = fromFeaturesSpec[caller, featuresSpecs]},
>   nestedToSingleAssociation @ AssociationThread[featureGroupList -> Replace[featureGroupList, {
>     "CausalGraph" -> graphFeatureAssociation[propertyEvaluate[True, boundary][obj, caller, "CausalGraph"]],
> ```

Now that `"CausalGraph"` is just a single value, wouldn't it make more sense to make this flat and treat it like just another property? So that the list of features is flat `{"CausalGraph", "StructurePreservingFinalStateGraph", "EventsCount", "PartialGenerationsCount", ...}`.
___
*[Kernel/WolframModelEvolutionObject.m, line 979 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8ltyoEaQF0-awi05t:-MX8ltyoEaQF0-awi05u:brpwfqk) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Kernel/WolframModelEvolutionObject.m#L979)):*
> ```objc
>     featuresSpecs_ : All] := With[{featureGroupList = fromFeaturesSpec[caller, featuresSpecs]},
>   nestedToSingleAssociation @ AssociationThread[featureGroupList -> Replace[featureGroupList, {
>     "CausalGraph" ->  <| "" -> propertyEvaluate[True, boundary][obj, caller, "CausalGraph"] |>,
> ```

Formatting: there should not be a space after `<|` and before `|>`.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1926 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8lyXP48j1VJxPuqcr:-MX8lyXP48j1VJxPuqcs:bso9nwc) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Tests/WolframModelEvolutionObject.wlt#L1926)):*
> ```Mathematica
>           VerificationTest[And @@ StringQ /@ Keys[#["FeatureAssociation"]]] & /@ evolutionObjects,
> 
>           VerificationTest[And @@ (NumberQ[#] || MissingQ[#]  || GraphQ[#] || BooleanQ[#]  || StringQ[#] &)
> ```

Please, fix the formatting. I.e., no double spaces, the indentation should respect the structure of the expression, and `/@` and `&` should be at the end of lines, not in the beginning.


<!-- Sent from Reviewable.io -->

2021-04-01 10:06 UTC, mrektor reviewed
Sorry I missed that. Now I added it.

> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630#-:-MXBmcf69k8cN4M8YINj:bipxchv)* status: 1 of 9 files reviewed, 7 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 22 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8iZ465Knw_WLViw7V:-MXBmjvq13hNLivJm_SS:bw5xbk2) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L22)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`"GenerationComplete"` is equivalent to `"PartialGenerationCount" === 0`.
</blockquote></details>

Ok then I'll drop "GenerationComplete"
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 25 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8kHzhCX8EqsvFviSV:-MXBn-4-8Bwdp6FrISsW:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L25)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Formatting: remove the extra space after `In[] :=`.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 28 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8bIRR3qwdVkwkgb_l:-MXBnKYf5Nx8JKBdUK3M:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L28)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I think instead of `-01` and `-02` it would be better to call them `FeatureAssociationExampleSingleHistory` and `FeatureAssociationExampleMultihistory`. The problem with numbers is that they might all need to be renamed if an example is added in the beginning in the future.
</blockquote></details>

Done.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 14 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8bdMz-gN-fMJQ2wR9:-MXBnUq4APFgXWH85yvn:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L14)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Similarly here, a better name would be `FeatureVectorExampleSingleHistory`.
</blockquote></details>

Done.
___
*[Kernel/WolframModelEvolutionObject.m, line 989 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8l4633rPfpc1GEYXn:-MXBngNjBduMRbvmyATe:bp4gb00) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L989)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Now that `"CausalGraph"` is just a single value, wouldn't it make more sense to make this flat and treat it like just another property? So that the list of features is flat `{"CausalGraph", "StructurePreservingFinalStateGraph", "EventsCount", "PartialGenerationsCount", ...}`.
</blockquote></details>

Yes Indeed it does make sense. I added CausalGraph to the feature group of object properties. But since "StructurePreservingFinalStateGraph" is not an object property, I would treat it as a different feature group. what do you think?
___
*[Kernel/WolframModelEvolutionObject.m, line 979 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8ltyoEaQF0-awi05t:-MXBofxYCMgcovflGbWp:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Kernel/WolframModelEvolutionObject.m#L979)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Formatting: there should not be a space after `<|` and before `|>`.
</blockquote></details>

Done.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1926 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8lyXP48j1VJxPuqcr:-MXBpWQ-8CQjGJiMDE6Y:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Tests/WolframModelEvolutionObject.wlt#L1926)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Please, fix the formatting. I.e., no double spaces, the indentation should respect the structure of the expression, and `/@` and `&` should be at the end of lines, not in the beginning.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-01 14:54 UTC, maxitg requested changes
> Reviewed 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630)* status: all files reviewed, 6 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 20 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCssVY8zgHejRzLH8U:-MXCssVY8zgHejRzLH8V:bwp88rs) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L20)):*
> ```Markdown
> - `"ObjectProperties"`: A list of properties of the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/WolframModelAndWolframModelEvolutionObject.md)
> that return a numeric value. Right now the list of properties is: [`"CausalGraph"`](/Documentation/SymbolsAndFunctions/
> WolframModelAndWolframModelEvolutionObject/Properties/CausalGraphs.md), "EventsCount",
> ```

It would actually be nice to link the rest of them to the documentation as well. It's just weird that `"CausalGraph"` is linked and the rest are not given that they all have documentation pages.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 40 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCsUfH5Cp4IgqYYalK:-MXCsUfH5Cp4IgqYYalL:b2mj9dj) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L40)):*
> ```Markdown
> ```
> 
> <img src="/Documentation/Images/FeatureAssociationFeatureSpacePlot.png" width="684.6">
> ```

I'm getting a different output here.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 14 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCrXNt35-sVB66Z-Hj:-MXCrXNt35-sVB66Z-Hk:bvxfz21) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L14)):*
> ```Markdown
> ```
> 
> <img src="/Documentation/Images/FeatureVectorExampleSingleHistory.png" width="513.0">
> ```

The output is now inconsistent with the input.
___
*[Kernel/WolframModelEvolutionObject.m, line 989 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8l4633rPfpc1GEYXn:-MXCtCzABB5w2awIVCR9:b2wl121) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L989)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Yes Indeed it does make sense. I added CausalGraph to the feature group of object properties. But since "StructurePreservingFinalStateGraph" is not an object property, I would treat it as a different feature group. what do you think?
</blockquote></details>

The question is, does it make sense to have groups at all? After all, `"StructurePreservingFinalStateGraph"` is just a `"FinalState"` property converted so that the WL feature extractor can understand it.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1926 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8lyXP48j1VJxPuqcr:-MXCuElJ4cYMp9cmvsCi:bphslmk) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Tests/WolframModelEvolutionObject.wlt#L1926)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is still a double space on this line.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1931 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCuNEC31cERT8R-mlk:-MXCuNEC31cERT8R-mll:boi3yzf) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Tests/WolframModelEvolutionObject.wlt#L1931)):*
> ```Mathematica
>           VerificationTest[SameQ @@
>             (Replace[#, _?(NumberQ[#] || MissingQ[#] || GraphQ[#] || StringQ[#] &) -> 1, Infinity] &
>               [#["FeatureAssociation"]] & /@ evolutionObjects)],
> ```

`[` should be on the previous line.

I.e., you would not write the call to a named function as

```wl
Replace
  [{1, 2, 3}, 1 -> 4]
```

Pure functions are no different.


<!-- Sent from Reviewable.io -->

2021-04-01 15:46 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630)* status: 2 of 9 files reviewed, 6 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 20 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCssVY8zgHejRzLH8U:-MXD3-1uB4GWGV93tOGH:b-7ql1td) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L20)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

It would actually be nice to link the rest of them to the documentation as well. It's just weird that `"CausalGraph"` is linked and the rest are not given that they all have documentation pages.
</blockquote></details>

fixed
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 40 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCsUfH5Cp4IgqYYalK:-MXD4Rd-D25bECGGQUDG:bontn8n) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L40)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

I'm getting a different output here.
</blockquote></details>

should be ok now
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md, line 14 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCrXNt35-sVB66Z-Hj:-MXD4u2Y0mAKFAJSCriV:b-h6y7gv) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureVector.md#L14)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The output is now inconsistent with the input.
</blockquote></details>

should be ok
___
*[Kernel/WolframModelEvolutionObject.m, line 989 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8l4633rPfpc1GEYXn:-MXD4yP27Hgl2TEiTCwU:bxx71uo) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L989)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

The question is, does it make sense to have groups at all? After all, `"StructurePreservingFinalStateGraph"` is just a `"FinalState"` property converted so that the WL feature extractor can understand it.
</blockquote></details>

Well it did make sense, I think it is nice to have the possibility of including feature groups we still have not thought about... Also it would make sense if one would explore specific aspects of the Wolfram model and avoiding others. But if you prefer we can just get rid of them
___
*[Tests/WolframModelEvolutionObject.wlt, line 1926 at r2](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8lyXP48j1VJxPuqcr:-MXD5W2D7QH777qFhBI2:b8pz2kh) ([raw file](https://github.com/maxitg/setreplace/blob/4c21c807aa6877f28527ff8a18527e1540955826/Tests/WolframModelEvolutionObject.wlt#L1926)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

There is still a double space on this line.
</blockquote></details>

sorry I missed that.
___
*[Tests/WolframModelEvolutionObject.wlt, line 1931 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCuNEC31cERT8R-mlk:-MXD5wFH3Z77CsvF375c:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Tests/WolframModelEvolutionObject.wlt#L1931)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

`[` should be on the previous line.

I.e., you would not write the call to a named function as

```wl
Replace
  [{1, 2, 3}, 1 -> 4]
```

Pure functions are no different.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-01 21:15 UTC, maxitg requested changes
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630)* status: all files reviewed, 3 unresolved discussions (waiting on @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 20 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCssVY8zgHejRzLH8U:-MXEGYF88zyzPyOli_Yo:bcl5d74) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L20)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

fixed
</blockquote></details>

Same here — the links are broken.
___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 8 at r4](https://reviewable.io/reviews/maxitg/setreplace/630#-MXEGQbA5W91N3FKccWe:-MXEGQbA5W91N3FKccWf:bphykjf) ([raw file](https://github.com/maxitg/setreplace/blob/a07f95aa6edfe0688f013c0ab37a17c6dd05d2ea/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L8)):*
> ```Markdown
> [`FeatureExtraction`](https://reference.wolfram.com/language/ref/FeatureExtraction.html)
> of the [`WolframModel`](/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/
> WolframModelAndWolframModelEvolutionObject.md)
> ```

You cannot put line breaks inside the links: https://github.com/maxitg/SetReplace/blob/ObjectPropertiesFeatures/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md
___
*[Kernel/WolframModelEvolutionObject.m, line 989 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8l4633rPfpc1GEYXn:-MXEGwpWCc5UwBlRBbk1:b-pu6seu) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L989)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

Well it did make sense, I think it is nice to have the possibility of including feature groups we still have not thought about... Also it would make sense if one would explore specific aspects of the Wolfram model and avoiding others. But if you prefer we can just get rid of them
</blockquote></details>

Ok, sure, but I'm not sure why the final state would be in a separate group because it is a property just like the causal graph.


<!-- Sent from Reviewable.io -->

2021-04-02 10:44 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @maxitg and @mrektor)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 8 at r4](https://reviewable.io/reviews/maxitg/setreplace/630#-MXEGQbA5W91N3FKccWe:-MXH8ovE1dxbuW955bsq:b-ld5nsc) ([raw file](https://github.com/maxitg/setreplace/blob/a07f95aa6edfe0688f013c0ab37a17c6dd05d2ea/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L8)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

You cannot put line breaks inside the links: https://github.com/maxitg/SetReplace/blob/ObjectPropertiesFeatures/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md
</blockquote></details>

I see, I thought that the push routine would have complained about a too long line... but now it should be ok.
___
*[Kernel/WolframModelEvolutionObject.m, line 989 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8l4633rPfpc1GEYXn:-MXH914K14o64lPeSRnD:bfq2y5a) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L989)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Ok, sure, but I'm not sure why the final state would be in a separate group because it is a property just like the causal graph.
</blockquote></details>

What about moving it to the "ObjectProperties" feature group while still maintaining the code that support feature groups? (Even though we would have just one feature group then...)

Anyway, having it as a separate group makes it easier to deal with the Multiway case in which the final state does not exist (implementation-wise)


<!-- Sent from Reviewable.io -->

2021-04-02 10:44 UTC, mrektor reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @maxitg)

___
*[Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md, line 20 at r3](https://reviewable.io/reviews/maxitg/setreplace/630#-MXCssVY8zgHejRzLH8U:-MXHAqYMEdQUzOnQUDNO:b-896fix) ([raw file](https://github.com/maxitg/setreplace/blob/9be9053dd73e8dac919613dfb7939689cbb7f021/Documentation/SymbolsAndFunctions/WolframModelAndWolframModelEvolutionObject/Properties/FeatureAssociation.md#L20)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Same here — the links are broken.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-13 14:54 UTC, maxitg approved these changes
> Reviewed 2 of 10 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/maxitg/setreplace/630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mrektor)

___
*[Kernel/WolframModelEvolutionObject.m, line 989 at r1](https://reviewable.io/reviews/maxitg/setreplace/630#-MX8l4633rPfpc1GEYXn:-MYAiQ1SDtnizazq0hi8:bgb70h6) ([raw file](https://github.com/maxitg/setreplace/blob/3851d41a5440b0d6d4691fa97244d1ffdcba4216/Kernel/WolframModelEvolutionObject.m#L989)):*
<details><summary><i>Previously, mrektor wrote…</i></summary><blockquote>

What about moving it to the "ObjectProperties" feature group while still maintaining the code that support feature groups? (Even though we would have just one feature group then...)

Anyway, having it as a separate group makes it easier to deal with the Multiway case in which the final state does not exist (implementation-wise)
</blockquote></details>

Ok, sure, let's keep it as it is for now. We can organize the groups better once we have more features.


<!-- Sent from Reviewable.io -->

2021-04-19 14:47 UTC, maxitg commented
Hey @mrektor, do you plan on making any other changes to this PR?

2021-04-19 15:40 UTC, merged